### ISSUE TITLE
incorrect IF condition

### ISSUE THREAD

**Issue by zuexo** [mgp25/Instagram-API#1047]
Line [2199](https://github.com/mgp25/Instagram-API/blob/4648f901a8d900accdc4b90ae35b80bd26fb89ba/src/Instagram.php#L2199) of file Instagram.php has incorrect IF condition or is it meant to be only accessible via GET request?

Note: If I may recommend instead of setting property and throwing exception when debug is enabled, it would be more convenient to set undefinedPropertyHandler and make undefined properties available all the time.
https://github.com/cweiske/jsonmapper#unknown-properties

**Comment by SteveJobzniak** [comment]
I greped and saw no $_POST ANYWHERE, and saw the same $_GET in two places.

```
$ grep -R "\\\$_GET" .
./src/http/HttpInterface.php:        if (isset($_GET['debug'])) {
./src/Instagram.php:        if (isset($_GET['debug'])) {
```

The bad news: This method of debugging is different from the class's $debug constructor parameter (which controls seeing API replies).

But we definitely won't make an automatic undefinedPropertyHandler. Because Instagram's replies need to be manually mapped to the appropriate data types. And trying to do it automatically would lead to A) Not having any control of the property types, and B) It would be impossible to look at source code to see what fields are available for each class, and C) It would lead to programmer laziness where new API fields wouldn't get added to the classes.

But throwing exceptions when nothing is in the base class is useful for programmers creating this API, hence why $_GET['debug'] maps to it. And GET variables can be set via the command line if you run php-cli instead of php.

As for users, if you want fields that are not yet mapped in the base classes, use getFullResponse() and then read it like a->normal->object.

However, all this being said, I think $_GET is indeed a bit ugly. But we don't want it in the constructor. I'll implement JSON exception throwing via a public boolean flag in the core Instagram class, in a moment.

**Comment by SteveJobzniak** [comment]
Thanks for bringing this to my attention. I had been glaring at the ugly response decoder for a while but didn't touch it. Now I had a reason to completely rewrite it, to take care of both this issue and the fact that the old response decoder was really messy.
