### ISSUE TITLE
How to view the request response from Instagram App?

### ISSUE THREAD

**Issue by samaybhavsar** [mgp25/Instagram-API#1048]
This might be a lame question. But how to debug the request response cycle from Instagram Mobile App? I can view the same for the web interface but not for the Android App. 

I tried using MITM proxy, but no luck.

**Comment by SteveJobzniak** [comment]
Hi. You need to set up a MITM proxy, and tell your device to trust its certificate so that all HTTPS traffic goes through it.

I know for a fact Fiddle works instantly via iOS, but they may use certificate pinning on Android in which case you need to hack the APK. Outside the scope of this project. Google it. Lots of guides exist.

For Android: http://docs.telerik.com/fiddler/Configure-Fiddler/Tasks/ConfigureForAndroid

For iOS: http://docs.telerik.com/fiddler/Configure-Fiddler/Tasks/ConfigureForiOS
