### ISSUE TITLE
Custom device and custom location ?

### ISSUE THREAD

**Issue by volkanaldas** [mgp25/Instagram-API#1124]
Can i use custom device and custom location ?

Example separate version codes for iPhone and android, and separate brand information

**Comment by mgp25** [comment]
@volkanaldas you can **NOT** use iphone data with this API.

And if you want to add any android device data, you can do it here: https://github.com/mgp25/Instagram-API/blob/master/src/Devices/GoodDevices.php

Regards

**Comment by SteveJobzniak** [comment]
@mgp25 @volkanaldas But don't contribute anything broken to that file. It needs to follow the contribution guidelines in that file otherwise the whole project (literally) breaks.

1. Instagram is watching and the best way to hide is to hide as popular devices (which that list does). Not some random one nobody normal uses.

2. All contributions must have references so that we can verify that you've added its _exact_ user agent correctly, otherwise Instagram can easily ban us.

3. All devices in that list must support at least 1080p graphics, so that they get the highest-quality video URLs from Instagram. They only give HD media to devices with good screens.

Good luck and open a pull request if you have any contribution to the list.

**Comment by mgp25** [comment]
@SteveJobzniak when i meant to add it, i meant in his own project, not in here
