### ISSUE TITLE
error While running

### ISSUE THREAD

**Issue by Mehran** [mgp25/Instagram-API#1132]
```
~/vendor# $ig = new \InstagramAPI\Instagram();
bash: syntax error near unexpected token `('
```

am i missed something ?

im not familiar with this commands .

**Comment by mgp25** [comment]
@Mehran do you know php? That arent commands, that is a constructor of the main class, you need create your own script.

Please read the wiki and examples.

Regards

**Comment by Mehran** [comment]
can you help how can i make it work  ? i not found any example or wiki about it . Thanks .

**Comment by mgp25** [comment]
@Mehran please read the Readme: https://github.com/mgp25/Instagram-API

**Comment by Mehran** [comment]
yes i read it but exactly i dont understand Below 

```
require __DIR__.'/../vendor/autoload.php';

$ig = new \InstagramAPI\Instagram();
```

Where i must use this ?

**Comment by mgp25** [comment]
@Mehran Since you don't know PHP and it is not an API issue. The only thing i can help you at is giving you a link where it is explained all PHP syntax, after you understood the basics, you will know what to do:

PHP. Language Reference: https://secure.php.net/manual/en/langref.php

You will find there all basic syntax, functions, variables, types etc.

Regards

**Comment by Mehran** [comment]
Thanks alot , You mean without Know PHP can't use this ? for example i see many Project with Python but i don't know python but i can Play with it .  i think without knowledge of php can Run this Project .

**Comment by mgp25** [comment]
@Mehran here is the thing, if you don't know PHP, we wont help you in your issues. Why? Because you need at least a basic understanding of how things are done, you can't expect everything to be just 1 click. This API is ultra easy to use.

If you dont know what a constructor is, how will you code your script? It is very important you know at least basics, so you can ask coherent questions.

**Comment by Mehran** [comment]
Thanks alot , i figure it how it work , Can give me example for Send comment ?
