### ISSUE TITLE
searchInAddressBook just considers contacts the first time

### ISSUE THREAD

**Issue by mbande** [mgp25/Instagram-API#1195]
I've used `searchInAddressBook` for contacts of my account, and it worked perfectly.
calling this function with a now list of contacts, it just returns the previous response.
it seems that the new contacts must be synced before ```searchInAddressBook```, is it true? or  ```searchInAddressBook``` should consider it's parameter and sync the list?

**Comment by aitte2** [comment]
Maybe instagram only allows "link address book api" call 1 time...

**Comment by mbande** [comment]
@aitte2 instagram app syncs the contact list periodically, if user allows it to do so.
i wonder the api call used for this is as `searchInAddressBook` or not. if so, `searchInAddressBook` does not work as expected. or maybe there is another api that is not implemented in this project.

**Comment by mgp25** [comment]
I dont think i'll ever add that. If you want, research it and send a pull request

Regards

**Comment by SteveJobzniak** [comment]
@mbande Try these commits. :)

https://github.com/mgp25/Instagram-API/commit/d5cf7d3d9052ccda728c0f803b50e2ec909d1f39

https://github.com/mgp25/Instagram-API/commit/8376ff61b4357ca4291b82d971140382665c1436

Use `linkAddressBook()` and then `unlinkAddressBook()`. Just be careful and don't link/unlink rapidly because Instagram would probably think you're spamming them.
