### ISSUE TITLE
How to Reed feedback title?

### ISSUE THREAD

**Issue by lonlyman** [mgp25/Instagram-API#1199]
While i am testing the api , i sent the same comment to a Media twice by mistake , but i note something interesting , instagrams respond with a nice message .

`"feedback_title": "Duplicate Comment"`

how can i get this message without all other stuff within the responde ?
is there a getter for Feedback Title?

With Regards.

**Comment by mgp25** [comment]
@lonlyman have you read the documentation? `getFeedbackTitle()`

**Comment by lonlyman** [comment]
Dear @mgp25 , i am an educated man, and yes i did search and read before creating this issues.
here is the $RESPONSE:


` {"message": "feedback_required", "feedback_title": "Duplicate Comment", "feedback_message": "It looks like you already left this comment. Try posting a new one.", "feedback_url": "repute/report_problem/instagram_comment/", "feedback_appeal_label": "Report problem", "feedback_ignore_label": "OK", "feedback_action": "report_problem", "status": "fail"}`

try{
post comment 
}catch (\Exception $e){
```
$e->getFeedbackTitle();
$e->getFeedbackMessage();
```
}

None of them worked , but an error message returned that there is no methods called getFeedbackTitle .

**Comment by mgp25** [comment]
@lonlyman because it is an exception but i'll add more exceptions when i have some free time. I'll ping you when its done, nevertheless if i forget it, ping me

Regards

**Comment by lonlyman** [comment]
@mgp25 So it is my turn to tell you " have you read the documentation?"
LOL just joking ...

Thank you in advanced

**Comment by SteveJobzniak** [comment]
@lonlyman Hi. Since we keep getting requests from people who want to get extra server reply details in some exceptions, I thought it was finally time to do something about it.

So I've extended the exception system. Every exception in this library is derived from InstagramException, which in turn now has brand-new `hasResponse()` and `getResponse()` functions!

With this, people can finally get complete server response details when they need it.

I've created an example in https://github.com/mgp25/Instagram-API/blob/master/examples/exceptionDetailsExample.php

In your case the code would be like:

```php
try{
     post comment 
} catch (\InstagramAPI\Exception\FeedbackRequiredException $e) {
    if ($e->hasResponse()) {
        var_dump($e->getResponse()->getFeedbackTitle());
    }
}
```

There will most likely not be any more exceptions. The set we have is perfect. It covers all critical CORE errors (such as "login_required", "feedback_required", "sentry_block", etc), and it also covers all per-endpoint problems via EndpointException.

@mgp25 The reason it's a bad idea to add more exceptions is that there are a few hundred endpoints, with about 5 different error messages each. That's like 500-1000 different error strings. All of which can change at any time. So it's just a bad idea to add more exceptions. Instead, to identify the actual problem in an EndpointException, users can easily search its getMessage() for an error string such as "Could not delete". And if they want more details about what happened, the user can always look at `hasResponse()` and `getResponse()` to see the full server response.

**Comment by lonlyman** [comment]
@SteveJobzniak  , is it in "composer require mgp25/instagram-php" 

```
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
Using version ^2.0 for mgp25/instagram-php
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files

```

**Comment by mgp25** [comment]
@lonlyman 

```
composer require mgp25/instagram-php dev-master
```

**Comment by mobbidigital** [comment]
I'm having this error and I can not fix it, instagram platform
print http://prntscr.com/ih0arz
