### ISSUE TITLE
resize image

### ISSUE THREAD

**Issue by Triden** [mgp25/Instagram-API#1270]
Hi, there used to be a class called AdaptImage, but then decided to abandon it. I have finalized it and it works without failures. Gently adding white margins to a format of 0.8 / 1.9 It is based of course on imagecopyresampled. You do not like this, I know mgr25.) But in practice, the images look great. I can rewrite the imagick library. Do you need this module here? I can upload.

**Comment by mgp25** [comment]
Send a PR so everyone can review it and discuss wether we merge it or not?

Regards

**Comment by SteveJobzniak** [comment]
@Triden We can check it. But are you aware that we have `src/ImageAutoResizer.php`? It's the v2 version of AdaptImage. We already rewrote it. That is why the old AdaptImage is deleted.

And ImageAutoResizer does the critically important job we need: Auto-resize / auto-crop images to make them legal on Instagram. So that uploads succeed without "rejection" by the server.

Anything other than that, such as adding borders, would be an "extra" feature. And I don't think we'll merge something that's a poor clone of ImageAutoResizer, because that's a duplicate and confusing feature. And ImageAutoResizer is already perfectly written.

But sure we'll take a look if you make a pull request.

**Comment by SteveJobzniak** [comment]
Perhaps you weren't aware of ImageAutoResizer which handles the aspect ratio / size / cropping correction.

Anyway, we'll take a look at the AdaptImage code you make a pull request (or better yet, a gist.github.com). ;-) I just want to see the code before I make a final judgment but I am leaning towards decline, since it duplicates the already-perfect `ImageAutoResizer` functionality.

And adding borders to images is some "weird extra" that people should do in their own code if they really want that. It's not necessary in the core library. Especially since the official app doesn't add any borders to portrait/landscape images, which would make our API images stand out negatively. The official app just uploads the images in their normal aspect ratio, with auto-cropping of too-wide/too-tall aspect ratios, and with some optional square cropping for people who want that. There's no "add white borders" option anywhere.

At absolute most, we may (but probably not) add a "make a square and fill with color X" option to ImageAutoResizer, but again it's not something the real app does and it's kind of stupid to add a bunch of blank "colored" borders around an image on Instagram. ;-)

**Comment by Triden** [comment]
@SteveJobzniak 
Yes I agree. Perhaps adding white borders is not good. It takes a lot of time to process photos, so I'd like to finish the library so that photos of any format can be downloaded without error. Ideally, provide choices, add white margins, or crop. But the quality of my code is lower. Since in fact I did only for myself.

**Comment by SteveJobzniak** [comment]
@Triden

Using ImageAutoResizer is very easy:

```php
$resized = new \InstagramAPI\ImageAutoResizer($photo_filename);
$ig->uploadTimelinePhoto($resized->getFile(), ['caption' => $captionText]);
```

It auto-processes. If the image is already a legal size and aspect ratio, it instantly returns the original file and doesn't waste any time processing the image. If the image is illegal, it processes it and then auto-deletes the tempfile after the object is destroyed. Very easy to use and only processes when necessary.

This makes all images valid and uploadable without error. Adding borders to this code would not be an improvement, so I think we won't do that.

Anyway, enjoy :)

**Comment by Triden** [comment]
@SteveJobzniak. Thank you. I'll take note. Also, I noticed that the text with the symbol №. is not published. If there is a possibility, you can add text verification to the util::. Add constraints to the 2200 characters and str_replace ('№.', 'N', $ this-> attachments ['comments']) .

**Comment by SteveJobzniak** [comment]
@Triden Thanks for the info. That's weird. I don't think they block specifically №. It could be a problem with your encoding. All text must be sent to them as UTF-8. If they do block №, then they definitely also block other characters (perhaps certain ranges of Unicode). So we won't add any specific overrides like you mentioned, but we'll add the warning to the wiki.

But please first try posting the character as proper UTF-8. For example, if you are using a Russian codepage on your site/whatever, and sending № encoded as CP-1251 (cyrillic), then it will not work at all. You must send as UTF-8 string to Instagram. So I think this is actually the problem. Because Instagram allows any language. Even arabic ^_^ So I don't think they block this character for you.

**Comment by Triden** [comment]
@SteveJobzniak I use utf-8.) You can test.)
