### ISSUE TITLE
stable request proxy

### ISSUE THREAD

**Issue by Triden** [mgp25/Instagram-API#1272]
I apologize, I wanted to ask. Proxy often does not work consistently, so requests periodically fall. In the old version to improve stability I added after the request
$Resp = curl_exec ($ch);
         $Cont = 0;
         While ($cont <= 3 && !$Resp) {
             Sleep(2);
             $Resp = curl_exec ($ch);
             ++$Cont;
         }

Now, guzzl immediately gives an exception. The only solution I could think of was:
While ($i) {
   Try {
     $Response = $this ->_ guzzleClient->request ($method, $uri, $guzzleOptions);
   } Catch {
     $i;
      ...
    }
}

Who faced the similar? How can this issue of stability be resolved more beautifully?

**Comment by SteveJobzniak** [comment]
The correct answer is that **you** need to do what you would do in **any other project which uses exceptions**: Handle the exception and do your retries around that fact. ;-)

Here's a helper function I use, to avoid repeating my retry-loop code everywhere that I need to do retries. I do my own retry status echoing from this function too, but you can adapt it any way you want:

```php
    /**
     * Function call retry handler.
     *
     * Simplifies the task of retrying function calls (such as Instagram API
     * calls), since their servers are unstable and often have SSL read errors.
     *
     * @param callable $fnCall fn(&$self) Function to call. Must return the
     * value that you want us to return if the function ran successfully. It
     * will be provided with a reference to the class instance.
     * @param int $maxAttempts How many times to try the call until success or
     * giving up.
     * @param string $errorStrPrefix Prefix to echo before exception message.
     *
     * @throws \Exception Final exception if all attempts failed.
     *
     * @return mixed Whatever the function returned, if it was successful.
     */
    protected function _retryFnCallBeforeThrow(
        callable $fnCall,
        int $maxAttempts = 4,
        string $errorStrPrefix = '[ALERT: ERROR]' )
    {
        $retVal = NULL;
        for( $currentAttempt = 1; $currentAttempt <= $maxAttempts; ++$currentAttempt ) {
            try { // Catch call errors.
                $retVal = $fnCall( $this );
                break; // No need for further attempts if the call succeeded.
            } catch( \Exception $e ) {
                // Something went wrong, show error...
                echo "{$errorStrPrefix} {$e->getMessage()}\n";
                if( $currentAttempt < $maxAttempts ) {
                    // We aren't yet on the final attempt...
                    $attemptsLeft = ( $maxAttempts - $currentAttempt );
                    if( $attemptsLeft > 1 ) {
                        echo "[INFO] Retrying ({$attemptsLeft} attempts left)...\n";
                    } else {
                        echo "[INFO] Retrying (last attempt)...\n";
                    }
                } else {
                    // We've failed the last attempt, so re-throw the error to
                    // let our caller handle it.
                    throw $e;
                }
            }
        }

        return $retVal;
    }
```

Note that the function gets called with a reference to `$this` (the parent object), which is why every function must have `function( &$self )` as their parameters, to be able to access "$this" (which must be done via the name "$self" since "$this" is not inherited inside anonymous functions as of PHP7+).

And here is how I use the function:

```php
    // Fetch the current timeline page.
    $userFeed = $this->_retryFnCallBeforeThrow( function( &$self )
        use ( $f_userPk, $currentPageNum, $currentPageId, $estimatedTimelinePages )
        {
            Utils::humanizedPause();
            echo "[PROGRESS] Requesting timeline page #{$currentPageNum} ({$currentPageId}) of ~{$estimatedTimelinePages} pages (estimated)...\n";
            return $self->_igAPI->getUserFeed( $f_userPk, $currentPageId );
        }, self::API_DEFAULT_RETRIES, '[ALERT: USERFEED API ERROR]' );
```

This helper calls my function and does automatic retries. If all retries fail, the final exception is thrown to the place that called `_retryFnCallBeforeThrow`. However, if the call _succeeded_, the result of the call is in the `$userFeed` variable above (because you can see that I return the API response call value from the anonymous function).

One more thing to note: You must use `use()` to "import" variables into the scope of the anonymous function. You can see me doing that above.

Lastly, you must implement sleep() in the above, as you mentioned. It needs to be inside of the function call so that there's a sleep before every retry. I would put the `sleep()` above the "echo [PROGRESS] Requesting timeline page..." line, to avoid hammering their API. And that is basically what my `Utils::humanizedPause();` does. It's a special sleep algorithm which I won't share.
