### ISSUE TITLE
Publication low reach

### ISSUE THREAD

**Issue by randinfo** [mgp25/Instagram-API#1274]
Hello and greet job for this.
I got a little question for you users.

I've tested the application with 2 same posts with image and a description with the same hastags. And i got a highier reach with the offical application. 
I've posted the first one (with this api) 5 minutes before the second one.
I got 0 likes on the first and 59 likes on the second (almost instantly).

That's why i'm asking if you got the same feeling or no ?

Thanks in advance

**Comment by mgp25** [comment]
This is a known issue. you can read more information in closed issues and FAQ. Hashtags doesnt work at the moment

Regards

**Comment by SteveJobzniak** [comment]
Writing hashtags in caption doesn't work. It's a known issue. Instagram doesn't publish your photo to those hashtags, so people looking at those hashtags will not see your photo. It's probably some antispam thing they do. We don't know what they're doing, and even if we research we may perhaps not publish the solution, because spammers would abuse it by flooding crap on every hashtag.

**Comment by randinfo** [comment]
Hi, i understant your point of view. But not every one is a spammer. I'm using this library for ly personnal use. For my facebook page and instagram. I've made a personnal scheduler that i'm using alone.

**Comment by SteveJobzniak** [comment]
@randinfo That's good. We make this library for people who want to create fun, personal toy projects. Unfortunately lots of spammers use it too. :( The only thing we can do against that is to not add functions that spammers will abuse. So some things have to be avoided, sadly. Spammers ruin it for everyone else. :(

**Comment by randinfo** [comment]
Thanks you too. That's realy disapointing :/
