### ISSUE TITLE
Possible Bug - Upload Album

### ISSUE THREAD

**Issue by rudemex** [mgp25/Instagram-API#1285]
Hi, 

I was testing the new modifications, and when I tried to upload the album, I returned this error
`[27-May-2017 20:54:17 Europe/Berlin] PHP Fatal error:  Class 'InstagramAPI\Request\Utils' not found in /Users/mex/Sitios/arduino/ArduinoProjects/ws-woonkybot/development/deploy/vendor/mgp25/instagram-php/src/Request/Timeline.php on line 112`

But solve it by adding `use InstagramAPI\Utils;` in the file Timeline.php line 6.

Now upload album photo!

;)

pd: sorry, my english is very very very bad! jajaja

**Comment by SteveJobzniak** [comment]
https://github.com/mgp25/Instagram-API/commit/82c6110fb46764df936342b4e97ce1e1e17fe4bf

Hi! Thanks a lot for letting me know. I thought I remembered everything but I forgot the "use" declarations when moving the functions. :)

Since you've tested the new modifications, how does it feel so far? It was a test because Instagram.php was just so big and messy. And `$ig->timeline->uploadAlbum()` solves that. It's meant to let us group related functions and to make it easier for users to find the functions they need.

**Comment by rudemex** [comment]
@SteveJobzniak Hi, you're welcome. I've been testing it, and it's far better than before. However I keep on working on the ffmpeg and ffprobe issue.  I'll get back to you with any news. Thanks!

**Comment by SteveJobzniak** [comment]
@rudemex Wow, thanks for that feedback. I am happy to hear you think it's far better than before. :))

And about the ffmpeg issue, the thing I wrote in the last post (https://github.com/mgp25/Instagram-API/issues/1267) should work, but there's a problem with spaces in the path. When I wake up I will fix it just for you. I think I know an easy fix.
