### ISSUE TITLE
How To Get ALL Usermadia

### ISSUE THREAD

**Issue by Mohammad-Reza-Rahimi-Zade** [mgp25/Instagram-API#1303]
hi

How To Get ALL Media By  username or userid  ???

**Comment by mgp25** [comment]
Parse the response or use feed functions:

https://github.com/mgp25/Instagram-API/blob/master/src/Request/Timeline.php

Read code and documentation before opening any issue. Everything is explained in the code

Regards

**Comment by gerchicov-bp** [comment]
@mgp25 is it the only way to use `getUserFeed` and `getSelfUserFeed`? They return **18** items per one request only and it takes a lot of time to get all the data.
The reason is I want to calculate something like statistics from this app:
https://itunes.apple.com/us/app/followers-for-instagram-follow-unfollow-tracker/id597077652?l=es&mt=8
Maybe could you suggest me a proper way?

**Comment by SteveJobzniak** [comment]
@gerchicov-bp If you only care about how many timeline posts, followers and followings a user has, then you just have to use `People::getInfoById()` which has those numbers in it, like `18 posts, 123 followers, 28 followings`.

If you want the actual media IDs / details then yes you must read the whole timeline page by page.
