### ISSUE TITLE
Some small problems with the Direct collection

### ISSUE THREAD

**Issue by SteveJobzniak** [mgp25/Instagram-API#1309]
@valga Since you wrote the code and know it best, I'm tagging you here.

I've noticed three possible areas of improvement in the Direct class:

1. `sendDisappearingPhoto` and `sendDisappearingVideo` take an externalMetadata parameter and have the typical "see Internal::configureSingleX..." comment, leading the user to the code where they can read what metadata parameters can be used. But those sendDisappearingPhoto/Video commits didn't change the metadata handling/comments in the configure-functions, so there's no actual information about what metadata can be sent for disappearing photos/videos. So either A) remove "externalMetadata" from sendDisappearingX funcs if there is no metadata available for those, or B) ensure that the Internal::configureSingleX code comments about externalMetadata (inside the func, near the top) also are correct for "disappearing direct media".
2. `sendDisappearingVideo` uses $externalMetadata + $maxAttempts. `sendVideo` uses $options for max_attempts. Is it possible to settle on one parameter format?
3. The new `sendDisappearingVideo` and `sendDisappearingPhoto` uses the correct design: `internal->uploadSinglePhoto/Video`, with a param for target feed. That was the intended design, where our "Internal" class contains a generic upload-algorithm re-used by all of our other request collections, and with just very small differences based on target feed. So that's great! The problem is `sendVideo` which is basically a copy-paste of `uploadSingleVideo` with 1-2 small changes, and which then calls the internal "sendDirectItem('video')" which does the configure. A better design would be that `sendVideo` calls `internal->uploadSingleVideo('direct_v2', ...)` which does the upload + configure for direct_v2 feeds. With no code duplication. Yes, it's good that our request-collections should contain their own self-related code. But re-usable upload code like this went in Internal so that we don't have to replicate the upload algorithms everywhere. So don't be afraid of using Internal for some of the direct-related upload algorithms.

Hmm... ;-)

**Comment by valga** [comment]
1. I must say that it is hard to verify what metadata can be used for disappearing media. When I start recording it, Instagram app asks for location access. So it _may_ use the same metadata as ordinal stories. I will try to verify that, but I can't guarantee anything on that.
2. Hmm, `sendDisappearingVideo()` is basically `Story::uploadVideo()` plus Direct recipients. So it uses the same parameters format. And `sendVideo()` is pure Direct method, so it uses the same convention as other non-upload methods from Direct requests collection.
3. I already told you that video upload needs to be refactored. But we certainly can't use `uploadSingleVideo()` for `sendVideo()` because they have only one thing in common: the video upload. Configure requests and responses are totally different. Also, `sendVideo()` doesn't upload thumbnail. Also, take a look at `Timeline::uploadAlbum()` method. It also has a lot of copy-paste from `uploadSingleVideo()`, so we should refactor it too. But, as I already said, I won't touch video uploads until they finish their experiment with new upload method.

**Comment by SteveJobzniak** [comment]
Hi valga!

1. Okay excellent. Probably the easiest way to research what metadata is possible is to use the app to send disappearing photo/video with all data filled in, and checking what API query the app makes. That will show what JSON metadata the real app sends.
2. Yeah, I guess it makes sense. You can leave it the way it is.
3. Ah so this was what you meant about refactoring uploads. I see. Yeah the current system has grown via constant extensions over the years whenever instagram added features. Well. At least the code works, so we can keep it the way it is. But if you ever refactor it that would be totally awesome.

Okay in other news: I have shut down and packed down my laptop today. Now I am putting full focus on my health treatment. I will not be able to be on github or working on the project anymore. You can srill reach mgp25. :)

I really appreciate your brilliant intelligence and everything you have brought to the team. We really made a kickass library, hehe. :)

I wish you all the best. Maybe we'll meet again, but I will be gone a long time now to deal with my health. Take care mate!
