### ISSUE TITLE
Can i get my stories seen people list? 

### ISSUE THREAD

**Issue by techinpark** [mgp25/Instagram-API#1325]
![image](https://user-images.githubusercontent.com/1935442/27066411-e5eac948-503e-11e7-8065-de846daf62b9.png)

have a idea?

**Comment by aitte2** [comment]
Have you tried all story functions?

https://github.com/mgp25/Instagram-API/blob/master/src/Request/Story.php

Maybe if you request your own story it maybe includes the viewer list in that API response since you own the story. Try it with var_dump on the response and look if the list of viewers is in there somewhere?

If not then it's a missing API. xD

**Comment by mgp25** [comment]
Yes, probably requesting media info or similar. I haven't tried, but you can test and post your own experience here

Regards

**Comment by SteveJobzniak** [comment]
@techinpark This is now possible in the latest `dev-master`:

```php
$ig->story->getStoryItemViewers()
```
