### ISSUE TITLE
Problem with shared medias

### ISSUE THREAD

**Issue by krakoji** [mgp25/Instagram-API#1334]
There is a problem with shared medias, I see that instagram returns this item as "placeholder" type, but InstagramAPI\Response\Model\ThreadItem returns empty message (no links to shared media)

**Comment by mgp25** [comment]
@krakoji you need to be more specific. Steps to reproduce it and so, if not this issue will be considered as invalid

**Comment by SteveJobzniak** [comment]
@krakoji You are probably using v2.0 of this library which had an old `$ig->directShare()` function which was very broken.

If you upgrade to `dev-master` (see README) you will get the nearly finished v3.0 of the library. It has a full Direct implementation, which should have perfect media sharing. Just use `$ig->direct->sendPost()` to share a post.

Upgrading will require you to rewrite most of your function calls. Because everything has changed and been grouped. It's worth it though. The library is finally fully organized and people are loving it. :)
