### ISSUE TITLE
View image from getVisualThread function.

### ISSUE THREAD

**Issue by matthijsotterloo** [mgp25/Instagram-API#1348]
When using `$ig->getVisualThread($thread_id)` where `$thread_id` is the id of the thread we're requesting, one of the fields in the response contains the image sent, but when I try to view this image I'm getting a 403. Is there any way to view this image? @valga probably knows this.

**Comment by mgp25** [comment]
Post the url

**Comment by matthijsotterloo** [comment]
The image url: `https:\/\/scontent-frt3-2.cdninstagram.com\/v\/t69.10827-15\/e15\/p640x640\/19282879_840658302753301_5891668422474858496_n.jpg?oh=71b821a8c15c4a07e4d43c18472d1431&oe=594B8537`

**Comment by mgp25** [comment]
@matthijsotterloo was this a vanishing image?

**Comment by SteveJobzniak** [comment]
Matthijs, how old are you? This URL you gave us has escaping: `\/` instead of `/`.

When fixed to regular slashes, your URL works: `https://scontent-frt3-2.cdninstagram.com/v/t69.10827-15/e15/p640x640/19282879_840658302753301_5891668422474858496_n.jpg?oh=71b821a8c15c4a07e4d43c18472d1431&oe=594B8537`

Also, be aware that the oh and oe tokens are necessary to access this protected image.

**Comment by matthijsotterloo** [comment]
Oh shit, sometimes these fixes are so easy haha.
I'm sorry guys!

**Comment by SteveJobzniak** [comment]
:)
