### ISSUE TITLE
checkpoint_required bypassing.

### ISSUE THREAD

**Issue by matthijsotterloo** [mgp25/Instagram-API#1361]
Lately I've been getting a lot of `checkpoint_required` errors on the login.
I know this is because of Instagram wanting to verify it's you logging in on the account, is there a way to get rid of this error on the API side without having to open the app to say it's me? 

Or is there something I'm doing wrong?

**Comment by mgp25** [comment]
That usually happens when:

1) Login from a different IP (Location). If you are lets say in Spain, and suddenly it connects to a Russian IP. Its weird, you know. Thats why it asks you for verification.

2) Lots of requests, marking your account as suspicious.

We are not going to implement checkpoint in the API, so, yes you need to open the app or go to instagram website to verify yourself.

Detailed information, can be found in the F.A.Q.: https://github.com/mgp25/Instagram-API/wiki/FAQ#what-does-checkpoint_required-error-mean


Regards

**Comment by matthijsotterloo** [comment]
Would it get merged if I make a pull request for this?

**Comment by mgp25** [comment]
@matthijsotterloo nope. This was already implemented in the API before, we removed it because many people are using this API with spam purposes, so we try avoid this kind of scripts that makes easier life for script kiddies spammers. I know its a shame, but society is messed up.

Have a good week.

Regards
