### ISSUE TITLE
Getting locked out for spam, but it's the VERY first action.

### ISSUE THREAD

**Issue by GarlandM** [mgp25/Instagram-API#1422]
Hi,

It seems that I'm getting the dreaded "Sorry, this feature isn't available right now" issue. 

However, I can assure you, I am not spamming. This happens almost immediately, upon my second or third like, the account will be like blocked via this API.

However, I'm still able to manually like via an actual device, such as my galaxy or iPhone.

Thoughts?

**Comment by mgp25** [comment]
@GarlandM If you are not spamming, you are using a flagged connection then, like a proxy or similar.

Not API issue, dont use flagged networks

Regards

**Comment by GarlandM** [comment]
@mgp25 

I can 100% guarantee you this is NOT a flagged proxy or connection. As stated in my original message, if I use the same account over wifi (thus the same external IP) as testing this script locally (again, same external IP) it works fine.

It's only when I use this script with the account is it blocked.

**Comment by valga** [comment]
@mgp25 apart from some new params to like requests, Instagram API has a new feature: some params can get out from signed body to POST data.

**Comment by mgp25** [comment]
@valga but only in rare ocassions, otherwise its vulnerable to be modified in a mitm. Can you point which ones so i can double check them?

**Comment by valga** [comment]
@mgp25 I checked it more thoroughly and found that it is actually an old feature: they have been using it to skip files from signed bodies. And there are only 3 such params:
1) `profile_pic` file at account creation;
2) `profile_pic` file at account modification;
3) `d` flag at like/unlike.

So you don't have to check anything. As for issue, it seems that Instagram fights with spam and blocks accounts with invalid request params.

**Comment by mgp25** [comment]
@GarlandM post debug log

@valga yup, they use an AI to determine if a user is legit or not, and not sending some params could lead to an account block.

**Comment by SteveJobzniak** [comment]
@valga Will we need to emulate unsigned POST?

**Comment by valga** [comment]
@SteveJobzniak, see recent PR.

@mgp25, I didn't fix params in like methods, I just added the ability to send params in a different way. But it seems that we have kind of broken params, and fixing them could lead to spam, so it's up to you to decide.

**Comment by SteveJobzniak** [comment]
The pull request is now slightly tweaked and merged.

As for whether to fix the functions... hmm... Liking is pretty innocent. "X liked your photo" is gonna happen thousands of times anyway even without spammers alive, so anyone using Instagram usually turns off notifications about photo-likes.

Spam is more dangerous with things like the ability to post photos to hashtag feeds (which can let them be filled with spam), which is not supported in this private API.

So I vote for allowing like() and unlike(). It's very innocent and doesn't really cause a nuisance to people, since everyone turns off like-notifications (or makes their profile private if they truly want privacy).
