### ISSUE TITLE
Hashtag search / shadowban issue

### ISSUE THREAD

**Issue by generictitle** [mgp25/Instagram-API#1425]
Hi Guys,

Over the last few weeks I've invested significant effort into trying to fix the issue with images not showing on hashtag searches. Though I have not been successful, I just wanted to leave a record of all the things I've tried, so that when someone else picks this up they aren't starting from scratch.

My work focused on two areas: 

- Ensuring all of the requests were identical to the ones that Instagram was making

- Adding the graph.instagram.com analytics packets that are sent with every action

The attached file "allRequests.txt" (files are listed at the bottom) is a record of all the communications between an iPhone and i.instagram.com after the initial login. 

I have modified every single request that happens to ensure headers and body are identical and happen in the same order as in this file, but the post remains shadowbanned. I am unable to sniff the traffic for Android, so it's entirely possible that there's some differences for Android which could be spotted by Instagram.. but I'd be pretty surprised if it turned out they were checking the useragent and then verifying the packets differently. It's possible I guess...

If anyone would like to try sniffing the iPhone packets and testing themselves, just download Charles from here: https://www.charlesproxy.com/ and then set up the SSL certificates + proxy on your phone as described here https://www.charlesproxy.com/documentation/using-charles/ssl-certificates/

I also spent a significant time getting the graph.instagram.com analytics packets that are sent by the app when any action is performed. In the file "graphData.txt" i'm attaching an example packet that is sent after the "configure" endpoint is called. Here is a handy page for understanding how the message payload is created (and therefore how to extract it) https://stackoverflow.com/questions/41509066/reverse-engineer-http-request

I've already done this for one of my packets, and from the message json data I have filtered the analytics data which are of interest to us for the image upload and attached it in the file "analyticsJsonData.txt"

As you can see the waterfall_id becomes relevant here, which is something that appeared in the i.instagram.com image upload body for the /media/configure action and didn't seem to have any meaning or use (the configure would still succeed without it). I ensured that the same waterfall_id uuid is used in my analytics upload as my configure action, recreated all of these packets... and the image is still being shadowbanned / invisible to hashtag searches.

At this point I've given up on this - this problem has been the bane of my life for the last few weeks. Hopefully someone can build on what I've done and find the solution - I feel like I may have been close, but as you'll find with this problem you could by months away or minutes away from the solution and you just have no idea. Very frustrating!

Cheers

[allRequests.txt](https://github.com/mgp25/Instagram-API/files/1164060/allRequests.txt)
[graphData.txt](https://github.com/mgp25/Instagram-API/files/1164052/graphData.txt)
[analyticsJsonData.txt](https://github.com/mgp25/Instagram-API/files/1164055/analyticsJsonData.txt)

**Comment by mgp25** [comment]
Thanks for your effort, but just because you were using iphone, all this is invalid. Although android and iphone are similar, it doesnt mean they are equal in all aspects. We are using android.

Dont worry, this will be added eventually since we know what the going on. When i have some spare time i will do it.

Regards

**Comment by SteveJobzniak** [comment]
@mgp25 Instagram is doing deep efforts to stop private API-posted media from being shown on hashtag feeds, to avoid spammers filling all hashtags with crap. So I wouldn't say that we will "definitely" succeed with getting media into their official hashtag feeds, and maybe we shouldn't even do it. It's gonna increase spam by a lot and would probably cause Instagram to finally _totally_ ban usage of the private API. Right now they tolerate it because they've got good protections that are working so far. Like this anti-hashtag spam situation which is currently working as Instagram wants it to work, which is to have only real posts on hashtag feeds.

**Comment by SteveJobzniak** [comment]
@mgp25 Instagram is doing deep efforts to stop private API-posted media from being shown on hashtag feeds, to avoid spammers filling all hashtags with crap. So I wouldn't say that we will "definitely" succeed with getting media into their official hashtag feeds, and maybe we _shouldn't_ even do it. It's gonna increase spam by a lot and would maybe even cause Instagram to finally _totally_ ban usage of this private API library and all other libraries.

We know they can detect this library but that they tolerate it. And right now they tolerate it _because_ they've got good protections that are working so far. Like this anti-hashtagspam situation which is currently working as Instagram wants it to work, which means that they currently have only real app posts on hashtag feeds, and very little spam. That's good... It means you can type "#nature" on Instagram and see nature posts instead of 1000s of viagra spam. ;D

If that situation changes and Instagram's quality starts to hurt, I am sure it's the end of this API.

**Comment by mgp25** [comment]
@SteveJobzniak yup, thats what i always say xD eventaully can be in like 100 years. I know the threats of doing this, if i ever achieve it, i probably wont share it, not because i dont want, but because of people misusing the API.

**Comment by SteveJobzniak** [comment]
@mgp25 Haha okay. xD Yeah, the risks are too great if this is implemented.

**Comment by generictitle** [comment]
Yeah I get it, just a shame for the rest of us that just want to make reasonable scheduling solutions! Gramblr has a working solution to this with their windows app. I know it's not an open API, but it's worth noting.

Also in regards to the results being less useful due to being iOS, that's a bit of a shame. Do note that the analyticsJsonData.txt dump I made was actually extracted from Android data, so may be relevant.

Thanks for the reply, appreciate you guys taking the time to respond

**Comment by SteveJobzniak** [comment]
@generictitle I know, it's a big shame that spammers ruin it for everyone, and we regret having to make these kinds of decisions. :-( Basically the rule of the internet is: Anything that can be used for spam _will_ be used for spam. So we have to avoid giving spammers tools.

**Comment by graphiclife** [comment]
After running several searches on the same hashtag my account seems to have been affected by a kind of ban, limiting the search results to my own posts only  (both in app and api, another account can see more posts with the same hashtag). It's just like being in sandbox mode in the official api. Frustrating :) Any idea to get around it?
