### ISSUE TITLE
How to get url from items

### ISSUE THREAD

**Issue by vallez01** [mgp25/Instagram-API#1428]
hallo 
how to get items data url video_versions ?
i use this code. but getting null

`$feed = $ig->story->getUserStoryFeed($userID);

 foreach ($feed->getItems() as $item) {
            
            $videoVersions = $item->getVideoVersions();
     foreach ($videoVersions as $version) {
     
     echo $version->getUrl;
     
            }
        }

`

**Comment by solomax2014** [comment]
```php
foreach ($feed->getReel()->getItems() as $item) {
    $media_type = $item->getMediaType();
    if ($media_type == 1) {
        // Photo
        $url = $item->getImageVersions2()->getCandidates()[0]->getUrl();
    } elseif ($media_type == 2) {
        // Video
        $url = $item->getVideoVersions()[0]->getUrl();
    }
}
```
[0] - First element in array, that has the best resolution.
For future, use var_dump to see, what you have inside variables.

**Comment by SteveJobzniak** [comment]
@solomax2014 Thanks for helping answer these questions! 👍 In general your code should be safe for a long time, but perhaps those media type numbers will change in the future. Right now they are 1 and 2 but Instagram can change it. That's why we have constants `\InstagramAPI\Response\Model\Item::PHOTO`, etc.

Look here: https://github.com/mgp25/Instagram-API/blob/master/src/Response/Model/Item.php#L322

(This line offset may be wrong in the future but it's pointing at the the "const" area). There are constants for PHOTO, VIDEO and ALBUM right now.

And people can look at `Timeline::backup()` for code that shows how to handle albums, photos and videos in timeline feeds: https://github.com/mgp25/Instagram-API/blob/master/src/Request/Timeline.php#L381

That's also how you'd wanna use those constants in your own code. It's safer than relying on numbers that may be changed by Instagram.

Anyway just thought I'd add this info. Thanks for helping out, max!
