### ISSUE TITLE
How to get meter readings for new events?

### ISSUE THREAD

**Issue by alexandrKulik** [mgp25/Instagram-API#1443]
In people.php there is a method getRecentActivityInbox () which shows the events for the account new and old, but when it shows them they become marked. How to get the values of counters for new events that they would not be marked with

**Comment by SteveJobzniak** [comment]
???

**Comment by alexandrKulik** [comment]
I'm writing through an interpreter, so I apologize if it's not clear.
There is a method getRecentActivityInbox () which shows all the new events for the account who put the class, subscribed, comment. When asked for it, the event tag is read, how to find out that there are new events, but that they would not be read, as in the application notifies that there are new events associated with your
Here is a screen, how to find out the data of this counter?
http://SSMaker.ru/ea3791a7/

**Comment by SteveJobzniak** [comment]
@alexandrKulik 

If I understand correctly, this is what you're saying:

- The app shows an activity counter number, like "2", on the Heart icon.
- When you use `getRecentActivityInbox()`, they become marked as "seen" and the "2" on the Heart icon in the app disappears?
- You want a way to get the "2" number, without triggering `getRecentActivityInbox()`, so that your app icon is still "2"?

Unfortunately we can't do that. Because Instagram is the one deciding that `getRecentActivityInbox()` call will "remove the 2"...

And our `login()` will always trigger `getRecentActivityInbox()`:

https://github.com/mgp25/Instagram-API/blob/d6de474d94a634165b537e485f145d86470be8fc/src/Instagram.php#L609

https://github.com/mgp25/Instagram-API/blob/d6de474d94a634165b537e485f145d86470be8fc/src/Instagram.php#L642

So even if we have a function to "just read the number 2" and don't call `getRecentActivityInbox()`, you would _still_ be calling it every time you `login()` and "refresh the login session" happens.

And as for how the app gets the number 2? I don't know but I am guessing the official app calls the endpoint and just caches the "2 events are waiting for you..." info locally, or perhaps it gets that info in another endpoint. But it doesn't matter because we call `getRecentActivityInbox()` on most `login()` calls... so there's nothing you can do to stop it from removing the "2" on the heart...

I hope this answer is clear (after you translate it with Yandex xD).
