### ISSUE TITLE
Login / challenge required 

### ISSUE THREAD

**Issue by MMrR0b0TT** [mgp25/Instagram-API#1458]
Is there any update that is impacting everyone in the challenge required since yesterday morning? We're dealing with it in here and Instagram arent accepting our confirmation even though using the website or app to confirm.

**Comment by mgp25** [comment]
There is no update, and probably is due the usage of proxy that have different locations. I have done some tests and everything is working fine.

Regards

**Comment by GarlandM** [comment]
Are you sure @mgp25 ?

Myself, and three others are having issues with this too. No proxy usage, testing it on my local machine. Accounts work fine via my IP on Mobile & Web, but using the Instagram-API, accounts will fail to verify.

**Comment by mgp25** [comment]
@GarlandM send me data of the account via email and i'll verify it

Regards

**Comment by nft2** [comment]
I'm also having this issue, since around Friday night EST, solving checkpoint challenges have no effect. This isn't an issue with the code here but it is an issue.

**Comment by mgp25** [comment]
Send account data to my email then

**Comment by GarlandM** [comment]
Sorry, by account data, would you like me to send the login details?

**Comment by MMrR0b0TT** [comment]
@mgp25 I sent to you yesterday an email

**Comment by WoLpH** [comment]
I can confirm as well, the "it was me" button doesn't solve the issue anymore. The ip address remains blocked. Preliminary results indicate it might be fixable using two factor

**Comment by nft2** [comment]
@WoLpH Thats interesting, can you elaborate on the two-factor fix?

**Comment by WoLpH** [comment]
I've had some success with enabling two factor authentication for the accounts. It didn't work in all cases though so it's not enough

**Comment by iwritecodetoo** [comment]
I can confirm as well that too many challenges are happening since this weekend. A single account can login most of the time, but if you try to login around 5 or 6 accounts, even with minutes between them, then all accounts get a challenge from that point on, and doesn't seem to go away. Connecting the same account through the app works fine.

I noticed this problem seem to happen only during new logins, not resuming existing sessions or doing anything else. This thread should be reopened.

**Comment by robwatkiss** [comment]
I too have seen a marked increase in the number challenges required and with them not clearing once confirmed in the app.

The challenge response is currently:
`{"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/#########/XXXXXXXXXX/", "api_path": "/challenge/#########/XXXXXXXXXX/", "hide_webview_header": false, "lock": true, "logout": false, "native_flow": true}, "status": "fail", "error_type": "checkpoint_challenge_required"}`

As opposed to previous challenge responses of the form:
`{"message": "checkpoint_required", "checkpoint_url": "https://i.instagram.com/challenge/########/XXXXXXXXXX/", "lock": true, "status": "fail", "error_type": "checkpoint_challenge_required"}`

Note the addition of the `native_flow` node.

**Comment by michelmelo** [comment]
I'm also having this problem, I can not log in.

**Comment by aitte2** [comment]
I have 3 accounts, and ai use all 3 on 2 different server IPs and from the app. I never spam.

I do not get any challenge/checkpoint required.

I think you guys are all spammers being caught by Instagram's constantly improving antispam.

**Comment by nft2** [comment]
Actually @aitte2 its because IG fixed what appears to have been an error on their end Monday morning. Appreciate your expert deduction that we are all spammers and botters though.

**Comment by iwritecodetoo** [comment]
@nft2 Agreed. Since Monday suddenly the problem stopped.

**Comment by aitte2** [comment]
That's good to hear. ;)

**Comment by iwritecodetoo** [comment]
@aitte2 You know, most of us are really grateful for the hard work all you guys put into this library, But you have this fake moral high ground and this attitude that really hurt the project.

You all have fake names, no personal info on your profiles. You hack into a private API against the company wishes and provide a way for people to automate actions that are not meant to be automated. You provide paid support and even a premium license for websites and apps. What do you think these people are doing? Running 3 personal accounts on their home server? Bullshit.

You can say here it's all personal just to maintain appearances. You can believe all you want, but the ONLY purpose of this project is to create bots in some way. Whether you believe your personal use of these bots is fair or not is not important. You're the same kind of user as everyone else here. Just stop calling everyone "bot and spammer" if you don't know what we're doing. This is bullshit!

Many of us would pay you good money to support this project if we saw a better attitude coming from the maintainers.

**Comment by WoLpH** [comment]
No fake accounts here, simply a lazy it guy that doesn't want to click manually if it can be automated

At one point I even automated birthday wishes ;)

**Comment by aitte2** [comment]
@iwritecodetoo I am just a contributor of a single pull requewt months ago, I don't work on this project. :P

**Comment by mgp25** [comment]
> Many of us would pay you good money to support this project if we saw a better attitude coming from the maintainers.

I work for free, i don't even use this API, it is just something i do when im bored. Back in the day when i was banned from using Instagram because reverse engineering WhatsApp, i started this API so i can upload my personal photos to my account. 

I do this for free but anyone can contribute by donating if they like the project or just saying thanks it is always appreciated.

> You can say here it's all personal just to maintain appearances. You can believe all you want, but the ONLY purpose of this project is to create bots in some way. Whether you believe your personal use of these bots is fair or not is not important. You're the same kind of user as everyone else here. Just stop calling everyone "bot and spammer" if you don't know what we're doing. This is bullshit!

The purpose of this project was what i told above, just a tool for myself to upload photos. Eventually it become a bigger project but NEVER was intended to do bots for spamming purposes. Thats why i stopped giving support to WhatsApp API (Chat API) and eventually if this happens in this project i will stop too. Of course you can do bots, it's fun to create automated stuff, i also do it, but not with spam or commercial purposes.

People who are not spammers but have come with great commercial sites, since they didn't put any reference or credit to this API, license was changed so people can contributte to this project and create more open source project. Or contribute by purchasing a subscription so they can use the software without puting any reference or credit about the API. So both options are helping the API.

---

I have to deal with a lot of issues (most of them duplicate ones), hundreds of mails daily and most of them are spammers, so we tend sometimes to say that X is being using for spamming. We aren't always right, so forgive us when we make any mistake.

So just that.

**Comment by aitte2** [comment]
@mgp25 very well said!

**Comment by iwritecodetoo** [comment]
@WoLpH bots doesn't mean fake accounts or spam. It means automation. If you're lazy and using this library, you're automating, it's a bot. That's what I mean.

@mgp25 I work at a small company and we use your library mostly to extract data. We never spam, we don't sell services to spammers. Still, most of the time I have issues I come here and there is a closed issue, just like this one saying "everything is fine, you're doing something wrong". Most of the times there is either an issue with the library or with instagram, just like this one, but people still got accused for nothng. And I have seem multiple times pull requests fixing issues that have been closed for days or weeks after you said there were no issues. Sometimes the pull request is not linked, but we can see the code changes related to the issue later.

I understand you have no obligation to fix anything, but at least leave the issues open so we can find them and see if anyone finds a solution.

I was asked to see if we should pay a premium license to get a better support. But I'm really not sure if we'd get anything much different from here.

@aitte2 You're still a jerk for assuming the worst in people.

**Comment by aitte2** [comment]
@iwritecodetoo I am sorry. But have a look at the closed issues marked "not related":

https://github.com/mgp25/Instagram-API/issues?q=is%3Aissue+is%3Aclosed+label%3A%22Not+related%22

Most of them are duplicates and are misusing the library with wrong parameters or lacking basic PHP skills. The "you are doing something wrong" is the correct answer to most of those tickets.

Same with label "invalid":

https://github.com/mgp25/Instagram-API/issues?q=is%3Aissue+is%3Aclosed+label%3Ainvalid

Most of them are nonsense.

And same with "duplicate":

https://github.com/mgp25/Instagram-API/issues?q=is%3Aissue+is%3Aclosed+label%3Aduplicate

And that is just the tickets that are labeled. Most of the unlabeled ones are nonsense too. Almost everything that gets posted on this issue tracker is nonsense. User-errors, spammers, dumb messages like "it's broken!" (without any error logs or code), etc.

Have you thought that maybe it is very tiring for mgp to get nonsense tickets day in and day out, plus endless demands to add new endpoints for free? It becomes a full time job which is why I accept that he has the right to charge for premium license now so that this library "job" isn't a waste of his time. Especially since so many websites are making money via this library and paying nothing back.

From what I have read, a license gives premium personal email support and the latest app keys and the rights to use it in closed-source apps/sites.

Without a license we can still use this library's hard work commercially if we just open source our website/app code too (exactly like this library is open source, so that's fair)...

This library unfortunately gets abused by spammers. That is proven in the issue tracker. Requests for automated account registration, and people getting caught by Instagram antispam, is all over the issue tracker. So when things go wrong for one person but nobody else, it's easy to think it's just yet another abusive spammer getting caught again. A lot of ticket research time has clearly been wasted by the people who are spamming/abusing the API and posting "errors" that are really just Instagram's antispam... and those tickets waste everyone's time.

But maybe now that there's a way to financially support the development time so that it's no longer an unpaid job, perhaps it's time to stop calling out spammers publicly.

**Comment by Octolus** [comment]
Is there any solution for this? I was very happy to find this API, however my server is located in another country.

I am not sure how websites like storrito, instazood does it but they allow me to send email verification and enter the coded on their website.
