### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by WolfKOTTO** [mgp25/Instagram-API#1472]
I cannot log into my account anymore now, it always says quote, "Please wait a few minutes before you try again" it's been a day what should I do about it I done a lot of research :(

**Comment by solomax2014** [comment]
This message appears if you're doing requests too quickly. This happens even for logging in. So, try to wait a few minutes, as message says.

**Comment by WolfKOTTO** [comment]
I did that and it never seems to work so there's really no way of getting my account back

**Comment by WolfKOTTO** [comment]
I even tried reinstalling it and reloging in and it doesn't work nor does entering the phone number on the website doesn't work it just gives me a "Sorry, there was a problem. Please try again" This been happening for at least a day

**Comment by solomax2014** [comment]
You can use ```$debug = true;``` or ```$ig = new \InstagramAPI\Instagram(true);``` to see what error Instagram exactly gives.

**Comment by mexdelgado** [comment]
Did you install the dev-master? Have you enabled the two factor?

**Comment by mgp25** [comment]
@WolfKOTTO it seems your are abusing their systems. Wait a day until trying again, and don't make request too fast.

When opening an issue, try to give as much information as possible, for us it is very useful if you paste here your debug log because it is easy to detect where the problem is.

Your issue comes from the fact your are sending bulk requests which is considered as spam (abusing Instagram server). My recommendation is to wait until Instagram unflags you. Don't use this API for bulk request or spamming.

Keep in mind that all the issues you have openened has nothing to do with this API.

Regards

**Comment by Vasko17** [comment]
I had this problem and i fixed it.Just install vpn from play store and then try to sign in.I did it and it worked,now i can sign in and with my default vpn.Hope it works.Try Canadian vpn server.😀

**Comment by mxms23** [comment]
> I had this problem and i fixed it.Just install vpn from play store and then try to sign in.I did it and it worked,now i can sign in and with my default vpn.Hope it works.😀

Hey vasko17, i just made an account here just to thank you for your solution. I gave it a try and it worked instantly. You are a genius! Thank you a lot ! <3
