### ISSUE TITLE
Delete Instagram account

### ISSUE THREAD

**Issue by sajadabasi** [mgp25/Instagram-API#1476]
Is there any endpoint that could delete an Instagram account?
I searched but I couldn't find.
thank you.

**Comment by mgp25** [comment]
Hello @sajadabasi, according to [Instagram FAQ](https://www.facebook.com/help/instagram/139886812848894?helpref=related), you can not delete your account using device app, you need to delete account using Instagram in web browser.

That is why it is not implemented in the API, since this is based on the device app.

Regards
