### ISSUE TITLE
MediaAutoResizer Problem

### ISSUE THREAD

**Issue by historylife** [mgp25/Instagram-API#1503]
Hello all 

i add a replay to https://github.com/mgp25/Instagram-API/issues/1477 but no one answer me ,, so i decided to open a new post , i am sorry for that ... (i did search and asked in the right place but no one get attention to my post)

if you upload a  small photo , smaller than 320 wide , i think the photo has to be enlarge to 320 ! correct .. have a look :
when i pass a small photo to the `MediaAutoResizer` and send it to the upload function :

`upload#exception 'InvalidArgumentException' with message 'Instagram only accepts photos that are between 320 and 1080 pixels wide. Your file is 282 pixels wide.' in /home/myinstaranker/public_html/panel/boot/vendor/mgp25/instagram-php/src/Utils.php:399`

i did upload a small photo but

```php
MediaAutoResizer($filename, ['operation' => MediaAutoResizer::EXPAND]); 
```
did not EXPAND the photo to the correct dimensions

the script dos not enlarge the photo , of at least create an empty white photo with the correct size and place the photo in the center of the white photo !

Please Advice

**Comment by mgp25** [comment]
@historylife in that case image quality will be bad. I personally don't recommend using images lower than 320 px as stated in the specifications. If you need that particular photo to be uploaded, you can prepare it so its fits correctly.

Keep in mind that the base of Instagram is quality images, no one wants to see a pixelated or bad quality image.

**Comment by historylife** [comment]
@mgp25 I do respect your point of view , and i know that the photo may be pixelated , but what if we place the small image as it is in a middle of white blank photo , so in this case we did not change the photo as it self but we made some kind of big white padding.

What do you think ?

**Comment by aitte2** [comment]
@historylife You can use that scaling in your own code , but I don't think it should be in the library. I agree with mgp25: Instagram should be quality images only and this library shouldn't make it easy to post crap. :P

**Comment by historylife** [comment]
@aitte2 I agree with 100% , that's make sense , But what i am referring to , in order to make this lib user friendly , we may add this an option , user may have choice , Democracy  :)

**Comment by valga** [comment]
`MediaAutoResizer` was designed based on assumption that Instagram checks only aspect ratio for uploaded images. In fact, you can upload even 1x1 image and it will be auto-upscaled by Instagram see https://github.com/mgp25/Instagram-API/pull/1085#issuecomment-287604598.

And that 320px width check was introduced recently: https://github.com/mgp25/Instagram-API/commit/bef9a6ebada6174246654e4201ec4b44cd2949bb#diff-8196fda03bd99e941e07599792a645a4L394

I don't know whether Instagram still accepts 1x1 images, but if so, we could just remove 320px constraint.

**Comment by aitte2** [comment]
@valga But the server will not receive less than 320px wide images from the real app, right? If you try uploading a 1x1 px image from your photo albums, what happens and what is the "original_width" value in the final image if it works?

**Comment by historylife** [comment]
@valga . no server did not upscale any thing (instagram server i mean ) check this error returned from the server : 
`upload#exception 'InvalidArgumentException' with message 'Instagram only accepts photos that are between 320 and 1080 pixels wide. Your file is 282 pixels wide.' in /home/myinstaranker/public_html/panel/boot/vendor/mgp25/instagram-php/src/Utils.php:399`

**Comment by SteveJobzniak** [comment]
@valga This is what I based that rule on:

https://www.facebook.com/help/instagram/1631821640426723?helpref=uf_permalink

It says that 320 wide to 1080 wide are the only allowed widths, and that anything over/under will be automatically scaled by their server. But I set a hard limit on at least 320 wide, to avoid people uploading extremely tiny photos, and to avoid triggering server-side scaling (which helps avoid our library "looking weird" compared to a real client).

It's possible that we can remove the lower limit but I don't think anyone would really care. 320x240 is already this tiny:

![androidtigerwallpapers](https://user-images.githubusercontent.com/22373193/29593203-4c9c7708-87a9-11e7-87f3-abb0ac90db88.jpg)

I don't think many people have smaller images than that.

**Comment by valga** [comment]
@SteveJobzniak We are offering `MediaAutoResizer` as an all-in-one solution, so it is kind of inappropriate to fail with small images, because we promised that it will fix every image to comply to Instagram requirements.

But this issue is not as simple as it seems. For example, we have 1x1 black image. If we just expand it to 320px, nobody will see that dot, so we should upscale it (as Instagram server does). But if we have 300x300 image, we could just expand it without scaling. So we must find a max resolution to scale from.

Another thing is deciding whether to keep aspect ratio. For example, we could expand 300x300 image to 320x300 or 320x320. Which one is more appropriate?

**Comment by SteveJobzniak** [comment]
@valga I agree. The main class itself blocks media if `less than 320px wide`, which I think is the right thing to do. But to match that requirement, the `MediaAutoResizer` would be improved if it actually upscaled to 320px minimum if given less than that.

Here's the most appropriate algorithm:

1. Add a `MIN_WIDTH` constant to `MediaAutoResizer`. Done: https://github.com/mgp25/Instagram-API/commit/44ae35a6d6cd8eb7fbe784885fcd60a1e29b5b14
2. Update "should process?" to also process if the width is < min_width.
3. Update the process-algorithm to do proper upscaling.

For step 3 (new process-algorithm), here's what I think would be most appropriate:

1. Initialize the local variables $width and $height to the original input size. This is already being done (literally at the top of `_processResource`). It gives us the "initial target resolution".
2. Check if width < 320. If so, set $width to 320, and set $height to `floor($width / $this->_aspectRatio)` (floor is used to avoid too-tall images), and update `$this->_aspectRatio` (and take rotation into account) to the new exact ratio we got from the upscaling. This gives us an "initial upscaled target resolution and aspect ratio", which the algorithm can further process.
3. Carefully tweak the rest of the processing algorithm so that it uses the local, updated "at least 320px wide" `$width` and `$height` variables instead of the original `$this->_width` and `$this->_height`... I say "carefully tweak", because in some cases we may have had a good reason to use the original variable instead of the local "`$width`/`$height`" variables, to get a "fresh reference to the original input data"... So it must be very carefully rewritten. And we also need to consider whether we should always use `$targetAspectRatio` instead of the local variable...

Before this work can be begun by one of us, I'll do one more commit in a moment, where I'll update some variable names in to make the algorithm even clearer.

**Comment by SteveJobzniak** [comment]
@valga @historylife I ended up spending the last 4 hours rewriting the algorithms to support upscaling. It seemed easy at first (and the final code may even seem pretty easy and obvious), but it was more work and planning and testing than expected!

Here are the notes from the commit message, since I describe everything in that message:

**MediaAutoResizer: Support upscaling, Refactoring**:
https://github.com/mgp25/Instagram-API/commit/dac8e56450c0de85082a79858333daf97952a924

---

Completes the work begun in commit 44ae35a.

Closes #1503.

Whew, this was a ton of work figuring out the best new algorithm to
allow upscaling tiny images to at least 320px, without breaking any of
the current CROP/EXPAND code.

Changes:

- Improved comments where necessary to explain the algorithm even more.

- Now also processes input-images if they are below the minimum allowed
  width (320px).

- Clearer variable names in `_processResource()`; no longer named
  $width/$height. Instead we use $targetWidth and $targetHeight,
  which makes it clear that they're for calculating final canvas size.

- Fixed cropping algorithm to make it capable of calculating cropping
  shift-offsets even when doing upscaling. To do so, we needed to
  calculate both the cropped target canvas dimensions and the cropped
  input dimensions, and then we use the input dimensions to calculate
  how many pixels to shift the input offsets.

- New variable `$useFloorHeightRecalc` which determines whether we'll
  use floor() or ceil() in the scenarios where we need to change the
  final image's width (and height). This variable is automatically set
  to its most appropriate state depending on whether the input was below
  the minimum ratio or above the maximum ratio. However, if the input is
  within the allowed range, we instead auto-calculate the most
  appropriate value for `$useFloorHeightRecalc` based on whether the
  input is closest to the minimum or the maximum allowed ratios.
  In short: This new variable gives us the safest and most perfect way
  of calculating the final height by ensuring that our final image can
  never break the desired aspect ratio limits.

- New way of calculating square images. It's done before the final width
  calculations. And since squares will always have identical width and
  height (target aspect = 1), squares will not care about the value of
  `$useFloorHeightRecalc` if the dimensions need to be re-calculated,
  since a square result is always identical via both ceil() and floor().

- Lastly, there's a brand new way of validating and calculating the
  final dimensions, which happens at the end: If the final canvas width
  is greater than the max, or less than the minimum, then we set the
  width to max (or min). And then we'll re-calculate the height via the
  target aspect ratio AND the value of `$useFloorHeightRecalc`. As
  described above, that variable ensures that the final dimensions will
  always be perfectly valid aspect ratios, by using either ceil() or
  floor() for the height calculation automatically, based on whichever
  is most appropriate for the input image!

So... whew, it's been a few hours of hard work but now the
MediaAutoResizer can perfectly handle automatic upscaling
to the minimum dimensions allowed by Instagram!

When using EXPAND mode, the image will now be upscaled so that the
largest side touches the edges, and the blank space on the other side
will be filled in with colored edges. When using CROP mode, the image
will be upscaled and cropped so that the image reaches all edges.

For the few people who want to post <= 320px wide images, these changes
will be what they've been dreaming of! ;-)

Enjoy! - Steve

**Comment by SteveJobzniak** [comment]
Here are two small test images I created for use with the new upscaling algorithm:

![tiny](https://user-images.githubusercontent.com/22373193/29630882-03ec0344-883e-11e7-8e92-077719a44cd9.jpg)
![tinywide](https://user-images.githubusercontent.com/22373193/29630883-03ef11a6-883e-11e7-9968-fc9cf67fb07e.jpg)

Here's the test-code I was using to process each image and test each mode:

```php
$options = [
    // 'operation' => \InstagramAPI\MediaAutoResizer::EXPAND,
    'minAspectRatio' => 1,
    'maxAspectRatio' => 1,
];
$resizer = new \InstagramAPI\MediaAutoResizer('tiny.jpg', $options);
copy($resizer->getFile(), 'out.jpg');
$resizer = new \InstagramAPI\MediaAutoResizer('tinywide.jpg', $options);
copy($resizer->getFile(), 'outwide.jpg');
```

Use that, and uncomment operation to compare EXPAND-upscaling vs CROP-upscaling (default).

**Comment by historylife** [comment]
@SteveJobzniak you are such a hero ! Thank you

**Comment by SteveJobzniak** [comment]
@historylife Aww, thanks for letting me now the work is appreciated! Enjoy! :)

**Comment by e-ht** [comment]
We need a 'send beer/coffee' option on Github...

**Comment by SteveJobzniak** [comment]
@e-ht Hehe, that option _can_ be arranged. ;) [With this link](https://www.paypal.me/Armindale/0usd). It's been a few months since I last received any donation, but it's totally up to you. Thanks anyway. :)
