### ISSUE TITLE
Seems fetching next page of liked feed  doesn't work.

### ISSUE THREAD

**Issue by Yoloper** [mgp25/Instagram-API#1544]
Just like the title said, it work find in first page but the next page return the same data.

I am pretty sure there is page 2 of my liked feed and I use the code right.

> Maybe the api have changed? Thanks in advance.

**Comment by mgp25** [comment]
Hello @Yoloper, when opening an issue, make sure to give as much details as possible, that means also posting the code you are using to do pagination and so. I'll test later.

Regards

**Comment by SteveJobzniak** [comment]
I wrote some quick and sloppy test-code just to check it... But note to everyone: DO NOT USE THIS METHOD OF PAGINATION IN REAL USAGE, SINCE IT HASN'T GOT ANY DELAYS! IF YOU DON'T HAVE ANY sleep() YOU WILL GET BANNED BY INSTAGRAM FOR ABUSING THEIR SERVER!

```php
$maxId = null;
do {
echo "-------------------\n";
echo "Page: {$maxId}\n";
$res = $ig->media->getLikedFeed($maxId);
foreach ($res->getItems() as $item) {
    printf("- %s.\n", $item->getId());
}
echo "-------------------\n";
$maxId = $res->getNextMaxId();
} while ($maxId !== null);
```

And the result is:

- I am using v3.0.1 stable of this library.
- Using the code above, every paginated result gave me different media IDs. So pagination works perfectly.
- The "next_max_id" param always pointed to the pure ID of the last item on the current page. So for example if the last item was "123812382138_12392", the next_max_id param was "123812382138".
- There is no problem with the endpoint or pagination.

Please try using my code. If that fails, Instagram doesn't like you.

**Comment by Yoloper** [comment]
Thanks guys @mgp25  @SteveJobzniak . I found that it is my fault. I make a stupid mistake in my code.
