### ISSUE TITLE
How to login with cookie for fast follow ?

### ISSUE THREAD

**Issue by set** [mgp25/Instagram-API#1545]
I use;
`
$i = new \InstagramAPI\Instagram();
foreach($users as $k => $v){
	$i->login($v->username, $v->password);
	$i->follow("USER_ID");
}
`
but is very very slow. I think I need to use cookie files. How can I do it ?

**Comment by robdiberlin** [comment]
however, you shouldn't do this with this library... Seems like you want to spam - it is against the rules and btw... this library is more for fun... From the first login, instagram knows that you are using this library and btw. instagram maybe let this library because their contributors keep this save.
For more informations def. check Terms and conditions 👍

**Comment by mgp25** [comment]
@robdiberlin thanks!
