### ISSUE TITLE
There is some Function to check if Media is Liked?

### ISSUE THREAD

**Issue by cleiomar** [mgp25/Instagram-API#1557]
There is some Function to check if Media is Liked by own user? something like "isLiked('MediaID')"

Already check at wiki documentation and not found.

**Comment by mgp25** [comment]
Hello @cleiomar,

All functions related to media can be found in [/Request/Media.php](https://github.com/mgp25/Instagram-API/blob/master/src/Request/Media.php), but that is something you already know since you have read the [wiki](https://github.com/mgp25/Instagram-API/wiki).

There is a function to get detailed media information which is `getInfo()`. You can also get your liked feed `getLikedFeed()`

Regards
