### ISSUE TITLE
Get more/other stories on location feed

### ISSUE THREAD

**Issue by BTopbas** [mgp25/Instagram-API#1560]
Hi;
I use this code to retreive story users of location. But can't mark as seen. Everytime retrive same stories. In application, i viewed and refreshing new stories. If no new story in location, stories not appear.

```
$location = $i->location->getFeed("112768952070470");
$stories = $location->story->items;
foreach ($stories as $story) {
echo $story->user->username;
}
$i->story->markMediaSeen($stories);
```
This code i retrive usernames of location stories but can't marks as seen. Last line not working..

**Comment by SteveJobzniak** [comment]
The last line (markMediaSeen()) is telling the owner of the story that you have seen it (they will see your name in the list of people who have seen their story). You would know that if you read the function docs for that function:

https://github.com/mgp25/Instagram-API/blob/2e09fe566f67e4626cd067d23b7081f2052358ab/src/Request/Story.php#L177

To get more stories in a location feed needs some other method. Probably same as the hashtag feed functions; we'll probably need to send a param with a list of stories to ignore at that location, to get different ones. But we will not be in any hurry to implement this because Instagram does not intend for people to request tons of stories from the same location over and over. They actually block you if you try doing that for hashtag feeds, and I think the situation is the same here.

**Comment by mgp25** [comment]
Hello there, you need to do the following thing:

```php
$response = $i->location->getFeed($locationId);

$locationItems = [];
$storyLocationId = $response->getStory()->getId();
$stories = $response->getStory()->getItems();
foreach($stories as $story) {
    $locationItems[$story->getId().'_'.$storyLocationId] = [$story->getTakenAt().'_'.time()];
}

//Note: where i did time() it is the seen time.
```

There is slight differences, and we might need to update `markMediaSeen()` function.

Regards

**Comment by SteveJobzniak** [comment]
@mgp25 Hmm... in that case, we should carefully implement it because `markMediaSeen()` wasn't meant for stories from Locations, so there are multiple ways to do it:

- We could add a "storyLocationId" parameter to `Story::markMediaSeen()`, and if it's provided, we generate a location-based ID for every story item...
- Or, we could add a `Location::markStoryMediaSeen()` which may take an Items array + a "storyLocationId" and then loop through all items, and use their `setWhatever()` on each item to set some value to the location ID instead, and then pass the "manipulated" Items array to `Story::markMediaSeen()` so that it generates the final, correct API query.

I dunno, we'll have to research this. It's not high-priority and I am very sick right now, so let's not rush this decision. And @valga perhaps has some idea?

**Comment by valga** [comment]
As far as I can see, seen items always are in `%ITEM_ID%_%SOURCE_ID%` format, where `%SOURCE_ID%` can be one of: user ID, location ID and probably tag ID. So we could convert `Story::markMediaSeen()` to accept source ID param, and then add a couple or proxy methods into `User`, `Location` and may be `Tag` classes.

**Comment by SteveJobzniak** [comment]
@valga Good observation. You're right, `%ITEM_ID%_%SOURCE_ID%` explains why the item ID (which ends in `_userId`) became `mediaId_userId_userId`. The last value is the source Id. We could do something like `(array $items, $sourceId = null)` and if it's NULL we use the $item->getUser()->getPk() as the source ID as usual. If non-NULL we use that value instead. And then we just finish it up with some basic wrappers in other collections that need to be able to mark stories. Sounds great.

**Comment by SteveJobzniak** [comment]
I have had a discussion with mgp25 tonight. The API is complete and up to date, and we've been working on it non-stop for so long. All of our instant support and instant coding and instant feature additions etc is totally killing us. So we'll slow down a bit now that v3 is out and the API is totally stable.

We're simply going to change the pace around here a bit. These tickets will remain open for a while, and we'll take care of them when we _feel_ like relaxing and doing some coding. Any ultra-critical bugfixes will of course still get high priority, but minor things or new features will happen when time is available.

This particular ticket will take some time to get through. Don't worry, it _will_ get done when we feel like relaxing with some programming, and we don't need to be reminded. This change of pace is simply for our health's sake. We've worked so hard for so long. Thank you very much for your contribution!

**Comment by solomax2014** [comment]
@SteveJobzniak, yes, health is most important. Keep healthy and have a rest!

**Comment by BTopbas** [comment]
```
public function markMediaLocationSeen(
        array $items,
        $locationId = null)
    {
        // Build the list of seen media, with human randomization of seen-time.
        $reels = [];
        $maxSeenAt = time(); // Get current global UTC timestamp.
        $seenAt = $maxSeenAt - (3 * count($items)); // Start seenAt in the past.
        foreach ($items as $item) {
            if (!$item instanceof Response\Model\Item) {
                throw new \InvalidArgumentException(
                    'markMediaSeen(): All items must be instances of \InstagramAPI\Response\Model\Item.'
                );
            }

            // Raise "seenAt" if it's somehow older than the item's "takenAt".
            // NOTE: Can only happen if you see a story instantly when posted.
            $itemTakenAt = $item->getTakenAt();
            if ($seenAt < $itemTakenAt) {
                $seenAt = $itemTakenAt + 2;
            }

            // Do not let "seenAt" exceed the current global UTC time.
            if ($seenAt > $maxSeenAt) {
                $seenAt = $maxSeenAt;
            }

            // Key Format: "mediaPk_userPk_userPk" (yes, userPK is repeated).
            $reelId = $item->getId().'_'.$locationId;

            // Value Format: ["mediaTakenAt_seenAt"] (array with single string).
            $reels[$reelId] = [$item->getTakenAt().'_'.$seenAt];

            // Randomly add 1-3 seconds to next seenAt timestamp, to act human.
            $seenAt += rand(1, 3);
        }

        return $this->ig->request('media/seen/')
            ->setVersion(2)
            ->addPost('_uuid', $this->ig->uuid)
            ->addPost('_uid', $this->ig->account_id)
            ->addPost('_csrftoken', $this->ig->client->getToken())
            ->addPost('reels', $reels)
            ->addPost('live_vods', [])
            ->addParam('reel', 1)
            ->addParam('live_vod', 0)
            ->getResponse(new Response\MediaSeenResponse());
    }
```
I created this function. Tested and this is working. I added locationid parameter and changed userid line to locationid. And now working perfect. Thanks for advice.

**Comment by SteveJobzniak** [comment]
@BTopbas Yep, that's right, you can use that while you wait! :-) But we'll solve it another way, without code duplication.

**Comment by SteveJobzniak** [comment]
I have now properly fixed this in the following pull request: https://github.com/mgp25/Instagram-API/pull/1619

(Commit: https://github.com/mgp25/Instagram-API/pull/1619/commits/f11eeb8214e772922d1f66067080377b4d243509)

Not merged yet, but will be soon.

**Comment by SteveJobzniak** [comment]
Alright, I went through and looked at all responses to see which ones can contain story trays. Literally only regular `Story::` search-functions, and the `Hashtag::getFeed()` and `Location::getFeed()` functions.

I've now added the final function for marking Hashtag stories seen as well:

https://github.com/mgp25/Instagram-API/pull/1619/commits/3caf151105416ad05970c2a877f03e553af209b3

Users will have to wait until it's merged.

**Comment by SteveJobzniak** [comment]
Fix is now merged to `dev-master`. :)

**Comment by marf** [comment]
Hello guys and thank you for this awesome API. I was wondering if there was the possibity to count mber of stories in a certain location because I wanted to build some statistics about how a place is full of people or not.
With the API to get stories from a location I get only 18 stories at a time (and if I refresh I get a fewer number of the remaining (less than 18)), I think that instagram has coded these limit in their API, but is there a way to bypass it?

I mean, I only need ther number of the stories published in that location and I wondered if it is possibile.

Thank you,
Marco
