### ISSUE TITLE
Error 500 when instantiating the Instagram Object

### ISSUE THREAD

**Issue by rt-2** [mgp25/Instagram-API#1561]
Hi
```
<?php
	set_time_limit(0);
	date_default_timezone_set('UTC');
	require '../vendor/autoload.php';
	echo 'works';
?>
```
works...
```
<?php
	set_time_limit(0);
	date_default_timezone_set('UTC');
	require '../vendor/autoload.php';
	try {
		$debug = true;
		$ig = new \InstagramAPI\Instagram($debug);
	} catch (\Exception $e) {
		echo $e->getMessage()."\n";
	}
	echo 'works';
?>
```
returns error 500.

I don't know how to test, I was not familiar with Composer, but with some playing around I managed to run `composer install` without any errors and it created the wanted 'vendor' directory with the 'autoload.php'.
But everything I try returns a blank error 500....

Thank you,
rt-2

**Comment by SteveJobzniak** [comment]
```
$ cd ~/Desktop/

$ mkdir test

$ cd test

$ composer --version
Composer version 1.4.2 2017-05-17 08:17:52

$ composer require mgp25/instagram-php
Using version ^3.0 for mgp25/instagram-php
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 21 installs, 0 updates, 0 removals
  - Installing psr/log (1.0.2): Loading from cache
  - Installing binsoul/net-mqtt (0.2.1): Loading from cache
  - Installing react/promise (v2.5.1): Loading from cache
  - Installing react/event-loop (v0.4.3): Loading from cache
  - Installing react/promise-timer (v1.2.0): Loading from cache
  - Installing evenement/evenement (v2.1.0): Loading from cache
  - Installing react/stream (v0.7.3): Loading from cache
  - Installing react/socket (v0.8.3): Downloading (100%)         
  - Installing react/dns (v0.4.11): Loading from cache
  - Installing react/cache (v0.4.1): Loading from cache
  - Installing valga/fbns-react (0.1.7): Loading from cache
  - Installing psr/http-message (1.0.1): Downloading (100%)         
  - Installing ringcentral/psr7 (1.2.1): Loading from cache
  - Installing clue/http-proxy-react (v1.2.0): Loading from cache
  - Installing clue/socks-react (v0.8.5): Loading from cache
  - Installing binsoul/net-mqtt-client-react (0.3.2): Loading from cache
  - Installing guzzlehttp/promises (v1.3.1): Downloading (100%)         
  - Installing guzzlehttp/psr7 (1.4.2): Loading from cache
  - Installing guzzlehttp/guzzle (6.3.0): Loading from cache
  - Installing netresearch/jsonmapper (v1.3.0): Loading from cache
  - Installing mgp25/instagram-php (v3.0.1): Downloading (100%)         
react/event-loop suggests installing ext-libevent (>=0.1.0)
react/event-loop suggests installing ext-event (~1.0)
react/event-loop suggests installing ext-libev (*)
valga/fbns-react suggests installing ext-event (For more efficient event loop implementation.)
valga/fbns-react suggests installing ext-gmp (To be able to run this code on x86 PHP builds.)
mgp25/instagram-php suggests installing ext-event (Installing PHP's native Event extension enables faster Realtime class event handling.)
Writing lock file
Generating autoload files

$ mkdir app

$ cd app

$ vim test.php

$ cat test.php
<?php
	set_time_limit(0);
	date_default_timezone_set('UTC');
	require '../vendor/autoload.php';
	try {
		$debug = true;
		$ig = new \InstagramAPI\Instagram($debug);
	} catch (\Exception $e) {
		echo $e->getMessage()."\n";
	}
	echo 'works';
?>

$ php -version
PHP 7.0.20 (cli) (built: Jun 28 2017 16:05:54) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies

$ php test.php 
works

$ /usr/bin/php -version
PHP 5.6.30 (cli) (built: Feb  7 2017 16:18:37) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

$ /usr/bin/php test.php
works
```

**Comment by SteveJobzniak** [comment]
I hope you can find the problem, but it's something with your own webserver.

Try turning on more logging on your server. Your server may be executing the PHP binary, getting an exception of some kind, and then suppressing the actual error and just outputting a blank "HTTP Error 500 Internal Server Error" page.

Only thing that's for sure: It's not this library. There are tens of thousands of successful users. And as you can see from the code your own example script works perfectly on PHP 7 and PHP 5.6.

Here is my actual theory: Your server is throwing an exception, and is configured as a "production server" to hide possibly dangerous (may expose internal server details) "raw" error pages by hiding it behind a general "Error 500" HTTP page instead.

Furthermore, my theory is that your web server doesn't have write-access to create the `sessions/` folder for user storage. You will see that error if you can get the server to show actual PHP errors instead of just a blank HTTP 500 page.

**Comment by SteveJobzniak** [comment]
Duplicate of #1559.

**Comment by SteveJobzniak** [comment]
So yes this is a user-error with your server configuration as I replied in the original ticket. But the good news is that we support changing the session storage location and method, like this:

https://github.com/mgp25/Instagram-API/blob/master/examples/customSettings.php

Good luck. :-)

**Comment by rt-2** [comment]
I love how you super fastly close any issue, like you would like this function not to even exist?
This server hosts 10+ application, I don't understand how YOUR is SO SPECIAL?????

THIS IS an issue, please stop closing the second you read it, this is super annoying.....
I swear even my client thinks you're an asshole...
The way you answer like you know every damn thing in the world annoys me super much....

**Comment by SteveJobzniak** [comment]
@rt-2 Because it's a problem with your personal server, not with this library. 100% proven, and guaranteed.

In fact, I just Googled "php error 500" (which you should have done before wasting my time). The problem is that your server's `php.ini` is set to `display_errors 0`. That makes your webserver throw an empty "Error 500" page instead of showing the actual error text.

Turn it to 1, and you will see the error. Most likely it's the sessions-storage folder, exactly as I said above. Which you would have known if you had Googled "php error 500", seen the first result telling you to enable `display_errors 1` to see the actual error, which would have shown you something like `The "/home/whatever/project/vendor/mgp25/instagram-php/src/../sessions/" folder is not writable.`

**Comment by rt-2** [comment]
Yes I found my problem,,, it was exactly why I included 3 example instead of 2, the problem was in Composer which I followed your instructiosn but it does not install correctly,,,
THE PROBLEM IS NOT MY WEB SERVER YOU DAMN NOOB, Apache2 and PHP was well configurated... please use the right words,,, my "WEB SERVER" was NOT AT FAULT GOD DAMNIT

**Comment by SteveJobzniak** [comment]
@rt-2 The problem is in your server. **You have disabled error display on the server**, so you got the "HTTP Error 500" page instead of seeing the real error. It's absolutely **nothing** to do with our library. If you enable error display, you would have seen something like "Unable to load class \InstagramAPI\Instagram", since you say it was an autoload-problem. Now fuck off you obnoxious cunt.
