### ISSUE TITLE
Does the Realtime client use the same proxy settings used for the rest of the endpoints?

### ISSUE THREAD

**Issue by mme76** [mgp25/Instagram-API#1565]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [X] Question
- [ ] Other

---

I was looking at the MQTT code and I couldn't find any references to proxy settings. I'm sure I just missed them, because of course otherwise Instagram/Facebook would immediately detect something wrong... the same user, from the same device and session contacting regular endpoints from one IP and the realtime ones from a totally different IP at the same time... could you please confirm?

**Comment by SteveJobzniak** [comment]
Hi! Yes, `Push.php` and `Realtime.php` both use our `src/React/Connector.php`:

https://github.com/mgp25/Instagram-API/blob/master/src/React/Connector.php

As you can see, it reads the proxy state + "verify SSL?" flag from the active Instagram API class instance. So as long as you set your proxy on the `Instagram()` object _before_ you connect to Push or Realtime, you will be connected via proxy.

Thanks to @valga for that clever system! ❤️

**Comment by valga** [comment]
It should be noted that Realtime and Push do not inherit output interface setting from parent `Instagram` object.

**Comment by SteveJobzniak** [comment]
@valga Good point. Makes sense, since that option is only supported by Guzzle's cURL backend, and not by the libraries you selected for realtime communication.

Luckily, pretty much 0.001% of people use the "setOutputInterface" feature. It was added for some weirdo with multiple network cards (with different IPs on each) who wanted to force a specific one for a specific IP. :-P
