### ISSUE TITLE
Endpoint for checking if a Direct thread already exists for a user?

### ISSUE THREAD

**Issue by saratik** [mgp25/Instagram-API#1570]
How we can get thread id by User id or user name?
I think, real app doesn't get all threads and tries find id in array.
There must be one request for this action.
You can be sure of this, when you search user and try sending message, after that you'll be see all old messages on screen (if you have exists thread with this man).

**Comment by SteveJobzniak** [comment]
You realize apps have databases? That is how it stores all old messages locally in the app and doesn't have to download them again.

The app most likely calls the "get inbox" endpoint periodically and always stores a list of all threads + userids in its app-database. So when you press Send Message on a profile it goes "SELECT thread_id FROM direct_threads WHERE participants LIKE '12345'" and finds the thread ID already.

But if anyone wants to investigate, you can debug the real app's http requests to see what it does when you press Send Message on a profile. Perhaps it calls some "get thread for user id" endpoint. Probably not, though.

**Comment by saratik** [comment]
I really know that client app save last 20 threads in data base(with messages). But i have some doubts about all threads.
About ""get list of all threads for user id X"  you are probably right.
Now, i'm tring simple  test
1. (Online) i'm searching recipient
2. (Offline) i'm tring to open thread as "send new message" 
3. On view i see, current exists thread . 
Сonclusion: most likely, apps save threads history in DB.
Thank you for the hint, @SteveJobzniak.

**Comment by valga** [comment]
https://github.com/mgp25/Instagram-API/blob/1c1b6ac6a59f657251d15db4ab893b8684f8f6d2/src/Request/Direct.php#L200

**Comment by SteveJobzniak** [comment]
@saratik So you made your phone go offline, and then pressed Send Message on a user, and it opened the existing thread? Okay so that's a strong sign that the app already knows the thread ID locally (offline, in its database).

@valga Hi. I just saw your message. I forgot about that function because I never use Direct myself. Are you suggesting that he calls getRankedRecipients with `$query` set to the username of the user he wants to find?

And perhaps you know the original question's answer: Does the official app call any "get list of threads for user X" endpoint when the user visits their profile or wants to send them a message, or does the app fully locally cache all of the valid thread IDs?

**Comment by valga** [comment]
@SteveJobzniak It depends on scenario. Sometimes (stories and sharing) app searches for existing threads by calling that ranked recipients endpoint, sometimes (text messages) app searches only for user ID by calling generic user lookup endpoint.

App uses local threads DB only for offline mode.

**Comment by saratik** [comment]
@valga  it does mean 
On first step searching, app uses UserSearch request-> 
then-> opens detail page -> then we select "Send new message", app sends two new requests 
getRankedRecipients() and if thread exists sends getThread()?

**Comment by valga** [comment]
Just checked recent version of the app to be completely sure, and you are right: app uses local DB to find existing threads when sending a message from profile. 

But ranked recipients endpoint is still being used by stories and sharing stuff, so it is a valid way to get a thread by username.

**Comment by SteveJobzniak** [comment]
@valga That's a great discovery! Thanks for verifying. That method certainly makes it a lot easier for people.

So to summarize this thread's info:

- The real app uses its own local ("offline") app database to find the thread ID when sending messages to a user (via the "Send Message" button on that user's profile page).
- The real app calls an API endpoint, `Direct::getRankedRecipients()` when sending direct stories and shared media etc to a user.
- Which means that it's safe to frequently call and use `Direct::getRankedRecipients()` every time you want to find the thread for a user, if you want to, since the real app apparently calls it quite often too.
- You can therefore choose: Either you cache all of your Inbox's thread IDs somewhere and just refer to your own local cache, or you can simply call that API endpoint to ask Instagram instead. But you should always try to reduce the amount of API calls you do to Instagram in general, so caching the threads locally would be a good way to reduce the number of API calls.

This ticket is solved then. Take care and good luck. :-)
