### ISSUE TITLE
Mapping Media From Album Posting

### ISSUE THREAD

**Issue by michaeldprice** [mgp25/Instagram-API#1581]
Hello. I love the api.

I do have an issue/suggestion...

Currently I am mapping source files to network files when uploading media.
However, since all the uploads are done in one shot it seems, I have no way to map the local file, with the uploaded file.

Wouldnt it be possible to pass back the provided  "file" parameter in the IgResponse?
Also, are there any docs that explain the return data from posting?

**Comment by SteveJobzniak** [comment]
Hi! Glad you like the library!

To answer your questions:

- Adding your original disk-filenames to the server response, so that you know which file each media item in an album came from: Impossible. The server response comes from instagram.com, and we do not control it at all. We cannot add anything to it. This library is an unofficial reverse engineering of their private app API, and we emulate the Android app, and whatever their server responds with is their final answer.
- Are there any docs that explain the fields in posting and other APIs: No, because it’s an unofficial reverse engineered API. We have done our best to document all functions perfectly. But their return values from the server are up to the user to use how they see fit. Luckily most variables in the responses make sense and are well named by Instagram.

I will give you a tip, though:

`var_dump($response->getFullResponse());`

That command will dump a list of all raw data that came from the server. So you won’t have to look at all empty NULL fields. It makes it a bit easier to look at the relevant data structure to figure it out.

😄
