### ISSUE TITLE
PrepareRecipients Error on Direct Messages

### ISSUE THREAD

**Issue by osyduck** [mgp25/Instagram-API#1585]
Catchable fatal error: Argument 1 passed to InstagramAPI\Request\Direct::_prepareRecipients() must be of the type array, string given, called in C:\xampp\htdocs\IG\vendor\mgp25\instagram-php\src\Request\Direct.php on line 1132 and defined in C:\xampp\htdocs\IG\vendor\mgp25\instagram-php\src\Request\Direct.php on line 928

i got this error. How to fix it?

**Comment by osyduck** [comment]
here is the code

$userId = $ig->people->getUserIdForName('osyduck');
$recipients = array("users"=>array($userId));

$text = "hi";
$send = $ig->direct->sendText($recipients['users'], $text);
print_r($send);

**Comment by SteveJobzniak** [comment]
@valga The problem here is that the user called `$ig->direct->sendText($recipients['users'], $text);` instead of `$ig->direct->sendText($recipients, $text);`... But it does illustrate a good point: `_prepareRecipients()` is too strict. Its first argument must be untyped. And then validated inside `_prepareRecipients()` via `!is_array() { throw \InvalidArgumentException(); }`. 

I'm swamped with work on the `LazyJsonMapper` every day. Do you have any time for this particular fix? I've assigned it to the Next release in the project tracker.

**Comment by valga** [comment]
> But it does illustrate a good point: `_prepareRecipients()` is too strict.

Nope, `sendText()` (and other methods) is too loose. The phpDoc says that `$recipients` param is an array:
https://github.com/mgp25/Instagram-API/blob/5724d8078270c02300589d1783fec9493f4e4f96/src/Request/Direct.php#L454

But there is no `array` typehint in args:
https://github.com/mgp25/Instagram-API/blob/5724d8078270c02300589d1783fec9493f4e4f96/src/Request/Direct.php#L468

**Comment by SteveJobzniak** [comment]
@valga Ohhhh. Good point. That's a much better fix then.

I need sleep. ;-)

**Comment by osyduck** [comment]
Solved when i close this issue. Here is my new code

$userid = $this->getUserId($username);
$userids[] = $userid;

$send = $this->ig->direct->sendText(array("users"=>$userids), $text);
