### ISSUE TITLE
The Realtime client can only run from the command line.

### ISSUE THREAD

**Issue by hosberd** [mgp25/Instagram-API#1588]
Hello,
I run this file  as you do in your example https://github.com/mgp25/Instagram-API/blob/master/examples/realtimeHttp.php. But I get the error 'The Realtime client can only run from the command line'. Why?

What does it mean '(PHP_SAPI !== 'cli')'?

**Comment by valga** [comment]
Are you running it from the command line?

**Comment by SteveJobzniak** [comment]
Because you can only run Push + Realtime from command line (from `php.exe` / `php` binary). You cannot run it via a webpage.

The Push and Realtime clients must be persistent (keep running forever). A webpage would kill it instantly.

If you want to interact with the Push and Realtime clients from a webpage, you must do two things:

1. You must run a separate, persistent process that runs Push and/or Realtime (you can edit your code to achieve both in the same script, [https://github.com/mgp25/Instagram-API/issues/1582#issuecomment-331615895](as noted here)).
2. You must code your webpage script to locally interact with your persistent Push/Realtime php script. Either via local sockets, or via a database that they both share, etc.

You don't seem to have much PHP experience so both of those are very advanced topics that we will not explain to those who don't understand how to do it themselves. Google is your friend.

If you don't need webpage-access to the Push/Realtime stuff, then you can ignore all of what I just said. In that case, you _only_ have to run the script via a command line/terminal, and do whatever you want to do from that single script.

**Comment by hosberd** [comment]
@valga @SteveJobzniak yes, I`ve run from command line before I wrote this topic. But I still get the error:
`[2017-09-26 23:47:45] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in D:\OpenServer\domains\univle.dev\vendor\evenement\evenement\src\Evenement\EventEmitterTrait.php:93
Stack trace:
#0 {main} `

That's why I thought I do something wrong.

**Comment by hosberd** [comment]
I delete this from library Evenement http://take.ms/hxoAL. Now it works. Xm...

**Comment by SteveJobzniak** [comment]
@hosberd That's a PHP7+ strict return-value. It means you hav an Evenement version for PHP7+. But you are trying to run the code on PHP 5.

Wtf? How did you succeed making such a weird vendor folder? :-P

**Comment by hosberd** [comment]
Oh... It turned out that windows command line runs PHP5, but OpenServer runs PHP7. But I run composer from Openserver :))

**Comment by SteveJobzniak** [comment]
@hosberd This is a common problem. People install the library on their local desktop, then they copy it to the server even though the server may not have all required extensions and PHP versions etc... :)

**Comment by SteveJobzniak** [comment]
@valga I investigated.

I made a blank folder on my desktop computer, and ran composer specifically via PHP 5:

`/usr/bin/php /usr/local/Cellar/composer/1.4.2/bin/composer require mgp25/instagram-php`

Result:

`- Installing evenement/evenement (v3.0.1)`

Then I looked at `cat vendor/evenement/evenement/composer.json`:

```
    "require": {
        "php": ">=7.0"
    },
```

I thought "Hmmm..." and looked at the file: `vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php` and it's full of PHP7 types and uses `declare(strict_types=1);`. It's indeed fully written for PHP7 only.

So uhm... wtf. Composer has a bug. It lets PHP5 install sub-libraries without checking if THEIR PHP version requirement is okay. I guess it assumes that if we include a library we've checked it, or that we perhaps only instantiate it if WE check that the user is running PHP7 during our own runtime. So they assume we know what we're doing when we include stuff...

Either way... here's the situation:

1. If Composer ever recursively checks PHP version requirements for all "require" libraries, then PHP 5.6 (which is what we "require") can no longer install `mgp25/instagram-php`, because the sub-libraries that need PHP7 will block it. I hope that never happens.
2. Either way, this means that `Push` and `Realtime` require PHP7+. So in addition to the `PHP_CLI` check, there should be a PHP version check, so that PHP 5 refuses to run those files. Because they will literally _NEVER_ work on anything less than PHP7.

It's okay that a sub-part of the library needs PHP7. Totally okay. As long as we just add a version check.

To do that, just look at `InstagramAPI\Instagram::__construct()`, where we have a PHP 5.6 check. A similar one is needed in Push and Realtime constructors. :-O :-)

**Comment by valga** [comment]
> Composer has a bug? It lets PHP5 install sub-libraries without checking if THEIR PHP version requirement is okay.

It seems that you are running outdated composer. Try to update it. I can't reproduce the issue:
```
$ php -v
PHP 5.6.30 (cli) (built: Jan 18 2017 19:47:28)
$ composer require mgp25/instagram-php
...
  - Installing evenement/evenement (v2.1.0): Loading from cache
...
```
```
$ php -v
PHP 7.1.9 (cli) (built: Aug 30 2017 20:06:08) ( NTS )
$ composer require mgp25/instagram-php
...
  - Installing evenement/evenement (v3.0.1): Loading from cache
...
```

**Comment by SteveJobzniak** [comment]
@valga I found the issue... it was that that even though I ran `composer` with PHP5, it spawns sub-`php` processes, and just picks the `php` found in `PATH` environment (which is PHP7 for me).

I had to launch composer like this to make it ignore the path where I have PHP7, so that it only finds PHP5:

`PATH=/usr/bin:/bin:/usr/sbin:/sbin /usr/local/Cellar/composer/1.4.2/bin/composer require mgp25/instagram-php`

And that reproduces your success! There is no problem with composer. It picks correctly. I also upgraded my Composer to 1.5.2 after that, hehe.

Okay, so this ticket was a user-issue (a very common one... installing on local composer and moving it to a server with lower PHP... sigh). We've already got constructor-protection against that in the main class constructor (many people move this to webservers that have PHP 5.4 due to "stability" etc). So we warn unless people have PHP 5.6+.

But we can't protect against composer installing PHP7 versions of libraries. Oh well, we'll just have to hope people are smart enough to try it locally and notice that it only fails on their server, and figure out that the problem is their own fault. :D

**Comment by hosberd** [comment]
@SteveJobzniak thank you for answer! 

I have question:
Look, I have such a problem. Here's my account @an_nethe.wat.ch, I posted a comment to my post in my account. If people reply my comment, I don't get comments from them. Is it a bug or not? http://take.ms/2q2qj

**Comment by SteveJobzniak** [comment]
@hosberd It's not a bug. The comments exist in the `Media::getInfo()` call and in your own timeline feed response too (there's a `preview_comments` field in it).

**Comment by valga** [comment]
@hosberd You should use Push example for notifications about comments. Realtime is for Direct.

**Comment by SteveJobzniak** [comment]
Oh, I misunderstood his question and thought he meant that comments aren't in his media feeds.

Yeah, Instagram uses `Realtime` only for Direct messaging (chatting). The `Push` client is the one you want if you want stuff like comment/liking/etc notifications.

**Comment by hosberd** [comment]
@SteveJobzniak I'm talking about Push. The an_nethe.wat.ch comment has already been posted. I did not receive a new comment: '@ an_nethe.wat.ch Hey! '. All other comments I receive.

**Comment by valga** [comment]
@hosberd Did you receive a notification for that comment on real device using the official Instagram app?

**Comment by hosberd** [comment]
@valga yes. And all other comments I receive. But  I did not receive the comment  '@ an_nethe.wat.ch Hey! ' to Push.

**Comment by valga** [comment]
@hosberd Hmm, I tried to receive some pushes with the example script... and failed to do that: I received 0 pushes at all. So it seems there is some kind of problem with them.

@SteveJobzniak Does it work for you?

**Comment by mgp25** [comment]
@valga i can confirm its working.

**Comment by hosberd** [comment]
@mgp25  It`s not working.

**Comment by mgp25** [comment]
@hosberd 

> i can confirm its working.

Tested in 3 accounts. Push notification received in all of them.
