### ISSUE TITLE
Double backslashes not supported by rename() on Windows Server

### ISSUE THREAD

**Issue by Kozzy1055** [mgp25/Instagram-API#1591]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---
Hi, its me again, sorry i didnt have time to respond your questions, you closed the issue so i must open a new cause its still not working and i found the real issue.

Lets clear somethings:

I got the write permission, i checked it, even the `Utils:atmicWrite` can create the `.atomictmp `file, just the rename fails.

So i checked this at `Utils:atomicWrite()`

write to temp file...
success, go on
```php
error_reporting(E_ERROR | E_WARNING | E_PARSE | E_NOTICE);
rename()
failed
$error = error_get_last();
```

`$error msg=rename(D:\home\site\wwwroot\vendor\mgp25\instagram-php\src/../sessions//XXX/XXX-settings.dat.atomictmp,D:\home\site\wwwroot\vendor\mgp25\instagram-php\src/../sessions//XXX/XXX-settings.dat): The specified path is invalid. (code: 161)`

**You were right, not the '/' caused the problem, the real problem was that you have double of it after 'sessions'.**

If i change the line at `Settings/Storage/File.php`
in `line 329`:
from:
```php 
$userFolder = $this->_baseFolder.'/'.$username.'/';
```
to:
```php
$userFolder = $this->_baseFolder.$username.'/';
```

Then everything works fine.

Sorry for my incorrect report, please try out some tests for renaming a path with double `/` (on Windows)

Thank you.

--

**Related issue: https://github.com/mgp25/Instagram-API/issues/1590**

**Comment by SteveJobzniak** [comment]
Thanks for investigating. That means that we're giving Windows a final path like `some\path\\invalid\foo`. The double backslashes are okay on regular Windows which is why we have not had any reports about this before, but apparently not okay on Windows Server.

We will need a different fix, because the one you propose will not work if people provide a custom path and add their own trailing slash or backslash to it.

We need to fix the value of `_baseFolder`, not of the assignment you pointed out. But we cannot use `realpath()` to resolve the path since the folder may not exist yet (we allow non-existent folders).

So I think the final fix will be something like a regex during construction of the `File` class, which cleans up the `_baseFolder` value to remove all trailing backslashes or forwardslashes. But it needs some safeguards. Like never doing that if the user is on non-Windows, since Unix allows backslashes in the folder names...

So yeah it will be fixed when a good algorithm is found to handle cle@ning up the user’s own provided paths.

For now, you can just edit the constructor assignment to make it not add a final slash after the default path it generates for `_baseFolder`.

**Comment by valga** [comment]
> So yeah it will be fixed when a good algorithm is found to handle cleaning up the user’s own provided paths.

It is called `realpath()`.

**Comment by SteveJobzniak** [comment]
@valga I just said that:

>  But we cannot use realpath() to resolve the path since the folder may not exist yet (we allow non-existent folders).

**Comment by valga** [comment]
@SteveJobzniak You can just create that folder with `Utils::createFolder()` and then use `realpath()` on it.

**Comment by SteveJobzniak** [comment]
@valga Good idea!

**Comment by SteveJobzniak** [comment]
@Kozzy1055 Okay, I have just rewritten the code to ensure that it creates the folder early and cleans up its path. Everything should now generate with single slashes and should work. But please, since none of us have Windows Server, can you _please_ try the latest `dev-master` code and let us know if the fix works for you?

https://github.com/mgp25/Instagram-API/commit/f9d614738b7abdffa2d4f30b130c0b20d88a76b8

:-)

**Comment by SteveJobzniak** [comment]
@Kozzy1055 How did it go? Please tell us.

**Comment by SteveJobzniak** [comment]
Marking as fixed since I assume you would have been back if it was still broken. :-P
