### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by mominak47** [mgp25/Instagram-API#1592]
It is showing HTTP ERROR 500, I have just copied accessingValues.php example

**Comment by SteveJobzniak** [comment]
Please search closed tickets, your question has already been answered.

Here is the short answer: This is a problem with your web server.

You are opening the example scripts via a web server/web browser, and your web server has disabled error-display, so instead of showing what is wrong with the code/your settings, you get a blank Error 500 page.

We do not recommend running any scripts via a web browser. This library is made for command line usage.

The answer to your question is to enable error reporting on the server via either php.ini, or via adding a command like this (if your PHP config allows the `ini_set()` command) to the top of the example scripts (above all other commands):

```php
<?php

ini_set("display_errors", 1);
```

It will work. Good luck.

**Comment by mgp25** [comment]
### [F.A.Q.](https://github.com/mgp25/Instagram-API/wiki/FAQ)

Read more about: [500 error related issues](https://github.com/mgp25/Instagram-API/search?q=500+error&type=Issues&utf8=%E2%9C%93)

**Comment by SteveJobzniak** [comment]
@mgp25 and Everyone:

I have added the above info to the wiki now. Please point everybody here instead in the future:

https://github.com/mgp25/Instagram-API/wiki/FAQ#what-does-the-500-http-error-code-mean

And it also explains why it's a really, really fucking bad idea to run these scripts via the browser. ;-)
