### ISSUE TITLE
Reupload Video with the same Thumbnail

### ISSUE THREAD

**Issue by hustlehero** [mgp25/Instagram-API#1598]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

### Question

Hey there,
is it possible to repost a Video with the exact same thumbnail? From the available code it wouldn't be possible, because ffmpeg creates the thumbnail at 00:00:01. So the thumbnail would be different. With the following snippet I'm able to get the thumbnail of the video as a jpg file. But I'm unable to use it, if I reupload the video, since the thumbnail is generated by ffmpeg.

```php
$var = $ig->media->getInfo(1616096057253913616);

	foreach($var->getItems() as $item){
		file_put_contents("Thumbnail.jpg",file_get_contents($item->getImageVersions2()->getCandidates()[0]->getUrl()));
	}
```
Any ideas or suggestions are appreciated. Thanks so much in advance!
Greetings from germany
Phil

**Comment by mgp25** [comment]
Hello @hustlehero,

you can tweak the API to upload videos with custom thumbnail, but we won't implement this feature since people could use it to hide the original content.

In case you want to tweak it at your side. You can use external metadata array as a helper for you. After the video is successfully uploaded, a thumbnail will be uploaded using the upload photo endpoint. Instead of calling ffmpeg you can use your own custom thumbnail.

If you have any question or doubt while doing, i'll be happy to answer you (email)

Regards
