### ISSUE TITLE
push notification for new message

### ISSUE THREAD

**Issue by aquarius1727** [mgp25/Instagram-API#1600]
hello guys i just need some help on getting a new message.. im not sure how can i do that...

i know they have this `pushReciever.php`
https://github.com/mgp25/Instagram-API/issues/1597

im having some trouble on running pushReciever on cli...
i was planning to just manually add it to cronjob every minute to check if there's a new dm...
is there any other way to get the new messages???

using `$resp = $ig->direct->getInbox();` i can get the number of unseen messages but cant see which messages are those

thank you guys...

**Comment by valga** [comment]
@aquarius1727 
1. You should not put Push/Realtime client into a crontab, because they are designed to run forever in background. Instead you should use some tool like [Supervisor](http://supervisord.org/) to ensure Push/Realtime persistence.
2. You can use [Child Process](https://github.com/reactphp/child-process) to run some custom script like `php messageCallback.php --threadId=%s --messageId=%s --jsonData=%s` or you can use [HttpClient](https://github.com/reactphp/http-client) to make HTTP requests to your callback URL. There are also asynchronous clients for MySQL, Redis, ... Just pick one that suits your needs or environment.

**Comment by aquarius1727** [comment]
hello @valga tnx for the information...
