### ISSUE TITLE
FBSearch / TopSearch has wrong parameters

### ISSUE THREAD

**Issue by mme76** [mgp25/Instagram-API#1608]
When clicking the Lens/Search icon and searching for something in the "Top" tab (not People / Tags / Places), the official app (version 10.33.00, consistent with the current API) sends the following GET request:

https://i.instagram.com/api/v1/fbsearch/topsearch/?timezone_offset=-14400&count=30&query=c&context=blended

While the current API code sends the rank_token, query and context parameters. We need to:

- remove rank_token
- add timezone_offset
- add count

Note that version 18.0.0.14.85 invokes a slightly different endpoint (topsearch_flat), but with the same paramenters:

`i.instagram.com/api/v1/fbsearch/topsearch_flat/?timezone_offset=-14400&count=30&query=c&context=blended`

For consistency, I suggest we fix the parameters. Thanks

**Comment by mgp25** [comment]
Hello @mme76,

thanks for reporting this. I'll verify this, and send a fix. (Will be done in a couple of hours)

Regards

**Comment by mgp25** [comment]
Added: https://github.com/mgp25/Instagram-API/commit/283bc5e90fc08f66add409160824c08805a50360

I also added other optional params.

Regards

**Comment by mme76** [comment]
@mgp25, the endpoint topsearch_flat is only for version 18, the
current one uses topsearch. I think we should keep everything
consistent.

**Comment by mgp25** [comment]
@mme76 we'll be updating the whole lib to newer versions soon, this changes only affect to `dev-master` code, so regular users will still be using latest release which was some weeks ago.

Major changes will come in the next few days 😄

**Comment by SteveJobzniak** [comment]
@mme76 If you're using `dev-master`, you're going to notice our brand new JSON backend. It leads to around 80% memory usage reduction compared to previous versions and offers tons of new features for debugging and data output. Check out https://github.com/mgp25/Instagram-API/blob/master/examples/accessingValues.php for some of those new features. ;-)

It'll be part of v4.0 (the "major changes" mgp talked about above), because the new changes are not backwards-compatible with people who have been writing their properties as `$item->some_thing`. We now _require_ the correct `$item->getSomeThing()` format, which was done to ensure that all users properly run our custom functions (which do important work) rather than bypassing them.

**Comment by mme76** [comment]
Excellent!
