### ISSUE TITLE
No response from server, connection or configure error

### ISSUE THREAD

**Issue by cyxen** [mgp25/Instagram-API#1613]
Hi,
Today there was an error "No response from server, connection or configure error".
what happened?

**Comment by aitte2** [comment]
Sometimes Instagram's server is down or refusing requests briefly. I sometimes get this problem too. It works again 30-60 minutes later. I don't know why. I do nothing bad that would make me flag. Maybe their server is down.

**Comment by joseflorido** [comment]
It seems that there is a temporary problem on their side.

**Comment by mgp25** [comment]
Not API issue.

Regards

**Comment by aitte2** [comment]
Funny that you guys mentioned this today. I just noticed that it happened a lot for the last 2 hours today. But now it's fine again.

I think this is not a "temp-ban" at all. It must be some kind of overload on their server that fails to handles our requests.

Because this is what it looks like:

- fail, fail, fail.... faaaaaail...
- suddenly works... then a few requests later... fail... fail... fail...
- fail... fail... faaaaaaail...
- 30-120 minutes later: Works perfectly again... And keeps working for weeks!

So I seriously think it's not something we are causing. It's just some kinda overload of Instagram servers that makes them drop connections to everyone (not just us 3rd party library users).

**Comment by rudemex** [comment]
Hi guys, today the office community managers reported that instagram and facebook were not functioning normally.
That's probably the problem.

Greetings.

**Comment by aitte2** [comment]
@rudemex Thanks for confirming that it happened to everyone. :) 👍

**Comment by AliKhaleghi** [comment]
There's something else though, well I've been using this library for multiple users, but for a user which i used the most, this error happens almost all the time, but for the rest of the accounts, server response is valid and as expected.
_Just sharing my experience about this, I have no idea what the problem is ( although i have been misusing the __API__ for the user which gets this error, that might be it )._

Cheers.

**Comment by SteveJobzniak** [comment]
@Alfredao `although i have been misusing the API for the user which gets this error, that might be it`

Yes that is it. Instagram gives empty replies (closes connect?) when they hate you.

I have seen this while testing the `Hashtag::search()` function:

https://github.com/mgp25/Instagram-API/blob/cef2679a315ae049277b27fe7819cc94f2ab3d08/src/Request/Hashtag.php#L73-L81

Thanks for adding the extra info to this thread. Now we know that Instagram will actually manually give empty replies for your account if they dislike it in general.

**Comment by Alfredao** [comment]
Hi @SteveJobzniak, shouldn't you have mentioned @AliKhaleghi?

**Comment by SteveJobzniak** [comment]
@Alfredao Oops. I wonder why it autocompleted your name since you weren't in this thread.

I meant @AliKhaleghi. ;-P
