### ISSUE TITLE
Error: Virtual property access is disabled for class...

### ISSUE THREAD

**Issue by hosberd** [mgp25/Instagram-API#1623]
I updated the library and get this error: "Virtual property access is disabled for class "\InstagramAPI\Response\UserInfoResponse"
Commit: "70f3422Response/Model/CarouselMedia: Add new property".

Before update I didn`t get this error. What may be a problem?

**Comment by SteveJobzniak** [comment]
Hi. You are using the `dev-master` (which is v4.x in-development). We have recently swapped the underlying JSON mapper to my new, super efficient and powerful [LazyJsonMapper](https://github.com/SteveJobzniak/LazyJsonMapper) library instead. It's a superb upgrade which really makes our JSON mapping perfect for the first time ever.

With that upgrade, we also got the new ability to choose _how_ people can access properties on the JSON objects. LazyJsonMapper supports properties (`$x->some->thing`) and functions (`$x->getSome()->getThing()`), and it lets projects configure which styles to allow (either, both, or neither).

A huge problem on `Instagram-API` in the past has been all the users using the `$x->some->thing` style which is ugly and bypasses all of our custom code (for example, `$x->message` can get invalid values, whereas our `$x->getMessage()` is coded to convert those invalid values to valid ones so that the message is always correct).

Thanks to LazyJsonMapper, we were finally able to solve that. From now on, people _must_ use functions for accessing properties. There is no other way to access JSON properties in `Instagram-API` from now on.

The `accessingValues.php` example has been updated to show several of the kickass new features that LazyJsonMapper provides you (the user) with. Such as `printJson()` and `printPropertyDescriptions()`.

https://github.com/mgp25/Instagram-API/blob/master/examples/accessingValues.php

Good luck with your upgrade/rewrite.

**Comment by hosberd** [comment]
@SteveJobzniak :))) Cool! Thanks.

**Comment by smileytechguy** [comment]
@SteveJobzniak If you don't mind me asking, why not use magic methods for backwards compatibility?  With `__get` http://php.net/manual/en/language.oop5.overloading.php#object.get and all you could make it so `->name` would actually return `->getName()`.
