### ISSUE TITLE
Suggest refactoring

### ISSUE THREAD

**Issue by ruscon** [mgp25/Instagram-API#163]
I suggest some changes:
- [ ] 1. Add method for checking success login only (without calling other api methods)
- [ ] 2. Feature for changing user account (need for posting by different users)
- [ ] 3. May be https://github.com/PHP-FFMpeg/PHP-FFMpeg ?
- [ ] 4. Add some dependence exceptions, if they not found (ffmpeg and other)
- [ ] 5. Code style
- [ ] 6. Feature curl proxy

Can help with this

**Questions:**
1. why php 5.6 ?

**Comment by mgp25** [comment]
@ruscon 

1. and 2.: Oks, seems good
3. I dont want to rely in other php libs yet, thats why the ffmpeg extension. Maybe when its more stable we can try to do something with it
4. Yes, some exceptions are required
5. code style its always appreciate but using standards as possible.

Questions:
1. why php 5.6 ?

Answer:
All the tests i do is in php 5.6, so i prefer users to use the same version, i know other version may work fine too, but since i havent tried other versions, is just to make sure

**Comment by ruscon** [comment]
Library did't use any php 5.6 dependence
I think we can set 5.4 or .5.5

Can u fix answer numbers ? 
I don't understand about №2 
> 2.: Oks, seems good
ok
> 2. I dont want to rely in other ...
№3 ?
> 3. Yes, some exceptions are required
№4 ?

...

**Comment by mgp25** [comment]
@ruscon 

1. Yes, its a good idea
2. Yup, its just changing a few things
3. Since i dont want to rely in other php libs i used the extension, anyway ill test that in the future
4. Yes, some exception are required to be added
5. Code style is always good, but following standards
6. Sorry, i dont want to support this features since many spammers use this to login with different IP

**Question**
 1. why php 5.6 ?

**Answer**
As i told you in the above comment, you can use any other version, 5.4, 5.5 there is no problem in that, but since most of the users using this API are unexperienced i set that version so everyone have the same and doesnt experience other errors, but yes, you can use any othre verssion

**Comment by ruscon** [comment]
> 6. Sorry, i dont want to support this features since many spammers use this to login with different IP
Bad :(
I;m not a spammer, but i need this functional

**Comment by mkanker** [comment]
@ruscon in what situation do you need the proxy?

**Comment by ruscon** [comment]
i want hide my ip - standard reason :)

**Comment by mkanker** [comment]
why?

**Comment by Stepkaa** [comment]
Actually, using search users by emails and phone numbers is quite an interesting thing, and proxy will be a great help here

**Comment by mgp25** [comment]
If you want any proxy stuff code it yourself in your code not here, i not want to support any kind of bulk requesting or similar oks?

And for the rest of the features, send pull request, ill review them and if its okay i'll merge them

Regards
