### ISSUE TITLE
Wrong parameters and compression method for Internal::sendClientEventLogs

### ISSUE THREAD

**Issue by szokeptr** [mgp25/Instagram-API#1634]
I just noticed that the Internal::sendClientEventLogs method has the wrong parameters and compression method. As far as I can see in the captured requests, the data is a gzdeflate-ed json string, without being base64 encoded (that's probably coming from your capturing software).
Also the parameters seems to be:
- access_token
- format=json
- cmsg=compressed data
- sent_type=timestamp of request
- cmethod=deflate

I can send a pull request if you confirm that my findings are correct.

**Comment by SteveJobzniak** [comment]
Hi. A few days ago I got a notification that you starred my LazyJsonMapper project. I thought "there's an intelligent person!". 🤣 

I was right. You're very intelligent to have found this `sendClientEventLogs` function and to analyze it.

But...

1. Are you capturing iOS or Android? Only android is valid. The two platforms differ.
2. The current code was extracted from Instagram's source code. It was correct 6 months ago although they may have changed it.
3. We never finished the feature. Many times I've thought about deleting `Internal::sendClientEventLogs` and `Constants::GRAPH_URL`. Because we're not going to add the feature. It's used internally by the app to log all kinds of data about what you are doing in the app, and then periodically send it to Instagram to prove that you're a real client. First of all, implementing it would be an insane amount of work (all functions in the entire library would have to start doing logging). Second of all, it's part of Instagram's antispam which we don't want to break.

So I think I'll delete that function actually...

**Comment by SteveJobzniak** [comment]
Okay I just searched through the commit/git blame history and found the answer: The function was added in June and then never touched since we're never going to rewrite the library to emulate their app logging (that would waste years of our time, would put us at war with Instagram and would only benefit spammers). I am going to delete it now.

**Comment by valga** [comment]
@SteveJobzniak I don't think that having this endpoint will hurt us. Do you remember we had Push endpoints event without Push clients?

Also, its params were wrong from the beginning, I already pointed at it.

**Comment by szokeptr** [comment]
I think it would be still useful to keep this enpoint with the correct parameters around, so those who are interested can send the events.
We would still have to figure out the event data ourselves, but at least there would be a method for sending them - I see no harm in that.

**Comment by SteveJobzniak** [comment]
@valga This is different. Here are the deletion-reasons I wrote in the commit message:

1. Nothing calls this code.
2. Its endpoint parameters are already outdated and are totally
   pointless maintenance work for no benefit.
3. We are never going to implement Graph-logging, which is what this
   function is for. Because it would require proper analytics code in
   the hundreds of functions in this library, which would take years of
   our time, would put us at war with Instagram, and would only benefit
   spammers (since this Graph system is part of IG's antispam). And if
   we tried to implement it, Instagram may decide to finally block all
   3rd party APIs forever. It's not a battle worth starting!
4. It's not even worth keeping "just in case a user wants it". Because
   NO legitimate user has the capacity to implement this feature
   correctly themselves. So the code is totally useless.
5. If someone wants to call it in their own project, then they have a
   specific reason and CAN do it themselves via `$ig->request()` to
   create their own manual API call. We're not going to do it FOR THEM.

@szokeptr That's the whole thing... "Figure out the event data ourselves" is impossible for you. As I wrote above: "NO user has the capacity to implement this correctly themselves".

Here's an example analytics log from the real app:

https://github.com/mgp25/Instagram-API/files/1164055/analyticsJsonData.txt
```json
	{
		"module":"media_capture",
		"name":"navigation",
		"time":1499050439.248835,
		"extra":{
			"dest_module":"media_capture",
			"pk":"1521863944",
			"source_module":"media_capture",
			"nav_depth":0,
			"radio_type":"wifi-none"
		}
	},
	{
		"module":"app",
		"name":"step",
		"time":1499050443.01275,
		"extra":{
			"waterfall_id":"853dd92995d94555b5db5a1b0bb404ea",
			"num_forward":2,
			"start":1499050438.428947,
			"entry_point":"last_selected",
			"num_backward":0,
			"total_seconds":4.583921909332275,
			"radio_type":"wifi-none",
			"direction":1,
			"step":"photo_edit",
			"pk":"1521863944"
		}
	},
	{
		"module":"app",
		"name":"step",
		"time":1499050443.037138,
		"extra":{
			"waterfall_id":"853dd92995d94555b5db5a1b0bb404ea",
			"num_forward":2,
			"start":1499050438.428947,
			"entry_point":"last_selected",
			"num_backward":0,
			"total_seconds":4.608215093612671,
			"mode":"filters",
			"radio_type":"wifi-none",
			"step":"edit_mode_selected",
			"pk":"1521863944"
		}
	},
	{
		"module":"media_capture",
		"name":"navigation",
		"time":1499050443.559913,
		"extra":{
			"dest_module":"photo_edit",
			"pk":"1521863944",
			"source_module":"media_capture",
			"nav_depth":0,
			"radio_type":"wifi-none"
		}
	},{
		"module":"media_broadcast_share",
		"name":"navigation",
		"time":1499050445.428248,
		"extra":{
			"dest_module":"media_broadcast_share",
			"pk":"1521863944",
			"source_module":"media_broadcast_share",
			"nav_depth":0,
			"radio_type":"wifi-none"
		}
	},{
	"module":"app",
	"name":"step",
	"time":1499050445.507263,
	"extra":{
		"media_type":0,
		"profile_photo_share_into_feed":0,
		"step":"upload_photo_attempt",
		"num_forward":3,
		"target":"UPLOADED",
		"radio_type":"wifi-none",
		"share_type":0,
		"dimension_height":1080,
		"is_direct":0,
		"failed_configures":0,
		"waterfall_id":"853dd92995d94555b5db5a1b0bb404ea",
		"entry_point":"last_selected",
		"num_backward":0,
		"upload_step_count":1,
		"connection":"WiFi",
		"upload_id":"1499050444",
		"failed_uploads":0,
		"to":"NOT_UPLOADED",
		"cancel_count":0,
		"dimension":1080,
		"from":"NOT_UPLOADED",
		"pk":"1521863944",
		"start":1499050438.428947,
		"total_seconds":7.078346967697144
	}
	},{
		"module":"app",
		"name":"step",
		"time":1499050447.054887,
		"extra":{
			"media_type":0,
			"profile_photo_share_into_feed":0,
			"total_size":157375,
			"step":"upload_photo_success",
			"num_forward":3,
			"target":"UPLOADED",
			"radio_type":"wifi-none",
			"share_type":0,
			"is_direct":0,
			"failed_configures":0,
			"waterfall_id":"853dd92995d94555b5db5a1b0bb404ea",
			"entry_point":"last_selected",
			"num_backward":0,
			"upload_step_count":1,
			"connection":"WiFi",
			"upload_id":"1499050444",
			"failed_uploads":0,
			"to":"UPLOADED",
			"cancel_count":0,
			"from":"NOT_UPLOADED",
			"pk":"1521863944",
			"start":1499050438.428947,
			"total_seconds":8.625967979431152
		}
	},{
		"module":"app",
		"name":"share_media",
		"time":1499050458.657773,
		"extra":{
			"share_later":false,
			"pk":"1521863944",
			"share_tumblr":false,
			"share_facebook":false,
			"share_twitter":false,
			"radio_type":"wifi-none"
		}
	},{
		"module":"app",
		"name":"step",
		"time":1499050458.71738,
		"extra":{
			"media_type":0,
			"profile_photo_share_into_feed":0,
			"step":"post_action_share",
			"num_forward":3,"target":"CONFIGURED",
			"radio_type":"wifi-none",
			"share_type":0,
			"is_direct":0,
			"failed_configures":0,
			"waterfall_id":"853dd92995d94555b5db5a1b0bb404ea",
			"entry_point":
			"last_selected",
			"num_backward":0,
			"connection":"WiFi",
			"upload_id":"1499050444",
			"failed_uploads":0,
			"cancel_count":0,
			"from":"UPLOADED",
			"pk":"1521863944",
			"start":1499050438.428947,
			"total_seconds":20.28848314285278
		}
	},{
		"module":"app",
		"name":"step",
		"time":1499050458.717753,
		"extra":{
			"media_type":0,
			"profile_photo_share_into_feed":0,
			"step":"configure_media_attempt",
			"num_forward":3,
			"target":"CONFIGURED",
			"radio_type":"wifi-none",
			"share_type":0,
			"is_direct":0,
			"failed_configures":0,
			"waterfall_id":"853dd92995d94555b5db5a1b0bb404ea",
			"entry_point":"last_selected",
			"num_backward":0,
			"upload_step_count":1,
			"connection":"WiFi",
			"upload_id":"1499050444",
			"failed_uploads":0,
			"to":"UPLOADED",
			"cancel_count":0,
			"from":"UPLOADED",
			"pk":"1521863944",
			"start":1499050438.428947,
			"total_seconds":20.28883004188538
		}
	},{
		"module":"app",
		"name":"step",
		"time":1499050458.806491,
		"extra":{
			"start":1499050438.428947,
			"total_seconds":20.37757015228271,
			"share_destination_toggle":false,
			"next_step":"post_attempt",
			"entry_point":"last_selected",
			"caption_toggle":true,
			"add_location_toggle":false,
			"waterfall_id":"853dd92995d94555b5db5a1b0bb404ea",
			"num_forward":3,
			"step":"share_screen",
			"m_t":1,
			"preview_toggle":false,
			"waterfall_type":"ig_creation_flow",
			"tag_toggle":false,
			"tag_people_toggle":false,
			"radio_type":"wifi-none",
			"num_backward":0,
			"pk":"1521863944"
		}
	},{
		"module":"app",
		"name":"step",
		"time":1499050458.806608,
		"extra":{
			"waterfall_id":"853dd92995d94555b5db5a1b0bb404ea",
			"num_forward":3,
			"start":1499050438.428947,
			"entry_point":"last_selected",
			"num_backward":0,
			"total_seconds":20.37767195701599,
			"m_t":1,
			"share_destination":"new_post",
			"radio_type":"wifi-none",
			"step":"post_attempt",
			"pk":"1521863944"
		}
	},{
		"module":"media_broadcast_share",
		"name":"navigation",
		"time":1499050459.247547,
		"extra":{
			"dest_module":"feed_timeline",
			"pk":"1521863944",
			"source_module":"media_broadcast_share",
			"nav_depth":0,
			"radio_type":"wifi-none"
		}
	},{
		"module":"app",
		"name":"step",
		"time":1499050460.154953,
		"extra":{
			"media_type":0,
			"profile_photo_share_into_feed":0,
			"step":"configure_complete",
			"num_forward":3,
			"target":"CONFIGURED",
			"radio_type":"wifi-none",
			"share_type":0,
			"is_direct":0,
			"failed_configures":0,
			"waterfall_id":"853dd92995d94555b5db5a1b0bb404ea",
			"entry_point":"last_selected",
			"num_backward":0,
			"time_since_configure_start":1.437366962432861,
			"upload_step_count":1,
			"connection":"WiFi",
			"upload_id":"1499050444",
			"failed_uploads":0,
			"to":"CONFIGURED",
			"cancel_count":0,
			"from":"UPLOADED",
			"pk":"1521863944",
			"start":1499050438.428947,
			"total_seconds":21.72602796554565
		}
	},{
		"module":"app",
		"name":"step",
		"time":1499050460.15515,
		"extra":{
			"media_type":0,
			"profile_photo_share_into_feed":0,
			"step":"configure_media_success",
			"num_forward":3,
			"target":"CONFIGURED",
			"radio_type":"wifi-none",
			"share_type":0,
			"is_direct":0,
			"failed_configures":0,
			"waterfall_id":"853dd92995d94555b5db5a1b0bb404ea",
			"entry_point":"last_selected",
			"num_backward":0,
			"upload_step_count":1,
			"connection":"WiFi",
			"upload_id":"1499050444",
			"failed_uploads":0,
			"to":"CONFIGURED",
			"cancel_count":0,
			"from":"UPLOADED",
			"post_duration_sec":1.438217043876648,
			"pk":"1521863944",
			"start":1499050438.428947,
			"time_since_last_user_interaction_sec":1.438217043876648,
			"total_seconds":21.72624897956848
		}
	},{
		"module":"feed_timeline",
		"name":"instagram_main_feed_refresh",
		"time":1499050461.623238,
		"extra":{
			"pk":"1521863944",
			"reason":"feed_item_posted",
			"status_code":"200",
			"radio_type":"wifi-none"
		}
	}
```

And if **A SINGLE THING** is wrong in that log, they detect you as fake.

This is literally part of Instagram's antispam and it uses heuristics like time-between-actions etc to determine if the log is real or not.

So no,  this endpoint is 100% harmful.

If some spammer wants to try implementing it, they're welcome to do it themselves via `$ig->request($endpoint)->etc...`.

It does not have to sit in the main codebase as dead code. Because we will never implement the analytics logging I just demonstrated above. If we even **TRY** to do it, Instagram would kill this project with a lawsuit and would block all 3rd party libraries (they can already block this library 100% right now if they want to, but they tolerate it because they can detect it and limit its spam-potential).

**Comment by szokeptr** [comment]
Thanks for taking the time to explain, I completely agree.
Also thanks for the incredible work you are doing, I am literally becoming a better programmer by just reading the code.

**Comment by SteveJobzniak** [comment]
@szokeptr Hehe, you're welcome. And thanks for the nice feedback. I am happy to hear the code is inspiring you. I hope to see contributions from you in the future, since you seem clever! :-) 👍
