### ISSUE TITLE
How to make sure receiving all push notifications without missing?

### ISSUE THREAD

**Issue by liudanking** [mgp25/Instagram-API#1635]
I am using pushReceiver to receive push notifications.

There is a requirement that I need to receive all pushes without missing (duplicated pushes are ok for me).

Assuming that this lib reliable (and it is ^_^) , the main case that causing push missing is restarting pushReceiver.

To achieve my goal, I have try following ideas:

1. Start multiple pushReceivers, when I need restart, I restart them one-by-one. It seems not perfect, but not so bad. Currently, the problem is that when I try to start second pushReceiver, the first one is kicked out 😂. How to run multiple pushReceivers on one host?

2. Start only one pushReceiver, when I complete a restart action, check inbox for missing messages. But after reading several issues about how to get unread messages for this lib, it seems we can't get unread messages through instagram private api.

Is there any ideas? Advices will be appreciated.

**Comment by SteveJobzniak** [comment]
Hi. You can run multiple pushReceivers for multiple _DIFFERENT_ accounts by running them all on the same EventLoop (`$loop`):

https://github.com/mgp25/Instagram-API/wiki/FAQ#is-it-possible-to-run-the-realtime-and-push-clients-in-a-single-script

You cannot run multiple receivers for a single account. Only 1 receiver per account works at a time. Because of the push token/device ID system, which means that only 1 of your receivers per-account will get messages from Instagram. And seriously we will not mess up the library code to somehow make more listeners per the same account, because that is not how push is supposed to work. 1 account/device = 1 device listener.

If you really want to, you can run a 2nd instance of the library with a DIFFERENT settings-storage, which means each user gets a different device + token in it. Just be aware that Instagram does not like multiple devices on the same account after a certain point, so be careful about too many devices.

As for seeing unread messages: You can read `$ig->direct->` various "get inbox" functions to look at new, incoming direct messages. You should have a local database (your own) which tracks which threads you have seen and their latest activity, so that YOU can detect the difference ("new messages!").

There's also a "getrecentactivityinbox" function which is the little "heart" icon in the app which is a tab that shows people liking your posts etc. You should read that one. But we also read it during the `login()` flow which may clear its info by the time you read it.

**Comment by liudanking** [comment]
Detailed and clear!
I will try to dive into my second idea with you suggestion.

**Comment by SteveJobzniak** [comment]
@liudanking Good luck. First try the `$ig->people->getRecentActivityInbox();` and `$ig->direct->` (various inbox) functions. Hopefully those give you all info you need.

If you finally decide that you truly want 2 push listeners, you can use the settings-storage method I mentioned, so that you literally register 2 different devices.

**Comment by SteveJobzniak** [comment]
@liudanking Btw, I think `getRecentActivityInbox` WILL work for you. Because I just remembered more about that annoying user in the past who kept talking about it (the threads you have seen)... He didn't have a problem with getting recent activities from it. He was annoyed that our library kept clearing the heart-icon in his personal phone's Instagram app (the heart icon showing recent activities), since our library calls recent activities during login. Which... who cares....

So I think you can do this:

- When you come back after a push receiver session, read the `getRecentActivityInbox` to see what people have liked your photos, followed you recently, etc. Just use some kinda timestamp to know what events are new and which are old.
- Also read the direct inboxes to look for new messages.

That should cover everything, I hope. Have fun!

**Comment by liudanking** [comment]
@SteveJobzniak I am just reading the issue by the guy you mentioned 😅 , you saved my time again.

**Comment by SteveJobzniak** [comment]
@liudanking 🤣

**Comment by SteveJobzniak** [comment]
@liudanking Ok I just tried it... lol, my `getRecentActivityInbox` has activities all the way back until June 2017... People who started following me, liked my stuff, mentioned me in comments, etc, are all in there...

Your problem is now solved. :-D

**Comment by liudanking** [comment]
@SteveJobzniak I think I should call you The Flash just like NBA Wade if you don't care 😁

I also need check `direct` APIs to get direct messages.  `getRecentActivityInbox` did not provide direct messages.

**Comment by SteveJobzniak** [comment]
Haha. 😄 

And yes, you will need to read the Direct inbixes separately as I said. You can see how we call them in `src/Instagram.php`, there are different kinds of inboxes. Good luck. Seems like you are having fun.

- The Flash

**Comment by valga** [comment]
@liudanking You don't have to do anything special to no miss pushes, because they have been made for phones. You phone can run out of coverage or battery, or you can just restart it. But you will receive queued pushes after going back to online. It happens because FBNS knows whether you received push message or not, and it retries the delivery after reconnection.

**Comment by liudanking** [comment]
@valga I did some tests, and it seems that you are right 😂
@SteveJobzniak Sorry, I think I have provided a stupid question which cost your time...

**Comment by valga** [comment]
@liudanking As for Direct messages, they have [Iris](https://code.facebook.com/posts/820258981365363/building-mobile-first-infrastructure-for-messenger/) for receiving offline messages. Just [search for 'seq'](https://github.com/mgp25/Instagram-API/search?utf8=✓&q=seq&type=) in the source code. But take in mind that queue length is somewhat limited.

**Comment by SteveJobzniak** [comment]
Haha. Nice final solution! I would never have guessed that their Push system queues, since my real phone misses pushes from Instagram all the time.

Does it also queue if multiple devices are registered to push and one of them is offline but one is online to get the push?

**Comment by liudanking** [comment]
@SteveJobzniak From my limited tests, Yes.

**Comment by SteveJobzniak** [comment]
Cool! 👍 😸
