### ISSUE TITLE
Unknown Function : getFullResponse

### ISSUE THREAD

**Issue by muratpolat** [mgp25/Instagram-API#1647]
Hello,

I can not use the getFullResponse method after updating repo. What do I have to do to get the json output?

```php
$feed = $ig->people->getInfoById($ig->people->getUserIdForName(''));
```

```xml
Exception : {"error":true,"error-message":"Unknown function \"getFullResponse\"."}
```

**Comment by mgp25** [comment]
Hello @muratpolat,

You are using `dev-master` and there were a lot of changes lately, `getFullResponse()` was removed.

You can use `->printJson()` function instead. The API is using [LazyJsonMapper](https://github.com/SteveJobzniak/LazyJsonMapper) from @SteveJobzniak. You can see an example here: 

- [Example](https://github.com/SteveJobzniak/LazyJsonMapper/blob/master/examples/basic_example.php#L80)

Regards

**Comment by SteveJobzniak** [comment]
I'll copy-paste this about `getFullResponse()` from another ticket:

Its only purpose was to read undefined properties that did not exist in the core Response/Model objects. But reading such properties is now supported natively in v4.x (the dev-master tree) thanks to my new LazyJsonMapper library. If you go [to its official page](https://github.com/SteveJobzniak/LazyJsonMapper), and [check out this ticket](https://github.com/mgp25/Instagram-API/issues/1623) where I gave users some tips, then you can learn more about it and what it will offer you.

If you were going to use that feature, the new way to read "non-existent" properties is this:

- Imagine that the property name is `some_property`.
- You can access it via its automatic LazyJsonMapper functions: `hasSomeProperty()`, `isSomeProperty()`, `getSomeProperty()`, `setSomeProperty()` and `unsetSomeProperty()`.
- To learn about those functions, you don't have to memorize their names. You can just use `$response->printPropertyDescriptions()`, which runs with default options "show functions, do not allow relative types, do not show undefined properties".
- To do the same listing, but include undefined proproperties that only exist in the data, use `$response->printPropertyDescriptions(true, false, true)`. (Functions on, relative off, undefined on). (Undefined is the last argument because it's such a rarely-used one.)
- Now that you have the function name, you should realize something... If you simply call `getSomeProperty()` as if it was a regular, fully defined property, then it _will_ work _if_ the property exists in the current object's data, but it will throw an exception if it doesn't exist. Because unmapped (undefined) properties will warn in that case. So that's dangerous.
- There's a special function for that purpose: `hasSomeProperty()`. It never throws exceptions. And it returns TRUE if the property either exists in the JSON data and/or has a full definition. If it returns TRUE, the property is safe to access.

So here's your code for reading `some_property`:

- Old code: `if ($x->getFullResponse()->some_property()) { ... }`

- New code: `if ($x->hasSomeProperty() && $x->isSomeProperty()) { ... }`

Assuming it's a flag, you can and should use `isX` like above to check if it's a "true"-like value; otherwise just use `getX` as usual if you want to actually get its value.

**Comment by SteveJobzniak** [comment]
@mgp25 The comment I gave above should probably be linked from the release notes later, since people will need to know that stuff while upgrading. ;-)

**Comment by findandreplace** [comment]
@SteveJobzniak Well , i test to see if one of my users sending spam , by doing 
`$response->hasSpam() && $response->isSpam()
`But its not work 
`PHP Fatal error:  Call to undefined method InstagramAPI\Exception\FeedbackRequiredException::hasSpam() `

**Comment by kriskras** [comment]
I added "use LazyJsonMapper\LazyJsonMapper;" at the top of my file, but I am getting "Something went wrong: Unknown function printJson.". Any idea what could be causing this? Thanks in advance.
