### ISSUE TITLE
instagram php object serialization  

### ISSUE THREAD

**Issue by findandreplace** [mgp25/Instagram-API#1662]
Dear all , i know that this post may **[ not Related ]** but what can i do , even google has now clear answer :)
I need to save instagram object to use it in other php page in order to avoid login(), it is just a refresh page to another , so session quite new .
i tested php serialization  method but it seems corrupt the object all together. since the object is quite complex .

What is your advice to save instagram object in order to reuse it right a way on other php page .

Regards

**Comment by pankif** [comment]
https://github.com/mgp25/Instagram-API/wiki#login

**Comment by SteveJobzniak** [comment]
@findandreplace You cannot do that. Instagram will ban you. Literally ban you. If you don't call `login()` every time.

First, they start silently disabling features so that APIs stop working.

Finally they ban you.

https://github.com/mgp25/Instagram-API/blob/ceccaf812696821fe05e9a56d73f73f5effff7f3/src/Instagram.php#L370-L373

https://github.com/mgp25/Instagram-API/blob/ceccaf812696821fe05e9a56d73f73f5effff7f3/src/Instagram.php#L758-L776

**Comment by SteveJobzniak** [comment]
The only thing that can be serialized are response objects: Everything in `src/Response/`.

**Comment by findandreplace** [comment]
@pankif Thank you for your reply , well i know this tip , and as i already said i dont want to call login each time i refresh the page. 

@SteveJobzniak 
I know that and trust me i do search before asking , so i come on all of these wonderful comments , But what i am saying which it seems inapplicable. 
If i have php page show some information to the browser , hit refresh , this will login and call time line..

So as i understand ... do login and drink my cup of tea :)

**Comment by SteveJobzniak** [comment]
Also you speak about some other very bad idea:

`I need to save instagram object to use it in other php page in order to avoid login()`

You're using this library directly on .php pages? That can lead to all kinds of very dangerous corruption, half-called APIs, etc.

Because .php scripts are killed instantly when the user closes a web tab or presses "Stop loading page".

So they can get interrupted in the middle of writing to disk, or in the middle of sending requests to Instagram, etc.

See this FAQ entry where we warn against using this library on webpages:
https://github.com/mgp25/Instagram-API/wiki/FAQ#what-does-the-500-http-error-code-mean

This library is not a webpage! It is an Instagram for Android application emulator. It emulates an application. Not a webpage. You cannot just randomly kill this library in the middle of work!

**Comment by SteveJobzniak** [comment]
If you use this online we recommend a database or JSON system.

Where you have a permanent process connected to Instagram, which either writes data to a database that your website displays. Or which your website script calls via `JSON` local calls to get data from it. You can look at `examples/realtimeHttp` for a way to write a "local server" that can be adapted to make a permanent library process that can do various API calls and return JSON to your main webpage .php script.

**Comment by SteveJobzniak** [comment]
I wrote an expanded FAQ about this situation and put it at the top of the FAQ. It's probably no new info for you now but it will help future users :) https://github.com/mgp25/Instagram-API/wiki/FAQ#can-i-run-this-library-via-a-website

**Comment by BaderAlmudarra** [comment]
Login() is not necessarily to be called in each page.

Suppose that I have a file named searchPostsByTag.php

which will return the results as Json format.

and I have a client that will Like() some posts in the above output via another file Like.php, I believe I should like the posts without login since I already logged in before the search results. Note that Login() will always get the timeline feed, so why I should retrieve the timeline after searching?

**Comment by SteveJobzniak** [comment]
@BaderAlmudarra The answer for your question is here: https://github.com/mgp25/Instagram-API/wiki/FAQ#can-i-run-this-library-via-a-website

**Comment by SteveJobzniak** [comment]
We really should (and could easily) make this library impossible to run on a website. Because using it in a .php file on a website is a total misuse of the design of the Instagram Android application (which this library emulates). It can corrupt data, it can break API calls, it leads to slow `login()` on every page load, etc.

The only reason we haven't blocked website usage is because dumb people would go nuts about it since they _want_ the "easy" solution of just "running/re-starting the Instagram Android app emulator inside their page script on every page load".

We will never give support with that kind of bad setup. The answer to a proper setup is in the FAQ I linked.

**Comment by SteveJobzniak** [comment]
PS: This thread and many others like it in the past has inspired me, and I will add a change which disables website usage in this library by default, which users can re-enable manually via a flag, AT THEIR OWN RISK. That way, everyone who wants to risk it can do so at their own risk.

**Comment by BaderAlmudarra** [comment]
@SteveJobzniak  I use this library from the command line not on a website. This FYI

**Comment by SteveJobzniak** [comment]
@BaderAlmudarra You just said something else here though:
https://github.com/mgp25/Instagram-API/issues/1662#issuecomment-340213464

>Login() is not necessarily to be called in each **page**.

>Suppose that I have a file named **searchPostsByTag.php**

>which will return the results as Json format.

>and I have a client that will Like() some posts in the above output via another file **Like.php**, I believe I should like the posts without login since I already logged in before the search results. Note that Login() will always get the timeline feed, so why I should retrieve the timeline after searching?

If you're truly using it from the command line, then why all your examples about .php files and "pages"?

Your design above should be redone like this:

`php core.php` = permanent 24/7 process, listens to localhost on a port.

website scripts = connects to localhost on the port and talks to your app emulator PHP process, and asks it to do stuff, all within that single session without any need for login() calls.

You also need something else: Periodically call `login()` inside your 24/7 PHP process. Otherwise it will get banned/limited by Instagram due to never calling login.

**Comment by SteveJobzniak** [comment]
Okay, the new flag has been enabled, with the following warning:

https://github.com/mgp25/Instagram-API/commit/95b086d8a053b3f22ed5c53033478f3278fc06f1

https://github.com/mgp25/Instagram-API/commit/b8a6398dbb13e5612a1de62f1fb7f8983c3edbc9

When you upgrade you will see the message. And after reading it, you can choose if you want to re-enable direct web embedding of the app emulator library at your own risk. There's a flag that restores old operation. You're welcome to do anything you want to, as long as you're aware that you _can_ cause data corruption by running it directly in a webpage.

**Comment by SteveJobzniak** [comment]
Okay, the new flag has been enabled, with the following warning:

https://github.com/mgp25/Instagram-API/commit/95b086d8a053b3f22ed5c53033478f3278fc06f1

https://github.com/mgp25/Instagram-API/commit/b8a6398dbb13e5612a1de62f1fb7f8983c3edbc9

When you upgrade you will see the message. And after reading it, you can choose if you want to re-enable direct web embedding of the app emulator library at your own risk. There's a flag that restores old operation. You're welcome to do anything you want to, as long as you're aware that you _can_ cause data corruption by running it directly in a webpage.

![message](https://user-images.githubusercontent.com/22373193/32144611-a60b48f4-bcbb-11e7-916d-dcb223b2432c.png)

**Comment by findandreplace** [comment]
@SteveJobzniak 
Well it is not clear how to use this new method You said put that line before the object creation:
```
 
<?php 

require __DIR__.'/../vendor/autoload.php';

\InstagramAPI\Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
try {
    $ig->login($username, $password);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}

?>
```

Well this is what normal user understand ! and this return an error , please make a small page in the example folder clarify howTo
