### ISSUE TITLE
UnlinkAddressBook / linkAddressBook

### ISSUE THREAD

**Issue by TobiM93** [mgp25/Instagram-API#1665]
First of all a big thank you to @mgp25 and @SteveJobzniak for this awesome repo!

I used `$ig->people->linkAddressBook($contacts);` and everything works fine. Afterwards I wanted to "update" my AdressBook and used `$ig->people->unlinkAddressBook();` to reset and use `$ig->people->linkAddressBook($contacts);` again to fill with new contacts. My problem is after the 3rd time doing this there's always the same userdata as response. Did I miss anything or is this just a restriction from Insta?

**Comment by SteveJobzniak** [comment]
Hi. Since your first two attempts worked, my guess is that you're doing it too often. Instagram doesn't like people using the APIs more frequently than the real app would call them. I've never seen it "repeat" old values, though. Usually when they dislike the rate of queries, they'll just send empty responses or "Throttled" responses. But perhaps the address book API is different and simply keeps the last value.

Sorry, I have no more ideas than that.

**Comment by mgp25** [comment]
It has some backoff time, but i can research more about that.

Regards

**Comment by TobiM93** [comment]
`POST: https://i.instagram.com/api/v1/address_book/link/?include=extra_display_name,thumbnails DATA: contacts=[{"first_name":"Tom","phone_numbers":[""],"email_addresses":["Tom@web.de"]}] ← 200 317B RESPONSE: {"items": [{"user": {"pk": XXX, "username": "marc", "full_name": "marc", "is_private": true, "profile_pic_url": "XXX", "profile_pic_id": "XXX", "is_verified": false, "has_anonymous_profile_picture": false}, "caption": "", "large_urls": [], "thumbnail_urls": []}], "status": "ok"} `

This is the debug Info I get, I check for Tom's account but always get marc as result. If I do it the first 3 times always with 2-3min between each request it works. After the 3rd time it always gives me the same response for marc.

Thank you for your fast reply and the support! And of course also big thank you to @valga  👍

**Comment by SteveJobzniak** [comment]
@TobiM93 The linking function has been updated now by mgp25 to match the latest parameters:

https://github.com/mgp25/Instagram-API/commit/793841843c447780ba5cac981d9ec52fdb37ae77

It won't help with the query-cooldown limits you're seeing though.

You can research the cooldown and share the results with us here. It would be nice since we've shared our time with you by writing this library. ;-) And all we could do anyway is just link and unlink to try to see how long the cooldown is. You can research that process just as well as we can. There's no difference between what we do about that or you do about it.

So please, if you find the cooldown, share it with the community here and we will document it in the code. :-)

**Comment by lazyjohny500** [comment]
@TobiM93 Do you have any news about it?

**Comment by AlexByte** [comment]
After some time, instead of the previous answer was given an error.
>  400 88B RESPONSE: 
> ```
> {
> 	"message": "Sorry, we only allow one unique import per user per day",
> 	"status": "fail"
> }
> ```

**Comment by shirnejad** [comment]
> It has some backoff time, but i can research more about that.
> 
> Regards

Hi , 
I also care about the problem of my dear friend .
I use the latest version of your library
My problem is that I can not check the new contact and in fact `$ig->people->unlinkAddressBook()` it does not work and displays a repeat contact at any time.
Thank you for helping me because it is very important
This is my code. Thank you for advising
`
$username = 'xxxx';
$username = 'xxxx';
\InstagramAPI\Instagram::$allowDangerousWebUsageAtMyOwnRisk = true;
$ig = new \InstagramAPI\Instagram(true, false);
try {
    $ig->login($username, $password);
} catch (\Exception $e) {
    echo 'Something went wrong: ' . $e->getMessage() . "\n";
    exit(0);
}
try {
    $contacts = array(
        array(
            'first_name' => 'Contact1',
            'phone_numbers' => array('+98936xxxxx'),
            'email_addresses' => array('')
        )
    );
    $ig->people->unlinkAddressBook();
    $res = $ig->people->linkAddressBook($contacts);
    print_r($res);

} catch (\Exception $e) {
    echo 'Something went wrong: ' . $e->getMessage() . "\n";
}`

**Comment by JRoy** [comment]
We don support web usage

**Comment by shirnejad** [comment]
What should I do to solve this problem?
In principle, my question is that I have a number of phone numbers and I want to check if these numbers have an Instagram account and I can get the ID of each account.
Thank you for telling me how can I do this and thanks for introducing resources.
