### ISSUE TITLE
Why I can not do ForceLogin any more

### ISSUE THREAD

**Issue by findandreplace** [mgp25/Instagram-API#1667]
https://github.com/mgp25/Instagram-API/blob/b8a6398dbb13e5612a1de62f1fb7f8983c3edbc9/src/Instagram.php#L470

It seems you removed ForceLogin ! why ?
If not , how can we do it !

**Comment by findandreplace** [comment]
Well i found a Workaround which i believe it is the official way to do it : 

`$ig->login($username, $password,1);   `

Since the third parm is `$appRefreshInterval` and by passing `1` or even `0` this will force API to refresh the session

**Comment by SteveJobzniak** [comment]
Hi! It was removed from public access because it was never supposed to be public. It's an internal library detail (the library uses it to force a re-login when the session is invalid/expired), and it is dangerous for users to `$forceLogin` manually:

https://github.com/mgp25/Instagram-API/commit/6be6daef14e283a491927a92c06ca0f80debcb4f

- This removes a harmful parameter which was never supposed to be
  public. Some people were abusing the `$forceLogin` parameter to force
  a full login even though they already had a valid session. That will
  confuse Instagram since their server can see the user's app session
  cookies and will see that the user is already logged in and has no
  reason to do the relogin call they're doing! So we are removing the
  public (harmful) access to `$forceLogin` abuse.

---

About `$appRefreshInterval`, it does something else: It does not force a login. Instead, it causes about 10-15 different APIs to be called, to do stuff like "get activity inbox, get direct inbox, get timeline, get story reel feed, etc". It emulates someone having closed the app and then opening the app again.

You can read its description of all `login()` parameters:

https://github.com/mgp25/Instagram-API/blob/27339789c7f78e8b87f8f512b0448813b90fd593/src/Instagram.php#L414-L428

**Comment by findandreplace** [comment]
>>Perhaps you were using forceLogin because you've made a user-website where people can login and you want to be sure that they are giving the right password?

Correct .

I need this to be sure this is a correct password , not session password ! so what is the correct official way to do this !

**Comment by SteveJobzniak** [comment]
@findandreplace There is no way to do it. Literally zero ways. This library emulates the Instagram android application.

After you are logged in to your Instagram app (on iPhone or Android), you are logged in forever. There is no button in the GUI to "check my password please". So we have no way to do it either, because there is no API for it.

What you _can_ do is store a random $salt:

```php
if ($salt already exists in database) {
    $salt = read from database;
} else {
    $salt = uniqid(mt_rand(), true); // generate a new salt
}
$hashed_password = sha1($salt.$password);
// now compare $hashed_password to a stored $hashed_password in database
// if it exists. if not exists, then put it in your database for next time.
```

But I have to warn you: I only told you this because I want your users to be safer.

You are till doing something **100% ILLEGAL**. You are essentially operating a password phishing website which is able to get people's Instagram passwords. That is very illegal. I hope for your sake that you only use it with a few friends who know that you can read their passwords.

For real official purposes you must use the OFFICIAL Instagram website API:
https://www.instagram.com/developer/

Which protects users by hiding the password from your site, and only giving your site a safe access token.

**Comment by SteveJobzniak** [comment]
One more thing: You're operating a website which means you're violating the license of this library, unless you contribute something back:

https://github.com/mgp25/Instagram-API#license

**Comment by findandreplace** [comment]
I am using this lib with my friends and family .
Ok i do understand your point of view, then can we just logout ! without delete user device ?

**Comment by mgp25** [comment]
`logout()`

**Comment by SteveJobzniak** [comment]
@findandreplace It's like this:

- `login()` with full login: Tells Instagram's server to create a new session. It does not kill the old session. So when people abused that flag manually, every `login()` call was creating a new session on Instagram's server. It could lead to your account being banned or limited, due to too many "simultaneous logins" (because each old session was still alive and stayed tracked on their server every time you created a new session).
- `logout()`: This tells Instagram's server to kill your current session. It means that next time you call `login()`, we will detect that you are logged out (no valid session) and will do a full login again which validates the password.

But again, be very careful about this. If you're running in the "dangerous web embedding mode" (that we recently added), then it means that every page load will `logout()` (first to clear the old session) and then `login()`. You'll essentially spam Instagram with requests to destroy and open new sessions every time they reload the webpage.

Okay... time to step back in time a bit:
- The reason why the "enable dangerous web mode at your own risk" flag was added is because of a lot of reasons, especially because those repeated requests to login/logout on every page load are very dangerous. I've _personally_ seen IPs getting flagged as "bad spammer" just because of constantly calling their login API and making new sessions (I was testing about 200 times with a test-account once). We do not want to let users do things not possible via the official API, which can hurt their accounts and IPs. That's why we've become stricter about preventing very harmful and dangerous misuse of the library.

You should think very closely about what you are doing with the library, because as the new warning says: This library is not a website. It is an Instagram application emulator. An application has a lifetime: It is opened, it logs in/resumes session, and then it stays alive forever until the user presses their Home button.

A real application does NOT constantly login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and login and logout and ...

Hopefully you see the point of why Instagram may ban/limit you after you do that...

The proper way to use this library online is described in the warning message, which can be read manually by opening `/webwarning.htm` in our repository in a web browser.

**Comment by SteveJobzniak** [comment]
Here's the proper design for your site, since you want users to be unable to login without real passwords:

- Have a `core.php` that runs a PHP-webserver and listens to localhost connections.
- That `core.php` should have URLs for commands such as `/login?username=...&password=...&sessionKey=...`.
- When it receives the login command, core does the following: If that username is already logged in, verify that the sessionKey is correct. If it's not already logged in, create a new `Instagram()` object for that username and generate a sessionKey (and keep it stored in memory in core.php), and try the login/logout/whatever calls...
- If the sessionKey matched an existing session for that username, or if the new login succeeded, then store the `Instagram()` object for that user in an array in core.php, and return a reply with some kind of "OK".

Now you have a core which can: Take commands to login or continue using a living session, and which validates that the session key is valid.

Next, your main website should change to this:

- The web scripts should connect to the core's localhost webserver, and do something like: `http://localhost:8100/login?username=...&password=...&sessionKey=<get this value from a $_COOKIES storage from the user's browser!>`.
- If the user successfully logs in, set the sessionKey cookie in their browser. That way, all future calls to the `/login` API will detect that they have permission to use that session.

That's it... Now you're ready to send authenticated commands to your local application process (core.php):

- To do something like "get timeline feed", you would have a function like `/get_timeline?username=...&sessionKey=<from cookies>&userid=<id>`, and that API in core.php would in turn do this:
- First, validate that the username has a current session in memory, and then check if the sessionKey is right (that way you know it is allowed to use the session).
- Then perform the API call on that object, such as `$this->_sessions[$username]->timeline->getUserFeed($userId)`, and you can then return the result to your main web script in any format you want, such as JSON, or as `serialize($response)`, etc. I would probably prefer the serialize-method because that way your local `core.php` returns full objects that the website can use almot as if the library ran inside the web script.

This setup is correct. Tedious? Eh who cares. It is the correct way to avoid Instagram banning, limiting, data corruption, partially called APIs, etc.

**Comment by mgp25** [comment]
@SteveJobzniak gitter

**Comment by findandreplace** [comment]
We do logout just one time !
Thank you very much for this comprehensive documentation ..

And thank you for your interest about my and my friends account , and trust me i know what i am doing.
Good bless you and your family !

**Comment by SteveJobzniak** [comment]
@findandreplace Thank you. And good luck. :-)

@mgp25 Okay!

**Comment by SteveJobzniak** [comment]
@findandreplace For you and others, to think about: An even simpler setup to avoid letting users login to each other's accounts, would be that your site asks users to create a website account. Then they login to that and link their Instagram account. From then on, only that account can access that IG account.

So the user would go to your site, login with their site username and password. Then click on their linked IG account and login with its password. Or something like that....

**Comment by dpavlovskiy** [comment]
> When a login() call was made, generate a random future timestamp between 30 minutes and 6 hours into the future via time() + rand(.........). This is the "we must call login() again" timestamp. 

Need "login()" every between 30 minutes and 6 hours - with creating a "new Instagram()" for new session or without "new Instagram()"?

```
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
$ig->login($username, $password);
```
or only
`$ig->login($username, $password);`

**Comment by aitte2** [comment]
@dpavlovskiy I am checking the source to answer that (https://github.com/mgp25/Instagram-API/blob/master/src/Instagram.php)... And the answer is: If you already have a `$ig` object you don't need to create it again (there's no difference if you do that). Just call `$ig->login($username, $password)`. It will then run the "refresh/resume session" API calls.

**Comment by dpavlovskiy** [comment]
Thank you!
