### ISSUE TITLE
Two Factor Authentication

### ISSUE THREAD

**Issue by backupManager** [mgp25/Instagram-API#1674]
Hi guys,

I'm building a new project using this amazing library and have run into a slight issue with 2-Factor Authentication.

I tried following the code located at: https://github.com/mgp25/Instagram-API/blob/3.1/examples/twoFactorLogin.php

It works fine when running via CLI but as soon as you move it to a web-based interface, it's all stateless. So when the user chooses to come back and put in their SMS verification code in the application, I'll have to `Instagram::login` again which triggers a completely new request for verification code generating a new one.

Since `Instagram::_setUser` is a protected function now, the only way to get to it is through `Instagram::login` and if I do that, I can't `Instagram::finishTwoFactorLogin` (ex: https://github.com/mgp25/Instagram-API/blob/3.1/examples/twoFactorLogin.php#L27) with my old verification code.

Any pointers would be dearly appreciated.

**Comment by backupManager** [comment]
I have gone through the past issues and the closest one is: https://github.com/mgp25/Instagram-API/issues/1323

but it's with an version of the library when `Instagram::_setUser` wasn't a protected function.

**Comment by SteveJobzniak** [comment]
Thanks for this report. That was unintended when we merged setUser and login (which was done to simplify login _and_ to prevent misuse where people set the user but never call login).

Strangely enough, v3 has been out since September 6th and in pre-release for months before that, so I am surprised why noone has said this before. I wonder if others are using some kind of solution?

Well, to oblige the web crowd, we could change the parameters for `finishTwoFactorLogin` to take username, password, identifier and verification code. And make it set the user too. It should solve your issue, while not being too much of a step back for proper CLI and [proper web users](https://github.com/mgp25/Instagram-API/wiki/FAQ#can-i-run-this-library-via-a-website).

Should we do that?

**Comment by backupManager** [comment]
Hey @SteveJobzniak, thank you for the quick response. 
That sounds like the most logical way to go about it.

My use-case is simply scheduling Instagram posts and its not done on every page load. Infact, this library is just called by `cron` whenever a post is scheduled to go live.

**Comment by SteveJobzniak** [comment]
@backupManager Yeah, I'll take care of it in a moment! 👍 

By the way, do you know about this when you're scheduling your posts via 3rd party libraries like ours? https://github.com/mgp25/Instagram-API/wiki/FAQ#my-photo-doesnt-appear-when-searching-hashtags

**Comment by backupManager** [comment]
@SteveJobzniak Thank you!

I did read that in the FAQ but I did a small test last night and I see it in hashtag listings so I thought it is working now ?! 

I'm not using this for spam.

**Comment by mgp25** [comment]
Photos with hashtags (using the API) are only visible in the hashtag feed by the user who has uploaded the photo, noone else will get the photo in the hashtag feed.

**Comment by SteveJobzniak** [comment]
The login issue for web embedders is taken care of now. Use `dev-master` (see readme). :-)

(Note that the comments in the commit are _NOT_ aimed at you in particular. ;-))

**Comment by backupManager** [comment]
@SteveJobzniak, that's because of the great work you guys put in to this library. It's so well maintained and documented that people like me want to keep using it and if there are issues, find workarounds.

@mgp25 I actually logged out and tried on a completely different computer. Maybe a one-off.

**Comment by SteveJobzniak** [comment]
@backupManager Thanks a lot. It's definitely been a massive job to get it to this state and it's wonderful to hear that it's appreciated. I hope you're having fun and enjoy the library!

By the way, about the hashtag searching: Things _may_ have changed since we wrote that wiki note... but I don't think so. Because if Instagram suddenly starts allowing 3rd party API photos in the main hashtag feeds, then there would be nothing but porn-spam and other junk on every hashtag from all of the bots in the world. Hmm... In the past, and probably still, they _only_ list media in hashtag feeds if you are using a real app client. If you post via your phone you'll always get seen. Any other way will [never get seen](https://github.com/mgp25/Instagram-API/issues/1274).

And yes, Instagram can detect the difference between this library and a real phone, because their real app has some uncrackable layers that nobody emulates (this library is the one that all other libraries for other languages are copying from, and we haven't emulated it, and neither has anyone else): Quicksand (encryption) and Graphs (analytics). The quicksand part is pretty easy but the graphs are [an impossible, ever-moving target](https://github.com/mgp25/Instagram-API/issues/1634#issuecomment-338470201).

If this was a world where spambots didn't exist, we'd be able to have a few more features such as hashtag reach. But unfortunately spam ruins it for everyone. :-\

**Comment by backupManager** [comment]
@SteveJobzniak Yeah, I have done a few personal projects for my own use. Been using this library for like 6 months via CLI only. Attempting a web-frontend for the first time and since I now have 2FA on all my accounts, that's why I ran into that issue.

That's interesting about Graphs and Quicksand. Didn't know about it but now that you mention it, I'm going to look into it in more detail. Maybe one day I can contribute to this library! :)

Yeah, would be so much better without spammers. :|

**Comment by SteveJobzniak** [comment]
Ahh, six months. Then you have seen the ongoing evolution ^_^

About web-frontend, you could try implementing this kind of setup (using `react/http` as library; check our realtimeHttp example): https://github.com/mgp25/Instagram-API/issues/1667#issuecomment-340776351

If you come up woth a nice design for the HTTP layer you could even contribute it as an `examples/` file. ;-)

**Comment by backupManager** [comment]
I'll definitely contribute to the `examples/` folder with a real HTTP example as soon as I figure something out. Thank you so much! :)

**Comment by SteveJobzniak** [comment]
That would be totally awesome. Good luck! <3 :-)

**Comment by krypto07** [comment]
@SteveJobzniak @backupManager Hello all, I have had this problem a month ago, I hadn't any time to report about it, sorry. And I built web-based account adding form with two-factor login, and now there is a bug as said @backupManager. When I confirm a sent code it sends that code (similar code) second time, because it is logging in the second time... @SteveJobzniak Is it fixed now? or have you created any function or method for it?
Thanks for this awesome API library, you are the best! @mgp25 @SteveJobzniak

**Comment by backupManager** [comment]
Hey @krypto07, yeah, @SteveJobzniak fixed it. You should pull the new changes.

`Instagram::finishTwoFactorLogin` now accepts a username and a password so u don't have to call `login` again to enter the code you receive.

**Comment by huynhquocbao92** [comment]
Hi all, a have had same this problem with verify code send twice time.
Please help me how to fix it.
Thanks you.
