### ISSUE TITLE
Comment is not appearing on Instagram despite status OK 

### ISSUE THREAD

**Issue by findandreplace** [mgp25/Instagram-API#1675]
While i am sending a comment , i got a **`status OK`** as following , but if you review the media , you can not find the comment !
Please note , it is only one comment so there is no loop or any kind of abuse !

Regards

```
POST:  https://i.instagram.com/api/v1/media/1640079496411667446_1640322131/comment/
DATA: signed_body=3b0c814f6ba09771e6d75f9eb7de4a5c155e2afa93e3a0a64fc8a69fc387965f.{"user_breadcrumb":"y7ozk3f1ILcika6g10XomvHwHgVIV+sxeoTcYgUTt1c=\nNDEgODQwMDAgMjEgMTUwOTczMzg1NzA1OA==\n","idempotence_token":"3ac19b4f-6787-4520-ad9b-3409a99803fa","_csrftoken":"873EASXORmDcV493xXb0RINV4lbJmYYe","radio_type":"wifi-none","_uid":"3895683360","_uuid":"8bd86631-edf6-4506-bb79-b58a06c3d401","comment_text":"Jolie contenu ! Un petit tour chez nous ?","containermodule":"comments_feed_timeline"}&ig_sig_key_version=4
← 200    394B
RESPONSE: {"comment": {"content_type": "comment", "user": {"pk": 3895683360, "username": "legginginabox", "full_name": "Legging In A Box", "is_private": false, "profile_pic_url": "https://scontent-ams3-1.cdninstagram.com/t51.2885-19/s150x150/19625106_2058281601065972_5428987169228193792_n.jpg", "profile_pic_id": "1456676961882832543_3895683360", "is_verified": false, "has_anonymous_profile_picture": false}, "pk": 17894292481128507, "text": "Jolie contenu ! Un petit tour chez nous ?", "type": 0, "created_at": 1509733856.0, "created_at_utc": 1509762656, "media_id": 1640079496411667446, "status": "Active"}, "status": "ok"}
```

**Comment by findandreplace** [comment]
It seem instagram Shadowban , now it is affect comment , if i log to account , i can find the comment , but if i log out , comment is gone !

WTF ,

**Comment by mgp25** [comment]
@findandreplace you account is flagged. It is working from here.

Regards

**Comment by findandreplace** [comment]
@mgp25 Lets assume the account is flagged , why when use instagram via web , comment appear with or without login !

**Comment by mgp25** [comment]
@findandreplace i dont know your circumstances or the context either. What i can say is that from my account is working. Also keep in mind that the API is not a perfect replica of Instagram, it has its differences, and if Instagram decides to not show you something, is up to Instagram Server.

**Comment by SteveJobzniak** [comment]
More importantly, Instagram has extremely advanced antispam which factors in tons of data to decide how risky (or not) you are, and which is capable of very detailed shadowbanning even down to just banning aspects of individual features.

**Comment by SteveJobzniak** [comment]
We've just found out that this @findandreplace motherfucker is a liar and a spammer.

He operates "legginginabox", a fucking spam profile which follows nearly 8000 people and spams random people with comments. He runs a bot which randomly comments on people's photos and says "Jolie contenu ! Un petit tour chez nous ?" (meaning "Pretty nice content! Want to come check us out?").

And then this utter goatfucking motherfucker comes to US and tells us "Guys, your API leads to shadowbanned comments. I am not doing anything wrong. Something is wrong with your API!".

And that is AFTER this fucker has already asked us for so much help in the past (and received it), and claimed that he did this for his little family. Turns out he's running a company.

Go fuck yourself, @findandreplace.
