### ISSUE TITLE
Does Posting Images work via this script?

### ISSUE THREAD

**Issue by AndiHamolli** [mgp25/Instagram-API#1676]
I read in a couple places that it isn't possible to post image to instagram. Will this library work. Bc if yes, it would be the coolest thing ever.
Thank you in advance.

**Comment by mgp25** [comment]
Hello @AndiHamolli,

Yes, it does. Since you are new here, i recommend you to read the:

- [Wiki](https://github.com/mgp25/Instagram-API/wiki)
- [F.A.Q.](https://github.com/mgp25/Instagram-API/wiki/FAQ)

Before opening an issue, you must read the [Wiki](https://github.com/mgp25/Instagram-API/wiki) and the [F.A.Q.](https://github.com/mgp25/Instagram-API/wiki/FAQ).

You can also find examples here:

- [Examples](https://github.com/mgp25/Instagram-API/tree/master/examples)

You need to use **Composer**, it is explained in the [Readme](https://github.com/mgp25/Instagram-API#installation). All dependencies are listed [here](https://github.com/mgp25/Instagram-API/wiki/Dependencies)

Regards
