### ISSUE TITLE
Authorisation Error

### ISSUE THREAD

**Issue by KJThaDon** [mgp25/Instagram-API#1699]
I am getting "Error: Authorisation error" when trying to connect. It worked fine before. I logged into my account through my web browser with the same username and password I always use, and it logged in fine. It did pop up saying something like "someone logged in from this location, was this you?" and I clicked yes, and browser normally. Still getting the error through the API though. Any ideas?

**Comment by mgp25** [comment]
Hello @KJThaDon,

you need to verify that you are the one logging in from the API from other location because the server you are using is probably using an IP from a location different than yours. You need to do the same you said: `"someone logged in from this location, was this you?" and I clicked yes`.

This is explained in the F.A.Q.:

- [What does "checkpoint_required" error mean?](https://github.com/mgp25/Instagram-API/wiki/FAQ#what-does-checkpoint_required-error-mean)

Regards
