### ISSUE TITLE
5 seconds sleep

### ISSUE THREAD

**Issue by ilusha2012** [mgp25/Instagram-API#1710]
For all request need to sleep 5 sec?

**Comment by mgp25** [comment]
Hello @ilusha2012,

Why? No. If you use the API as expected, no sleep is required. You can follow examples here:

- [Examples](https://github.com/mgp25/Instagram-API/tree/master/examples)

Regards

**Comment by SteveJobzniak** [comment]
For pagination: yes, always sleep when paginating. Otherwise you get throttled after around 40-50 API calls (page requests).

For other requests: sometimes. It depends on how often you call those APIs.

Instagram has complicated throttling algorithms. Some APIs are throttled heavily, som enot at all, and all calls count towards a global throttling limit too.

If you act like a real user in the pap (same navigation speed), you will not be throttled. If you are faster than a human you will be throttled.
