### ISSUE TITLE
maxId  returns null  and post collection is incomplete

### ISSUE THREAD

**Issue by timbilino** [mgp25/Instagram-API#1716]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [ ] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

Hi. I try to get the 90,000 posts of a hashtag. I change the max_id every time the program stops, but near the 9000 posts, the max_id returns null .. Is it possible to get this amount of posts or is there any restriction? . This is the code that I use:

```php
$tag ="localguides"
$maxId = "J0HWiAFqQAAAF0HWendCQAAAFs6AAQA%3D";
do {
    $result = $ig->hashtag->getFeed($tag, $maxId); // ????? ?? ??????? 
    $maxId = $result->getNextMaxId(); // ???????? ????????
    $items = $result->getItems(); //??? ????? ????? ????? ?? ????????
    foreach ($items as $key) {
      echo "getId: " ;
      echo $key->getId();
    } 
} while ($maxId !== null);
    echo "end";
```

**Comment by mgp25** [comment]
Hello @timbilino,

1. You don't need to provide a `$maxId` value at the beginning. [See example](https://github.com/mgp25/Instagram-API/blob/master/examples/paginationExample.php).

2. Instagram has some restrictions server side, and if you get `null`, that means there is nothing more to show you. It is not because the API but Instagram server.

I think this has been answered in the past (in a closed issue).

Regards
