### ISSUE TITLE
How to add location when uploading photo

### ISSUE THREAD

**Issue by maxvergelli** [mgp25/Instagram-API#1732]
With the following code the post is uploaded and visible on Instagram but the location doesn't appear:

                            $latitude = "20.2167";
                            $longitude = "87.4667";
                            $location_name = "Tulum, Quintana Roo";
			$location = new \InstagramAPI\Response\Model\Location;
			$location->lat = (float)$latitude;
			$location->lng = (float)$longitude;
			$location->name = $location_name;
			$instagram->timeline->uploadPhoto( $photoFilename, array('caption' => "caption text test", 'location' => $location) );

Could You give me a help? Thank You

**Comment by SteveJobzniak** [comment]
Hello. That is not how you add locations. It's wrong in every way.

Instagram uses special IDs for their locations. You must find the Location object via the same endpoint that the real app uses:

https://github.com/mgp25/Instagram-API/blob/67d5eacbcaf52f155e048c7b9738cb848f9b40a8/examples/uploadStory.php#L42-L47

Then just send that object as 'location' metadata.

Also, I do not recommend saving locations manually (ie making "new Location()" and putting fields in it). Because Instagram deletes/merges locations all the time, so they can stop working. The only safe way is to always search for it via the endpoint above.

Good luck :)

**Comment by SteveJobzniak** [comment]
PS: I just remembered something... We made lots of upgrades to Location attaching in the latest code. You should upgrade to `dev-master` code. But beware, you'll have to rewrite lots of your code, because most functions have changed, and you cannot access properties via `->some_prop` later. It's all done via `->getSomeProp()` and `->setSomeProp()` style now. See: https://github.com/mgp25/Instagram-API/issues/1623
