### ISSUE TITLE
Why we have to Generate " rankToken " ?

### ISSUE THREAD

**Issue by alaadiab** [mgp25/Instagram-API#1742]
Dear all , 

Why We need to call rankToken ? Why dont call it internally !

**Comment by SteveJobzniak** [comment]
No he cannot. ;-)

Because to act like the real app you need the same token on every call to the function for each related search pagination. So we cannot randomly generate it every time, and we cannot store it for you.

Examples:

rankToken = generate token (123)
Search hashtag: "nature". rankToken: 123
Search hashtag: "nature", page 2. rankToken: 123

rankToken = generate token (454)
Search location: "New York". rankToken: 454
Search location: "New York", page 2. rankToken: 454

Etc...

Look in the new `/examples/` folder examples of local token usage.
