### ISSUE TITLE
getGender() returns nothing

### ISSUE THREAD

**Issue by elnurxf** [mgp25/Instagram-API#1744]
Hi Steve. Thanks a lot for a huge work you've done for us.

My question is: then I get me followers I getSelfFollowing() and on each result I getGender() It's return nothing, but other getters like getIsPrivate() works as expected.

Could you point me to correct way?

Thanks.

**Comment by SteveJobzniak** [comment]
Hi! Happy to hear that you are liking the API. We all worked very hard on it!

The `get<Self|><Following|Followers>` returns short info: Name, username, ID. Not much else.

To get full info there is only one way: `$ig->people->getInfoById($id)`. :-)

**Comment by elnurxf** [comment]
That's make sense! Thanks a lot for your quick reply and support!
A pint of beer from me ;)

**Comment by SteveJobzniak** [comment]
Haha. 👍 Enjoy.

PS, if you want info about your own account, `$ig->people->getSelfInfo()` is a shortcut for self, and there's also `$ig->account->getCurrentUser()` for yourself with some other info.

**Comment by elnurxf** [comment]
Hey @SteveJobzniak 

Before you leave for a year :) I wish you good luck!

Now is the question:
`$response = $instagram->people->getInfoById($userId)->getUser();`

`return [
    'id'              => $response->getPk(),
    'isGender()'      => $response->isGender(),
    'hasGender()'     => $response->hasGender(),
    'getGender()'     => $response->getGender(),
    'getUsername()'   => $response->getUsername(),
    'getIsPrivate()'  => $response->getIsPrivate(),
    'isIsBusiness()'  => $response->isIsBusiness(),
    'hasIsBusiness()' => $response->hasIsBusiness(),
    'getIsBusiness()' => $response->getIsBusiness()
];`

Returns me with:

`{
"id": "1247936749",
"isGender()": false,
"hasGender()": true,
"getGender()": null,
"getUsername()": "elnur_akhundov",
"getIsPrivate()": true,
"isIsBusiness()": false,
"hasIsBusiness()": true,
"getIsBusiness()": false
}`

Event request which is coming from is followed and following back user. So, It's a private user, but following each other. The requested user pointed gender. So getting gender looks too complicated to me :\

**Comment by SteveJobzniak** [comment]
@elnurxf Hi. Thanks for the well-wishes. :-)

I investigated this quickly now. The answer is that `gender` is not provided by Instagram's API for any account except your own, via exactly this function: `$ig->account->getCurrentUser()`. It's the only function that gives gender. There is absolutely no chance that you will get it for other accounts. For example, you cannot even get gender via `$ig->people->getSelfInfo()`, which is another way to get info about your own account (it's like doing `$ig->people->getInfoByI()` on your own ID), in the same way you'd get info about others. And since that one is blank for yourself in that call, you will definitely not get it for others.

So forget about gender. ;-)

**Comment by elnurxf** [comment]
@SteveJobzniak thank you!

Looks like same is for `getBirthday()` and similar methods which work with `getCurrentUser()`

Good luck to you with all new beginnings! 👍
