### ISSUE TITLE
Media 'usertags' array is null after editing.

### ISSUE THREAD

**Issue by andCoder** [mgp25/Instagram-API#1748]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---
---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

Example Code:

```php
					$usertags = $meta_array['usertags'];
					$tags     = [ 'removed' => [], 'in' => [] ];
					if ( $usertags !== null ) {
						foreach ( $usertags as $usertag ) {
							$image_meta['caption'] .= ' ' . $usertag['name'];
							$tags['in'][]          = [
								'position' => $usertag['position'],
								'user_id'  => (int) $usertag['user_id']
							];
						}

						$configure = $this->client->timeline->uploadPhoto( $file, $image_meta );
						if ( count( $usertags ) ) {
							$response = $this->client->media->edit( $configure->media->id, $image_meta['caption'], [ 'usertags' => $tags ] );
						}
					}
```

### Describe your issue

Hello. Currently I'm trying to add usertags feature to my program. But I've got stuck on it. I add usertags after image uploading as you've answered to someone previously but response media always doesn't contain them and response status is 'OK'. $meta_array is a variable that is read from json file. It contains data in that format: 
```json
{"meta":{"hashtags":[],"location":null,"usertags":[{"user_id":"6425704505","position":[0.43125,0.5698744769874478]}],"caption":""}}
```

**Comment by mgp25** [comment]
Hello @andCoder,

You read the answer partially. Now you can do when uploading or after uploading it, is up to you. When you do an `user_tag` and you are specifying the position and the `user_id`, it is only making that concrete position clickable. If you try with your code, although there won't be any usertag, if you go to that position and click in there, you will see that is working.

Why is this happening? Because the API doesn't do any modifications to the image. Usertag is just a layer on top of your image. So now that you know this, you should usertag when uploading and add the usertags layer on top of your image, so it will match with the clickable area you have specified.

Regards

**Comment by andCoder** [comment]
Thank you for help.
