### ISSUE TITLE
How can I get all the followers of this line in the story

### ISSUE THREAD

**Issue by Juuhz** [mgp25/Instagram-API#1767]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

Hello good Morning!

How can I get all the followers of this line in the story?

`[text] => people1 started following people2, people3 and 9 others.`

- I am using the **getFollowingRecentActivity()** method

 Thanks for the patience in helping me <3

**Comment by mgp25** [comment]
Hello @Juuhz,

```php
$response = $ig->people->getFollowingRecentActivity();

$response->getStories()[0]->getArgs();

$text = $response->getText();
$users_ids = [];
foreach($response->getLinks() as $link) {
   $users[] = $link->getId();
}
```

Regards

**Comment by aitte2** [comment]
I tested too. The real app and this code above only gets ids of listed users. I think there's no way to get the full list of all "and 13 others". Also, the 1st ID is always the person who did the action which you may not want, so you can skip the first guy like this:

```
foreach($response->getLinks() as $link) {
    if ($link->getStart() == 0)
        continue;
    $users[] = $link->getId();
}
```

Maybe my code is not so great but it works... The start/end is the position of the name in the text, and the 1st user is always at "start: 0" (such as "dantheman liked 8 posts").

Also if you want to get media IDs for actions about "ABC liked 8 posts", you get all of those posts via "getMedia()" instead of "getLinks()".
