### ISSUE TITLE
Uploaded Video is Zoomed In

### ISSUE THREAD

**Issue by djstanley** [mgp25/Instagram-API#180]
Hi,

When you upload a video in the Instagram app, it by default scales it to be zoomed in. There is a button (see the image attachment) which when pressed returns it to the original video size.

When I upload videos via the mgp25 library, the video is uploaded as scaled/zoomed in. This means some parts of the video cannot be seen. I want to essentially "press" this button so the uploaded video does not automatically get scaled and stays in its original size.
![screenshot](https://cloud.githubusercontent.com/assets/17340299/15305101/07c84876-1bb9-11e6-8f91-8617fca2e06f.JPG)

**Comment by mgp25** [comment]
Probably because of the request i capture, but you can canpture a request while configuring the video, compare it to the one its implemented here, and add a option to configure it without zoom.

When ready, you can send a pull request and ill merge it

Regards

**Comment by mewlabs** [comment]
hello @mgp25 please capture request with this button pressed. It would be great, because without it, uploading of video is useless in most cases... I can capture traffic up to v7.0.0 of app but they don't have this button yet. I guess that should be several additional options in configuration to display video in original size without cropping on mobile devices. Thanks!
