### ISSUE TITLE
edit phone number with sms verification in editprofile method

### ISSUE THREAD

**Issue by hadikmsh** [mgp25/Instagram-API#1811]
Hi
in original instagram client if we want to change or input a new phone number in our profile, an activity will open and ask to verify our phone number.
in editProfile method there is a field called phone_number but i can not find any method to verify phone number. How can i do that? can you help me?
thanks.

**Comment by mgp25** [comment]
Hello @hadikmsh,

That feature is not implemented but probably will soon (i will check later today). You can still send a pull request if you time.

Regarsa

**Comment by mgp25** [comment]
Added in latest commit: https://github.com/mgp25/Instagram-API/commit/dfa53a04619c8b83010a8537d10c45e6d7b04f55

Regards

**Comment by hadikmsh** [comment]
Hi @mgp25 
Thanks for your fast response.
thank you so much.

**Comment by aitte2** [comment]
@Mgp25 Hi, I was reading the new commit but was confused because one thing was named `sendConfirmEmail()` which matches `'accounts/send_confirm_email/'` which is logical, but then we had the new `requestSMSVerificationCode()` which is also a "please verify me" function but for SMS instead (so shouldn't it match the `send*` pattern of the email function?), and its endpoint was `'accounts/send_sms_code/'` so the new function's name wasn't the same as the endpoint. There were also some older functions that didn't match their endpoint. I hope you don't mind that I made all new and old functions more closely match their official endpoints. :) https://github.com/mgp25/Instagram-API/commit/efdbc694a0e3d401ea1fe90ada7e159ea4d32cd1#diff-ab26304dc21e3b69a6aa5078eea97607R496

@hadikmsh `$ig->account->sendSMSCode()` will make Instagram send you a SMS verification code, and `$ig->account->verifySMSCode()` is for you to verify the code you received.

**Comment by mgp25** [comment]
Hello @aitte2, can i talk with you? Email or any IM if possible, send me your contact to email please.

Regards

**Comment by aitte2** [comment]
@mgp25 sent to email! ;)
