### ISSUE TITLE
Live Comment

### ISSUE THREAD

**Issue by amirhododi** [mgp25/Instagram-API#1866]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [x] Question
- [ ] Other

---

Hi when i start live broadcast all thing was ok but when addToPostLive are other users comments was gone in saved replay why?

**Comment by mgp25** [comment]
@valga @aitte2 is there anyway to run commands in loop while:

```php
    $ffmpeg->run(sprintf(
        '-rtbufsize 256M -re -i %s -acodec libmp3lame -ar 44100 -b:a 128k -pix_fmt yuv420p -profile:v baseline -s 720x1280 -bufsize 6000k -vb 400k -maxrate 1500k -deinterlace -vcodec libx264 -preset veryfast -g 30 -r 30 -f flv %s',
        escapeshellarg($videoFilename),
        escapeshellarg($streamUploadUrl)
    ));
```

is running? 

Because the issue here could be that we are missing the request done during the transmissions which are:

- `live/id/get_comment/?last_comment_ts=0&num_comments_requested=3`
- `live/id/heartbeat_and_get_viewer_count/`
- `live/id/get_like_count/?like_ts=0`
- `live/id/get_join_request_counts/?last_total_count=0&last_seen_ts=0&last_fetch_ts=0`

And before sending the end broadcast we should do: 

- `live/id/get_final_viewer_list/`

Thoughts/ideas?

Regards

**Comment by valga** [comment]
@mgp25 https://symfony.com/doc/current/components/process.html#running-processes-asynchronously

**Comment by mgp25** [comment]
@valga something like this?

```php
    $process = new Process($ffmpeg->run(sprintf(
            '-rtbufsize 256M -re -i %s -acodec libmp3lame -ar 44100 -b:a 128k -pix_fmt yuv420p -profile:v baseline -s 720x1280 -bufsize 6000k -vb 400k -maxrate 1500k -deinterlace -vcodec libx264 -preset veryfast -g 30 -r 30 -f flv %s',
            escapeshellarg($videoFilename),
            escapeshellarg($streamUploadUrl)
        )));
    $process->start();
    while ($process->isRunning()) {
        $ig->live->getComments();
        //other request
       // ....
       sleep(1);
    }
```

**Comment by aitte2** [comment]
I have no idea about this sorry 😕

**Comment by valga** [comment]
@mgp25 You've got the idea, but you have to build the command manually:
```php
$process = new Process(sprintf(
    '%s -rtbufsize 256M -re -i %s -acodec libmp3lame -ar 44100 -b:a 128k -pix_fmt yuv420p -profile:v baseline -s 720x1280 -bufsize 6000k -vb 400k -maxrate 1500k -deinterlace -vcodec libx264 -preset veryfast -g 30 -r 30 -f flv %s',
    escapeshellarg($ffmpeg->getFFmpegBinary()),
    escapeshellarg($videoFilename),
    escapeshellarg($streamUploadUrl)
));
```

**Comment by aitte2** [comment]
@valga How about changing ffmpeg wrapper `run()` to use Process, and have an argument that chooses between 'run and wait' or 'just run (async)'? That way it can be used in either mode. But I have no idea what this is for, so I will stop trying to help :D

**Comment by mgp25** [comment]
@valga what do you think about @aitte2 's comment?

**Comment by mgp25** [comment]
@amirhododi this is now fixed. If you want to try it, make sure to use latest commit from `dev-master`

@valga @aitte2 

This was fixed in: https://github.com/mgp25/Instagram-API/commit/2b168be7244f16740e7629c9bc6e40745e6d3584

I think I made everything clear, nevertheless feel free to make any changes to it to improve it and make it easier to understand.

Regards

**Comment by aitte2** [comment]
@mgp25 Nice work and good idea with the loop. I see some bugs with typos which I'm going to fix. But one thing I can't verify is `'is_first_fetch'             => 'string',`. Its name looks like it should be a true/false 'bool'? Was it really a string?

Because if we go into src/Response and search for `'is_` in all files, we only find int and bool values with the `is_` prefix. This `is_first_fetch` is the first time any `is_` is marked as string. So is that correct or was it a typo?
