### ISSUE TITLE
Where are the examples asJson?

### ISSUE THREAD

**Issue by wolrd** [mgp25/Instagram-API#1890]
I have created the issue https://github.com/mgp25/Instagram-API/issues/1882
@mgp25 answered me to read documentation and watch examples. Where are the examples? 

I want convert $ig to a string. And I don`t understand how to do it. How can I do it? 
My lib version is 4.0.

```
$ig = new Instagram();
$ig->login('user', 'pass');
```

**Comment by mgp25** [comment]
Sigh... The API returns objects, you don't manage json directly, in fact you can use `asJson()`.

It seems you didn't read the: 

For more info: https://github.com/SteveJobzniak/LazyJsonMapper

Example:

- [basic_example.php](https://github.com/SteveJobzniak/LazyJsonMapper/blob/master/examples/basic_example.php)

Regards

**Comment by wolrd** [comment]
I have studied basic_example.php but I don`t understand what to do with it:
```
class Section extends LazyJsonMapper
{
    const JSON_PROPERTY_MAP = [
        'section_title' => 'string',
        'users'         => 'User[]',
    ];
}
```
I need to convert $ig to a string, send it, convert it back in order to login again.

**Comment by wolrd** [comment]
@mgp25  ?

**Comment by aitte2** [comment]
@wolrd Your old question was:

> How to convert an object `($loginResponse)` to json?
> ```php
> $loginResponse = $ig->login($username, $password);
> ```
> I use the `json_encode($loginResponse)` but return 'false';

The `login()` function returns null most of the time (read its docs!). So you cannot use any functions such as `asJson()` on the "login response" because there is no login response most of the time! I think you only get a loginresponse when the library does a full login for the first time (or the rare cases of a relogin due to deleted session).

---

About the example: It's about another library we use. It demonstrates what functions you can use to convert things to JSON (`asJson()`), print the data (`printJson()`), look at functions (`printPropertyDescriptions()`), when you have a valid object.

The login response, as I said above, is not a valid object (most of the time).

---

About "I need to convert `$ig` to a string, send it, convert it back in order to login again.", I get the feeling you don't understand PHP, since you think you should convert a PHP object to a string, which is impossible. That is not our problem. Please read PHP tutorials to learn the basics before trying to program in PHP or use a library like this.

To relogin again, you always have to call `$ig = new Instagram(); $ig->login($username, $password)` every time.
