### ISSUE TITLE
Access to a account Function

### ISSUE THREAD

**Issue by Startname** [mgp25/Instagram-API#1906]
- [x] Request

in instagram app can Access to a account when forget the password
via Email or Phone or Facebook

<img src="https://preview.ibb.co/iCMdPx/photo_2018_04_10_21_52_24.jpg" width=200>

Please, add this.

**Comment by aitte2** [comment]
To team: Where would we put this code? I assume this is stuff _before_ the user has logged in, so I guess in the main class.

Something like `$ig->forgotPassword($recoveryType, $data)` where `$recoveryType` is one of `username, email, sms, facebook` and `$data` is the username, email, sms number or facebook (actually I doubt we can do the facebook method since we have no facebook code, so forget that part).

**Comment by mgp25** [comment]
Added: https://github.com/mgp25/Instagram-API/commit/bac5e6957fc3099a917f70db7729df908ebb3860

@aitte2 I did slightly different to your recommendation since function were using different endpoints. Nevertheless, I think is clear enough for the users to understand it and its very intuitive, anyway, feel free to check it and change anything.

**Comment by aitte2** [comment]
@mgp25 Yep it's very intuitive, I like it! `sendRecoveryEmail()` and `sendRecoverySMS()` avoids having a single function with confusing parameters. :) 👍
