### ISSUE TITLE
Question/suggestion about MQTT

### ISSUE THREAD

**Issue by Zazo0** [mgp25/Instagram-API#1938]
Is it optional? It is unclear according to this document:
https://github.com/mgp25/Instagram-API/commit/87d90d94fea68dbf15452a9d9fc9df3c3ac7c3a1#diff-b899fb41b88f6fd2e27a4203cc617bb4
If no then is it possible to make it optional? Reason - MQTT is less popular than TCP/IP even if it gives additional possibilities

**Comment by mgp25** [comment]
Hello @Zazo0,

Can you elaborate your question, please? Is it optinal what?

**Comment by valga** [comment]
@Zazo0 https://www.google.com/search?q=why+is+facebook+using+mqtt

**Comment by Zazo0** [comment]
@mgp25
according to git previously you didn't use code which interacts with MQTT protocol.
Then you add this commit:
https://github.com/mgp25/Instagram-API/commit/87d90d94fea68dbf15452a9d9fc9df3c3ac7c3a1#diff-b899fb41b88f6fd2e27a4203cc617bb4
with comment
```
This PR minimizes coupling between Realtime/Push clients and Instagram instance.
```
As I understand your code with MQTT just improves the code and may be safety excluded, mayn't it? Or in other words is this code optional? Or does Instagram require MQTT now always?

@valga
thanks but it doesn't answer the question "MUST this library use MQTT protocol to interact with Instagram?". I ask because your library didn't use MQTT previously and everything was Ok.

**Comment by mgp25** [comment]
@Zazo0 Instagram used to use http for everything, but since their user base is growing so fast, they need light protocols to save bandwidth. Both facebook and instagram are using MQTT protocol.

So in few words: Yes, now Instagram requires MQTT, and thats why we do the MQTT implementation. Actually, @valga was valga the one to implement it, and it is perfect.

Regards

**Comment by valga** [comment]
@Zazo0 I will explain everything in details.

First of all, you can't build an interactive mobile app using HTTP protocol alone. You have to notify a user about some events, and using `while (true) {http.pullNewEvents(); sleep(1);}` is not ok. There is an obvious solution - Push notifications. 

Originally Instagram used only GCM/APNS/whatever, but then it has been bought by Facebook. Facebook has its own Push notifications service called FBNS, and it runs on MQTT. FBNS is the primary Push channel, while GCM/APNS/whatever is used as a secondary channel in case of errors.

But Push notifications can't cover all usecases, because they are designed just to notify users about something, also payload and sending rates are somewhat limited. So when Instagram were in need of some realtime communication channel, they have chosen Websocket (see #1105). But then Facebook bought Instagram, and Facebook can't afford running 2 different protocols for the same purpose, so they switched to MQTT (see #1356).

To conclude, the app uses MQTT to:
1. Receive Push notifications. The app has a service that runs in background even if you are not using the app.
2. Communicate with Instagram servers in realtime. Realtime client runs only when the app is in foreground.

And yes, you MUST use MQTT if you want to look like the real app.

**Comment by aitte2** [comment]
Great answer. I learned a lot. :)

**Comment by zzet** [comment]
@addonis1990 nope

**Comment by addonis1990** [comment]
Been trying other tools to enable the real time stuff on python but no luck so far. How about you @Sovetnikov ?

**Comment by valga** [comment]
@addonis1990 You can't use paho for push notifications because of non-standard MQTT protocol version they have. More details [here](https://github.com/mgp25/Instagram-API/pull/1459#issuecomment-361902230).

However, you can use paho for the realtime (MQTT 3.1).

**Comment by addonis1990** [comment]
@valga when you say it is broken, do you mean the code is broken or Instagram stopped supporting that ? What is the last version that worked with realtime with no issues?

**Comment by valga** [comment]
@addonis1990 See #2287. The last working release is 4.1.0.

Push notifications work just fine in all versions though.

**Comment by Sovetnikov** [comment]
@addonis1990, i just made python FBNS client based on react_fbns code
you can check my repo https://github.com/Sovetnikov/fbns_mqtt
there is complete example
@valga thanks for FBNS reversing!
