### ISSUE TITLE
Invalid JSON property map entry "0"

### ISSUE THREAD

**Issue by hesam67b** [mgp25/Instagram-API#1963]
### Before submitting an issue make sure you have:
- [ ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [ ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [ ] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [ ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [ ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### Describe your issue

hi.
when i try login to account, get this error:
Something went wrong: Compilation of sub-property hierarchy failed for class "\InstagramAPI\Response\TimelineFeedResponse". Reason: Invalid JSON property map entry "0" in class "\InstagramAPI\Response\Model\ReelMention". /../lazyjsonmapper/src/Property/PropertyMapCompiler.php 535 
how can i fix it?

**Comment by mgp25** [comment]
Steps to reproduce and more info required. If you want help/support for issues you need to make clear everything, we don't have the time to figure out whats the problem here.

**Make sure you are using latest release or dev-master code.**

So please, if you want help, post the following information:

- Steps to reproduce
- Debug log of the request giving issues

Regards
