### ISSUE TITLE
Uploading photo and returning media_id

### ISSUE THREAD

**Issue by davidenco** [mgp25/Instagram-API#2011]
Using the example ([/examples/uploadPhoto.php](https://github.com/mgp25/Instagram-API/blob/master/examples/uploadPhoto.php), I can upload a photo but I want to access the media id and other variables returned by the upload photo call.

If I try to run this code:
```php
$object = $ig->timeline->uploadPhoto('filename.jpg', ['caption' => 'My caption']);
echo $object->media->id;
```

I get:
Virtual property access is disabled for class `\InstagramAPI\Response\ConfigureResponse`

What am I doing wrong?

**Comment by mgp25** [comment]
Hello @davidenco,

I would recommend you reading this:

- Example: [How to access values](https://github.com/mgp25/Instagram-API/blob/master/examples/accessingValues.php)
- Wiki: [Managing responses](https://github.com/mgp25/Instagram-API/wiki#managing-responses)

As you can see from the function doc: https://github.com/mgp25/Instagram-API/blob/master/src/Request/Timeline.php#L30

`timeline::uploadPhoto()` returns `\InstagramAPI\Response\ConfigureResponse` (It is in the function's doc!).

The problem here is not the class, is how are you accessing values. The first to links I sent you will solve your question.

Regards
