### ISSUE TITLE
how to check if user follows me 

### ISSUE THREAD

**Issue by DarkSaTla** [mgp25/Instagram-API#2104]
Hey,
i tried to get the data of user but i not see anything that result his follows me, what can i do?

**Comment by mgp25** [comment]
F.A.Q.: https://github.com/mgp25/Instagram-API/wiki/FAQ
Closed issues: https://github.com/mgp25/Instagram-API/issues?q=is%3Aissue+is%3Aclosed

**Comment by DarkSaTla** [comment]
i readed the other issuse that someone got that problem too, but i dont understand can u help me before closing?

**Comment by mgp25** [comment]
@DarkSaTla The reason this issue was closed is because this was explained in other issues and how to get values from the responses are explained in the wiki. Keep in mind this is a issue tracker not a help forum. And don't get me wrong. As long as you have a reasonable question it will be answered with as much as detail we can.

Now a very easy way to check things. Use your device go to friends profile. Does it appear something like "follows you"? Well, there's your answer. Instagram doesn't offer that feature right now as far as I know.

**Comment by mgp25** [comment]
@DarkSaTla Use `$ig->people->getFriendship($userId);`
