### ISSUE TITLE
Api returns some account info as null values

### ISSUE THREAD

**Issue by AndManowar** [mgp25/Instagram-API#2214]
Hi, Im trying to get account info such as account followers/followings and media count, but api returns null.
Request example: $this->account->getCurrentUser()->getUser()->getFollowingCount();
Extension version: "mgp25/instagram-php": "^4.1",

**Comment by mgp25** [comment]
Hello @AndManowar,

Have you seen debug log? It is there for this exact reason. You have to check if that request returns any following/follower information which this isn't the case and thats why you see the `null`. 

If you had searched in the documentation, you would have noticed that we recommend another function to get other information like the the one you are trying to get.

https://github.com/mgp25/Instagram-API/blob/master/src/Request/Account.php#L17

And use `dev-master` since latest release is very outdated. Hope that this has helped you.

Regards

**Comment by AndManowar** [comment]
Thank you very much, that works:)

**Comment by AndManowar** [comment]
The other question is:
When i logged in with a specific username and password - i can type any other password while logging in other times for this username (i think that`s because account data is stored in file), so how can i resolve this? I want to check credentials each time while logging
