### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by AndManowar** [mgp25/Instagram-API#2215]
When i logged in with a specific username and password - i can type any other password while logging in other times for this username (i think thats because account data is stored in file), so how can i resolve this? I want to check credentials each time while logging.
And even i write valid credentials to the account - im getting `InstagramAPI\Response\LoginResponse: The password you entered is incorrect. Please try again.`

**Comment by mgp25** [comment]
When you login using the mobile app, everytime you try to open the app afterwards you will be logged in directly. This happens because the app stores session authentication in cookies. The same happens with the API, once you have logged in with an account successfully, we store these cookies in the folder `/sessions` and are used to resume your existing session. When you call `login()` function and have an existing session, it will NOT perform a login request, in fact it will only call requests that imitates mobile app.

Keep in mind that this API works in the same way to the mobile app. If you want to do login again, then you need to logout from the app. Same happens here!

There are two ways for you to "logout", which is using the [logout](https://github.com/mgp25/Instagram-API/blob/master/src/Instagram.php#L1135) function or removing the user session from the `/session` folder.

I want to clarify that this API does **NOT** store the password.

Regards

**Comment by AndManowar** [comment]
Ok, and what about invalid credentials while login? I know, that credentials are valid

**Comment by mgp25** [comment]
@AndManowar make sure the username and password are correct.
