### ISSUE TITLE
What are the external metadata key that we have to pass during video upload on instagram story.

### ISSUE THREAD

**Issue by KrishnaVishwakarma1595** [mgp25/Instagram-API#2256]
I am wondering about the key-value pairs that we have to pass in the metadata array if we are uploading a single video on an Instagram story. Could anyone help me about that?

**Comment by mgp25** [comment]
@KrishnaVishwakarma1595 can you elaborate your question? Do you mean all possible key-values?

It can be found in:

- [/examples/uploadStory.php](https://github.com/mgp25/Instagram-API/blob/master/examples/uploadStory.php)
- [/examples/uploadStoryPoll.php](https://github.com/mgp25/Instagram-API/blob/master/examples/uploadStoryPoll.php)

Regards

**Comment by KrishnaVishwakarma1595** [comment]
Thank you for the answer. Yes, I meant all possible key-values pairs for uploading a video on a story. I've searched into inner files but I found we can use only story_polls, hashtags, location, location_sticker, story_mentions, user tags and link also If we have a business account and more than 10k followers If I'm not wrong. 

But, what about other key-value pairs of metadata for video sharing on a story. I'm trying to post a video on my story without any metadata but it keeps throwing an error "Something went wrong: The photo file "my_file_path/filename.mp4" is not a valid image." Do I have to include thumbnail image path in the metadata and path it during the request? Here is the code I'm using:

$debug = true;
		$truncatedDebug = false;
		$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
		try {
			$ig->login($login, $pass);
		}catch (\Exception $e) {
			echo 'Something went wrong: '.$e->getMessage()."\n";
			exit(0);
		}
try {				   
$video = new \InstagramAPI\Media\Photo\InstagramPhoto($filePath, ['targetFeed' => \InstagramAPI\Constants::FEED_STORY]);
			$ig->story->uploadVideo($video->getFile());				    
		} catch (\Exception $e) {
			echo 'Something went wrong: '.$e->getMessage()."\n";
		}

Please go through this link - https://prnt.sc/l1yspn

**Comment by mgp25** [comment]
Hello @KrishnaVishwakarma1595,

You are right about all you hav said, but the error you have is more trivial. You are uploading a video, right?

```php
$video = new \InstagramAPI\Media\Photo\InstagramPhoto($filePath, ['targetFeed' => \InstagramAPI\Constants::FEED_STORY]);
```

If you look closely the line above, it says `InstagramPhoto` and not `InstagramVideo` and `Photo` instead of `Video`. And that is way the class is complaining, because you are passing a video instead of an image.

The right code would be:

```php
$video = new \InstagramAPI\Media\Video\InstagramVideo($filePath, ['targetFeed' => \InstagramAPI\Constants::FEED_STORY]);
```

About your question if the `thumbnail_timestamp` is required, it is not. That is optional and it is used to specify a custom timestamp for the thumbnail (it is extracted from the video).

Reference:

- (/examples/uploadVideo.php)[https://github.com/mgp25/Instagram-API/blob/9d20c73eb8d55249bd596c5007a496a9944defe3/examples/uploadVideo.php]

**Comment by KrishnaVishwakarma1595** [comment]
Oh, god! It was a silly mistake. Thanks, @mgp25 It's working now.
