### ISSUE TITLE
Check if the user is followed by me

### ISSUE THREAD

**Issue by AndManowar** [mgp25/Instagram-API#2271]
Please explain me how can I check if the user is followed by me or not . 
UserInfoResponse doesn`t provide me with this information. Or Im blind :(
Tried to call getInfoById and getInfoByUsername

**Comment by mgp25** [comment]
@AndManowar Does the Instagram app (Android) shows you anything in the screen if a user is following you when you visit their profiles?

**Comment by AndManowar** [comment]
No, I want to check if the user is followed by me. (Do i have to show Subscribe button or not?)

**Comment by mgp25** [comment]
@AndManowar If the app doesn't show you anything if the user is following you, then... you have to look if your username is in their following list, right?

This issue is duplicated, make sure to search before opening new issues. Furthermore, it is a good practice to check how the Instagram app behaves comparing it to the API and understanding what you are doing.
