### ISSUE TITLE
Checking for authenticity

### ISSUE THREAD

**Issue by Tridenn** [mgp25/Instagram-API#2325]
Hello. There was a small question. I noticed that if you go through the wrong link to the photo in instagram, then there will be the inscription "URL signature mismatch" or "no content". So, probably the photo gives a full script, and not nginx for example. There have already been written that sometimes the photo disappears after publication. When you upload a photo in instagram, the new post is displayed immediately. The question is, does anyone know, the photo in the post he already gets on the link? Probably, this parameter can be used to track whether the post was posted from the phone or not. Because I didn’t seem to have found a code that would read the photo after uploading. Script can it track?

**Comment by bolds07** [comment]
your question is not clear about what is "going through the wrong link" www.instagram.com/asdiashduiahdsu is a wrong link to me...

you should provide an example of this behavior

second, instagram actually does not provide any way to upload a photo wihtout the app so you statement "used to track whether the post was posted from the phone or not" makes no sense, since it is impossible to the photo NOT be posted from the phone

if i did understand something in all this mess you wrote is you want to understand how does instagram defines a link to a photo after someone uploading it...

well it is a two phase configuration, first you upload the photo and assign an id to it
then you assign the respective metadata to that photo passing the id

when second phase is complete instagram will start showing the photo on the app

**Comment by sergeykomlev** [comment]
> There have already been written that sometimes the photo disappears after publication.
True. But only for new accounts. Not for all, why this happened I don't know.

**Comment by Tridenn** [comment]
@bolds07, hello. I know English badly. 
example: https://instagram.fhel2-1.fna.fbcdn.net/vp/367a54668cc6c8e0babf41927168b410/5C6FE816/t51.2885-15/e35/43621839_330208194227022_80941595411865812_n.jpg
it's try.
A bad link is to change the numbers.
example: 
https://instagram.fhel2-1.fna.fbcdn.net/vp/367a54668cc6c8e0babf41927168b410/5C6FE816/t51.2885-15/e35/43621839_330208194227022_80941595411865811_n.jpg
we get "URL signature mismatch".

This suggests that requests to the file are made through a script that gives them.

After uploading the file to the server, private api does not download files by the link it receives. If server-side requests are processed by a script, can it consider it suspicious? Does so, of. attachment?

Did you get a clearer explanation?

**Comment by mgp25** [comment]
@Tridenn Instagram has a way to modify the images from the URL, operations like resizing, cropping or expanding (there are many more). However, this URLs are signed (similar thing like we do with API requests), so if you want to modify any of the URLs parameters you will need to sign the URL too. This is something I am not going to support in the API or at least for now.

Regards

**Comment by Tridenn** [comment]
@mgp25 
I'm calling, but I don't need to change the link. I gave this example to confirm that the photo returns the script. There any text is written, when clicking on the wrong link.
When you upload a photo from the official application, it is displayed in the tape immediately. It became interesting to me, the data on the new post it receives from the server instagram or not. If so, then the instagram can see if the application has downloaded the photo for display after downloading. Api does not. since the photo gives the script, it can follow this. Maybe at least this time I wrote understandably.
