### ISSUE TITLE
How can i share instgram's post from feed to story ?

### ISSUE THREAD

**Issue by AmienKhaled** [mgp25/Instagram-API#2335]

**Comment by bolds07** [comment]
you should start reading the wiki about how to use the api-> login, get user feed and all basic stuff...
then you need to download the media item you want from instagram to you local machine since there isn't a straight way to copy a media from feed to story...

once the image you want is local, you need to redimension it since feed and story have tottally different image aspect allowed...

finishing you just need to call the function to upload the redimensioned image to story...


the api part is easy, the difficult thing will be how to handle the different image aspect from feed to story.

But if you are waiting for someone to write down you the code you need... please wait with a beer

**Comment by bolds07** [comment]
First there was no question to read just a title what was against any standard of this repository 

Second if the instagram app do allows you to share a photo from feed to story is exactly this process the app does...  There isn't any request that tells the server to "copy the photo from one feed to another"
