### ISSUE TITLE
reacted to their story

### ISSUE THREAD

**Issue by GoldenEagle66** [mgp25/Instagram-API#2354]
![image](https://user-images.githubusercontent.com/17871694/49011923-dbc88d00-f188-11e8-93fd-d62086d1c4b5.png)

Is it possible to repeat this through the library?
If so, how?
using sendReaction?

**Comment by mgp25** [comment]
Yes, that is correct.

Regards

**Comment by fuzzybro** [comment]
> ![image](https://user-images.githubusercontent.com/17871694/49011923-dbc88d00-f188-11e8-93fd-d62086d1c4b5.png)
> 
> Is it possible to repeat this through the library?
> If so, how?
> using sendReaction?

Hey @GoldenEagle66 , have you figured out how to react to stories?

`sendReaction` doesn't really work since it was meant to post reaction on already existing thread items. Basically if I share a story I can _separately_ send a reaction to it, and that reaction is limited to 'like' only.

When it comes to reacting to stories, I think `sendStory` method should be used and some extra options should be provided in the `options` array. I haven't figured out which ones tho.

@mgp25 could you please give us a hint?
