### ISSUE TITLE
UploadAlbum with usertags

### ISSUE THREAD

**Issue by padregeek** [mgp25/Instagram-API#2374]
### Before submitting an issue make sure you have:
- [X] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [X] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [X] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [X] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

Use exact code from uploadAlbum example, only change media info:

```php
/////// MEDIA ////////
$media = [
    [
        'type' => 'photo',
        'file' => '_MG_0533.jpg',
    ],
    [
        'type' => 'photo',
        'file' => '_MG_0533_v2.jpg',
        'usertags' => [
            [
                'position' => [0.5, 0.5],
                'user_id' => 2159689274,
            ],
        ],
    ],
];
```

Error Log/var_dump:
```
Something went wrong: Invalid usertag at index "0": Missing keys "position", "user_id" for user tag array.
```

**Comment by mgp25** [comment]
Just checked the example file and works perfectly, check what @Ant-V said.

Regards

**Comment by padregeek** [comment]
Sorry guys, but I tried with or without quote but already have the same error.

**Comment by halixness** [comment]
@mgp25 having the same error @padregeek  has encountered. I used the same code you posted one year ago: https://github.com/mgp25/Instagram-API/issues/1900#issuecomment-379448359
Tried to put userId as both string and integer, but no way.
Thanks in advance.

**Comment by Daedra22** [comment]
@mgp25 same for me as @halixness described, I updated the devmaster code and then the error occured ...

**Comment by thevisuales** [comment]
Could you finally fix it @ Daedra22 @halixness? I get the same error:

`Missing keys "position", "user_id" for user tag array.`

`$metadata = [
                                'caption' => 'test',
                                'usertags' =>
                                [
                                    [
                                    'position' =>
                                        [
                                            0.5,
                                            0.5
                                        ],
                                        'user_id'  => '230159903'
                                    ]
                            ]
                        ];`

**Comment by austinhutchison** [comment]
It looks like `Utils::throwIfInvalidUserTag` is looking for a format like this:
```
    'usertags' => [
        [
            [
                "user_id" => $userId,
                "position" => [0.5,0.5]
            ]
        ]
    ],
```
which to me seems like a extra encasing array - but it will pass the check.

Unfortunately, I have not successfully uploaded a photo to the timeline with a tag, despite passing the check. Here's the JSON output of the formats I've tried:

```
"usertags":"[[{\"user_id\":\"12345678\",\"position\":[0.5,0.5]}]]" //standard JSON encoding
"usertags":"[[{\"user_id\":12345678,\"position\":[0.5,0.5]}]]" //tried user_id as integer
"usertags":"[{\"user_id\":12345678,\"position\":[0.5,0.5]}]" //removed extra encasing array
"usertags":"[[{\"position\":[0.5,0.5],\"user_id\":\"12345678\"}]]" //flipped position & user_id order
"usertags":"[{\"position\":[0.5,0.5],\"user_id\":\"12345678\"}]" //removed extra encasing array
```

Still trying to figure this out!

**Comment by olb1ue** [comment]
Not sure anyone is still having this issue, but since more recent versions of the api (circa version 4.1 and up), configureSinglePhoto() no longer automatically wraps the $usertag array into the 'in' container. So you need to do:

`$usertags = ['in' => $usertags]; // Wrap in container array.`

**Comment by austinhutchison** [comment]
@olb1ue Can you share the debug JSON output of your usertags on an upload that hits `configureSinglePhoto`?

I tried wrapping it inside `in` and still can't get it to work. 

these formats have all failed

```
  "usertags": [
    {
      "user_id": "1482095101",
      "position": [
        0.5,
        0.5
      ]
    }
  ],
```

```
  "usertags": {
    "in": [
      {
        "user_id": "1482095101",
        "position": [
          0.5,
          0.5
        ]
      }
    ]
  },
```

**Comment by olb1ue** [comment]
@austinhutchison Here's the portion from the debug with the usertags on a post that worked:

`"usertags":"{\"in\":[{\"position\":[0.5,0.5],\"user_id\":\"xxxxxxxxx\"}]}"`

and the code that created it:

`$metadata['usertags'] = ['in' => $rc['usertags']];`

Since my last response, I ran into the same issue with another project except it was only working without wrapping the array in 'in'. It was the same version of this API (7.0.1) so I'm still looking in to what is happening. Either way, I've been able to get them to work by using either the code above, or:

`$metadata['usertags'] = $rc['usertags'];`

**Comment by olb1ue** [comment]
@austinhutchison Here's the portion from the debug with the usertags on a post that worked:

`"usertags":"{\"in\":[{\"position\":[0.5,0.5],\"user_id\":\"xxxxxxxxx\"}]}"`

and the code that created it:

`$metadata['usertags'] = ['in' => $rc['usertags']];`

Since my last response, I ran into the same issue with another project except it was only working without wrapping the array in 'in'. It was the same version of this API (7.0.1) so I'm still looking in to what is happening. Either way, I've been able to get them to work by using either the code above, or:

`$metadata['usertags'] = $rc['usertags'];`

**Comment by austinhutchison** [comment]
@olb1ue thank you so much for posting

During my own debugging I believe I took out the json_encoding step which gave me this output in my `POST` data
`"usertags":{"in":[{"position":[0.5,0.5],"user_id":"xxxxxxx"}]}`

The encoding in olb1ue is necessary so that you get 
`"usertags":"{\"in\":[{\"position\":[0.5,0.5],\"user_id\":\"xxxxxxx\"}]}"`
