### ISSUE TITLE
Can we read other instagram Insight details? [Question][Not Related To API] 

### ISSUE THREAD

**Issue by beshoo** [mgp25/Instagram-API#2400]
Dear all.
This post is not related to the API anyhow, but it is a question in order to improve our Instagram knowledge.

There is a Website named: socialblade.
 **https://socialblade.com/instagram/user/YourUsername**

This website claim that it can show you any Instagram Insight details, I checked one of my new accounts and it returns decent accurate data.

How come this website know my follower growth data without adding my account, and without login to any application?

the only thing you have to arrange is a business account, that is all.
Why business account?

instagram Business account provides Insight details, but not for the public, only the login user can see the Insight details.

How come this "socialblade" show you how many users follow today, and how many unfollow?
And this information is instant information, you don't need to wait one week to collect the information.

**Comment by JRoy** [comment]
Socialblade is constantly tracking thousands of accounts via the official graph APIs. It also has legacy data from when the old API was actually decent. 

The reason a business account is required is mainly due to the [Cambridge Analytica](https://www.nytimes.com/2018/03/19/technology/facebook-cambridge-analytica-explained.html) scandal that occurred with Facebook (who owns Instagram). This made Instagram [phase out](https://www.instagram.com/developer/changelog/) their old official APIs and replace them with the new [Graph API](https://developers.facebook.com/products/instagram/). This new Graph API is limited to business accounts to prevent data miss-handling. 

Hope this answers your questions!

**Comment by beshoo** [comment]
Dear jroy.

Thank you for your reply. 
Actually that what i think, but how they can use the graph api to check other insight without permission? 

As i know any facebook app has to get auth Token from you to read your information. 

I am confused, can facebook app read instagram account insight with out permission? 

Regards

**Comment by seva0812** [comment]
Instagram 75 version pinning ssl key signed
skype: webqart_1

**Comment by mgp25** [comment]
@JRoy thanks for reporting it :)
