### ISSUE TITLE
Get followers not returning each user following and follower count

### ISSUE THREAD

**Issue by fquirogam** [mgp25/Instagram-API#2573]
Hi, I've been checked the library but I run with the following issue;
When I get the followers of an account, the array containing the Model\User objects that are its followers does not include each follower following_count and follower_count, and if I want to do this I have to make a request for each user using the getUserInfoById method, but this ends on my application to making too many requests. I'm missing something? Is there a way to get all my followers following and follower count without making so many requests to the api?

**Comment by mgp25** [comment]
No, that is how Instagram app works. If you see at your mobile device, go to your followers. Do you see any follower/following count? You don't, you need to go to the user profile in order to see this. Whenever you code something with the API you need to think how the app does, because the API does the same.

Hope I have answered your question. By the way, please, use issue template, otherwise your issue will be ignored.

Regards
