### ISSUE TITLE
Problem on comment

### ISSUE THREAD

**Issue by bolds07** [mgp25/Instagram-API#2652]
---

### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [x] Other

 
### Describe your issue

Well, please the whole text before closing the issue, i've been using this api for 2 years and i know that "challenge_required" related stuff is never answered but this is something that might be looked closely.

I was going to test something, so i ran my test code which just logs in and comment in my photo, but i got this answer:

{"message": "feedback_required", "comment_error_key": "comment_si_blocked", "spam": true, "feedback_title": "Action Blocked", "feedback_message": "This action was blocked. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.", "feedback_url": "repute/report_problem/instagram_comment/", "feedback_appeal_label": "Report problem", "feedback_ignore_label": "OK", "feedback_action": "report_problem", "status": "fail"}

* I run it in my local pc which a random home based ip: so it couldn't be ip related stuff
* my account hadn't commented nothing over a week: so it couldn't be a quota exceeded stuff
* and the comment was just "online" 

so i found somehow my account got blocked, then i went on instagram app and tried do the same, and it worked...

so while looking for something weird that i might had done at first time i decided to use an old session i had cached somewhere to login the same account (from the cached session) and do the same. it WORKED

so while i cant precisely say what was the root cause of this issue it might be good to keep an eye over it since it looks to me instagram is doing a more intense seek for non official api usage

**Comment by JRoy** [comment]
We do not give support for `feedback_required`. Please read over past issues before opening.

Regards.

**Comment by bolds07** [comment]
first line of my text man...

> Well, please the whole text before closing the issue, i've been using this api for 2 years and i know that "challenge_required" related stuff is never answered but this is something that might be looked closely.

do not be a bot, read

**Comment by beshoo** [comment]
I have long experience with this problem, you can nit compare old sessions to the subject of creating a new one.

We all do agree that instagram will know that you are using un official api. 

And we all agree, we are login on our own responsibility.

Even if you used your home wifi connection, that is not important. 

In general, this is not free api, i advice you to sign up with paid version of this api, so you can get latest keys signatures to imitate the instagram app as much as possible

**Comment by JRoy** [comment]
@bolds07 I'm not a bot, I read your ticket and after reviewing, there is nothing different here: We still don't support `feedback_required` tickets (even if you acknowledge that we don't support them).

We can do nothing to help you here, the bottom line is: This API isn't a perfect Android app emulation and if Instagram really wanted to, they can detect this. The reason we don't support `feedback_required` errors is due to the fact that we can't do anything to help you with this and that everything you can do has been talked about **numerous** times in the past.

The little we can do to suppress these errors is to improve the API. Either by people contributing or by the devs updating the API. So please don't discourage us by demanding support and calling us bots.

Cheers.

**Comment by bolds07** [comment]
> In general, this is not free api, i advice you to sign up with paid version of this api, so you can get latest keys signatures to imitate the instagram app as much as possible

@beshoo i disagree about this.... this is a very sensitve point where i disagree with mgp25 idea... this api should "stand" at some instagram version and keep stable as possible... instagram app is at sixtysh version but it still allows users with fifitysh versions tu use it (is not forcing users toupdate) so latests keys and stuff are not really necessary try to mimics the real instagram behavior would be a better move (but again this is my opnion this api is driving more to include more features what is also a not wrong approach)

@JRoy im just saying that would not take you much time to read my report... if you start noticing that many people writing similar reports even about "feedback_required" maybe it is a sympton of an api issue (instagram start checking somethnig it wasn't checking before) and just alert the users about the situation

**Comment by beshoo** [comment]
I agree with you.
Well, instagram has kind of pattern detection. They know once you login if you are using the app or not, they can block this api completely, but instagram needs some bot behavior, but with out spam. 

Think with me, what if instagram add recaptcha with login form? 
This will end this lib for ever. 

Some times your ip address has problem with the api but not with the app it self. 

Did you use this api to spam instagram in any how? 
Send more than 15 likes per hour as an example.

I am not sure what is your case, but this error has nothing to do with this lib. 

I am using this lib since 2 years, checkpoint, and feedback required can not be solved by this api. 

It is not api bug. 
Using same phone number with multiple account to pass phone verify may triger checkpoint. 

Any way, it is true that your problem has nothing to do with this lib. And JRoy did the right step when he close this.

Regards
