### ISSUE TITLE
Question About Instagram

### ISSUE THREAD

**Issue by bakill3** [mgp25/Instagram-API#2680]
### Before submitting an issue make sure you have:
- [X] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [X] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [X] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [X] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [X] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [X] Question
- [ ] Other

---

### Describe your issue

Hi.
 First of all I just want to thank @mgp25 and other devs involved for developing this amazing API. I have a question about Instagram, and I thought this would be the best place to ask it.
If I login on my account and I put a challenge required code, does that mean that my IP is forever unblocked/unlocked or can Instagram ask a code again?

Thank you for your time.
Best Regards, Gabriel Brandão

**Comment by mgp25** [comment]
Hello,

We don't support `challenge` related stuff, but answering to your question: Yes, Instagram can ask again for a verification

Regards

**Comment by bakill3** [comment]
Thanks for the fast response ;)

**Comment by bolds07** [comment]
Challenge required stuff is most non related to ip... 

Só your idea you needed to solve a challenge because somehow your ip is flagged is wrong.

If you ip is flagged you get really blocked and can't do anything 

Challenge required is most related to a new device_Id trying to login in your account 

It also can be triggered by other stuff wich I don't know

I do travel a lot, I don't use nothing extra official of instagram in my personal account and I do get a challenge to solve once a month

Don't know why

Actually Facebook Co have policies that think people don't travel (even crazy it sounds) I get my ads blocked and my account locked because I tried to run an ad campaign and my credit card is from Brazil but I was in Colombia

**Comment by mgp25** [comment]
It is explained in the wiki...

```
If you get checkpoint_required, it means that Instagram wants you to prove that you are human and that you are the owner of the account. It can easily get triggered if you put your script on a server which is in a country that you don't normally log in from, for example. Simply login to your account via the official website or your mobile device - that should fix it. If you still get the error again, it means Instagram dislikes your server's IP and that you must login to your account via Instagram's website and your server's IP to prove to them that your server's IP is a human.
```
