### ISSUE TITLE
[Feature Request] Social Media Account Linking

### ISSUE THREAD

**Issue by akaCube** [mgp25/Instagram-API#2683]
### Before submitting an issue make sure you have:
- [x] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)
- [x] [Using latest API release](https://github.com/mgp25/Instagram-API/releases)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

Hi, I am currently getting used to this library and i like it very much. However i can not seem to find any kind of api endpoint/implimentation for linking / inlinking any other social media accounts to the instagram account.

From my understanting it is not in a web-browser within the app, so there should be an api for it. I am not good at reversing and before diving in too deep, i wanted to ask for help.

The only thing, i could find by browsing the internet is the api call **linked_accounts/get_linkage_status/**, which can be accessed by a simple GET api call. 

Thank you.

**Comment by JRoy** [comment]
After researching this, I have found this request infeasible to complete.

`linked_accounts/get_linkage_status/` is the only thing I would have considered adding due to the rest of the things requiring some type of oauth or credential handling that is out of the scope of this api. However, that endpoint is basically useless as it only returns your facebook linkage status.

Regards.
