### ISSUE TITLE
Warning: Use of undefined constant streamUploadUrl - assumed 'streamUploadUrl' (this will throw an Error in a future version of PHP) 

### ISSUE THREAD

**Issue by obscurecodes** [mgp25/Instagram-API#2731]
( ! ) Warning: Use of undefined constant streamUploadUrl - assumed 'streamUploadUrl' (this will throw an Error in a future version of PHP) in C:\wamp64\www\robot\modal\Post.php on line 169
--

**Comment by obscurecodes** [comment]
it was a syntax error

**Comment by ASteb** [comment]
ЭДБББЮБЖ..ХХ.ЖД,_юж,,


Отправлено из приложения "Почта" для Windows 10

От: Mohammadreza Tahmasbi
Отправлено: 30 июня 2019 г. в 13:49
Кому: mgp25/Instagram-API
Копия: Subscribed
Тема: Re: [mgp25/Instagram-API] Warning: Use of undefined constantstreamUploadUrl - assumed 'streamUploadUrl' (this will throw an Error in afuture version of PHP) (#2731)

it was a syntax error
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
Это сообщение проверено на вирусы антивирусом Avast.
https://www.avast.com/antivirus
