### ISSUE TITLE
Why you deleted our issue

### ISSUE THREAD

**Issue by mohsinbolatar** [mgp25/Instagram-API#2762]
If you don't want to give answers or solution. Then close our issue instead of delete.
That problem i encourage.
When i post from api add post - photo and caption then post goes without caption.
You delete my previous issue also you close one another user issue that he encourage of same me.

**Comment by mgp25** [comment]
- Invalid issue template
- Not providing debug log
- Not providing enough information
- Not provided steps or detailed description

why should we bother answering when you don't bother reading the issue template and repo guidelines?

**Comment by borutkovacic345** [comment]
I have similar issue. I have been blocked because i asked something about direct inbox feature. They probably assumed i was one of those users who want to spam others. I can prove that i am not. Looks like it was misunderstanding; We are working on webhook service and we are only sending replies (we dont send messages first) based on keywords.

We want to help. I already contributed to the project and i am planning to do more.

**Comment by beshoo** [comment]
Yes true, and no error message with the log
