### ISSUE TITLE
Create Accounts

### ISSUE THREAD

**Issue by doctorbinsibar** [mgp25/Instagram-API#29]
Hi, im creating Accounts, but when it says everything ok.
If successful creating Accounts 1 of 5 Try. 
The Accounts getting deleted instantly. 
Anything what we can change to create accounts which i can post on ?

**Comment by npeplow** [comment]
I'd also be interested to know if anyone else is having success with the default setup that's (awesomely!) provided here. Even using residential IP's, the accounts I create are instantly banned after being apparently successfully created.

Could it be due to an outdated IG_SIG_KEY, or perhaps the user agent is now known and blocked? tried playing around with both, but a little stumped now

**Comment by xteraflopx** [comment]
@npeplow @doctorbinsibar

You cannot create accounts because Instagram now requires a special HTTP parameter called the "qs_stamp" ... Only me and a few other people know how to generate this code...

**Comment by mgp25** [comment]
_sigh..._ i'll check it tonight guys, but i guess its quite simple

**Comment by janicheg** [comment]
@mgp25 , do you have any news?)

**Comment by xteraflopx** [comment]
The repository has the version marked as 7.13.1

If you are using HTTP parameters from an earlier version of the app, or using URL paramaters in a different order than how they would appear in the actual 7.13.1 version, Instagram will obviously know you are a bot. Also if you never submit requests to the analytics, Instagram will also know that you are obviously a bot.

**Comment by janicheg** [comment]
@mgp25, yeap, I tried to wrote to him, but i think he'll try to sell it. At the moment I try to understand in apk source how to generate this qs_stamp. 

All of HTTP parameters equals to this repository.

What do you mean, when you write "requests to the analytics"? Is it requests when user clicking some of items?

**Comment by mgp25** [comment]
I've been busy, im doing other projects, but ill check it tonight in a couple hours. Sell it? I do everything for open source and free.

This is quite easy, i dont understand why people can check it by theirselfs, i mean, you only need a proxy, the apk is not required since you only want the http request.

And talking about the analytics is just some data the app sends to FB server, features, user activities, keep in mind that facebook earn money by knowing as much as possible how the user is, thats why this `analytics` etc etc...

Checking it in an hour.

**Comment by janicheg** [comment]
@mgp25, I mean than @xteraflopx trying to sell it, sorry.

I captured some of analytics request, but I think they use sockets and don't see all of requests.

**Comment by mgp25** [comment]
@janicheg right now i only have an iOS device, so, if you have time and have an android device, get in touch with me (mail in my profile page) and i'll do this, meanwhile im extracting iOS sigKey.

**Comment by mgp25** [comment]
Oks, `qs_stamp` its pretty easy to figure out if you have basic reverse engineering skills. I have tested and everything works perfectly. But since people is using this for creating lots of accounts, etc etc, im not going to release it, maybe in a future.

Regards

**Comment by mgp25** [comment]
Interested one, please contact with me via mail

Regards
