### ISSUE TITLE
Sessions and cookies

### ISSUE THREAD

**Issue by phibershinigami** [mgp25/Instagram-API#2907]
# Question
Once i log in, it accepts whatever password I enter with that name.

### Example
-> I logged in 'xxx' username and '123' password. (Correct)
-> Logout.
-> Trying again with another password and accepts

### Code (Optional)

```php
try {
        $ig->login($_POST['username'], $_POST['password']);
        // login successfull codes..
    } catch (InstagramAPI\Exception\InvalidUserException $e) {
        header("Location:http://localhost/charmander/last/login?hata=invaliduser");
        $kontrol = 0;
        exit(0);
    } catch (InstagramAPI\Exception\IncorrectPasswordException $t) {
        header("Location:http://localhost/charmander/last/login?hata=invalidpw");
        $kontrol = 0;
        exit(0);
    } catch (Exception $y) {
        header("Location:http://localhost/charmander/last/login?hata=twofactor");
        $kontrol = 0;
        exit(0);
    }
``` 

##  Other Question
Generates cookies even if the username is invalid. How can I prevent this?

### Images

https://i.imgyukle.com/2019/10/01/oANeic.png

**Comment by JRoy** [comment]
We don't support web usage, and this isn't easily preventable. 

Cheers.

**Comment by mgp25** [comment]
This has been answered multiple times. One you have done a successful login, the `login()` function will only set the active user, it won't check wether the password is correct or not as it is simply telling the API: Hey, check if you have an active session for this username, if so, go ahead and continue making requests. As long as you can make requests the password would be valid, when the password changes, session will eventually kick you out, for that reason you have to try catch the `login()` function in order to prevent that in the future.

Also, what @JRoy said https://github.com/mgp25/Instagram-API/issues/2907#issuecomment-537024557

Regards
