### ISSUE TITLE
When sending media (photo or video) returns an error: "Invalid request options"

### ISSUE THREAD

**Issue by DimaLondon** [mgp25/Instagram-API#3032]
Please help solve the problem. When sending media (photo or video) Instagram returns the error: "Something is wrong. Please check your input and try again",  so Instagram-API returns "Invalid request options". 

I do everything exactly as in your example https://github.com/mgp25/Instagram-API/blob/master/examples/uploadPhoto.php Until recently, everything worked well, but now it does not work.

I understand that this is a duplicate https://github.com/mgp25/Instagram-API/issues/2972 but this problem is still not resolved and many people suffer because of it.

This is my error log:

> POST: https://i.instagram.com/api/v1/upload/photo/ → 31.51kB ← 400 58B RESPONSE: Something is wrong. Please check your input and try again. 

And the class returns an "Invalid request options" error.

Installed the latest version of "Instagram-API" through the composer.

Thanks in advance.

**Comment by JRoy** [comment]
Opening multiple issues for the same problem doesn't fix the problem any sooner and just annoys us 🙄

We understand the problem and want to implement a proper fix instead of a quick fix. Our premium subscription already has this and other issues fixed. Please see #2655 for more information!

Regards.
