### ISSUE TITLE
Add $rankToken param to getFollowers method on the wiki page

### ISSUE THREAD

**Issue by Arman-Hosseini** [mgp25/Instagram-API#3048]
Must be added [here](https://github.com/mgp25/Instagram-API/wiki#getting-followers).

**Comment by vatansbeytr** [comment]
Well I added it.

`set_time_limit(0);
date_default_timezone_set('UTC');
require 'C:\Users\xD_xD\vendor\autoload.php';
/////// CONFIG ///////
$username = 'name';
$password = 'pw';
$debug = true;
$truncatedDebug = false;
//////////////////////
$ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
try {
    $ig->login($username, $password);
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
    exit(0);
}
try {
    // Get the UserPK ID for "natgeo" (karincaciftligim).
    $userId = $ig->people->getUserIdForName('karincaciftligim');
    // Starting at "null" means starting at the first page.
    $rankToken = \InstagramAPI\Signatures::generateUUID();
    $maxId = null;
    do {
        // Request the page corresponding to maxId.
        $response = $ig->people->getFollowers($userId,$rankToken,$maxId);
        
        $followers = array_merge($followers, $response->getUsers());
        
        $maxId = $response->getNextMaxId();
        // Sleep for 5 seconds before requesting the next page. This is just an
        
        // Instagram will throttle you temporarily for abusing their API!
        echo "Sleeping for 5s...\n";
        sleep(5);
    } while ($maxId !== null); // Must use "!==" for comparison instead of "!=".
} catch (\Exception $e) {
    echo 'Something went wrong: '.$e->getMessage()."\n";
}`
New Error: **Something went wrong: Throttled by Instagram because of too many API requests.**
And my new error even I tried first time already banned it isn't possible I guess there is something but what ?

**Comment by Arman-Hosseini** [comment]
@vatansbeytr Please create a new issue to check.

**Comment by JRoy** [comment]
Added :)
