### ISSUE TITLE
GetHastagFeed Function

### ISSUE THREAD

**Issue by marks97** [mgp25/Instagram-API#461]
Can I receive less information with geHastgFeed function to take less to make the request? Sorry if I wrote bad english, and thank you!

**Comment by mahmoud015** [comment]
by limit the request

**Comment by mgp25** [comment]
You can't change Instagram's server response. When you call `getHashtagFeed`, Instagram will answer with available items, if you want to see more data, then you need to use `maxId` param, so whenever it exists `next_max_id` you can do this: `getHashtagFeed($hashtag, $maxId)`.

And since all responses are objects, from the response, if there is more info to show, you can use `->getNextMaxId()` and use it as second param of the function

Regards

**Comment by marks97** [comment]
How do I limit the request? What $maxId should I set?

**Comment by mgp25** [comment]
Thats called pagination, when you call that request, its response is an object, you can see wether is more to load checking `->getNextMaxId()` and passing that value to the function

Regards
