### ISSUE TITLE
How has this library held up in the past?

### ISSUE THREAD

**Issue by bramgg** [mgp25/Instagram-API#531]
I understand there are no guarantees with something like this, but I'm considering using this library for a project and am wondering how often the posting photos aspect (or anything required to get to that point, such as logging in) has broken in the past, and how long it usually takes to be fixed. If anyone can comment on this from their experience it would be much appreciated.

Thanks for all the work done here!

**Comment by bramgg** [comment]
Really?

**Comment by mgp25** [comment]
@bramgg this is an issue tracker. To post issues related to the API. Remember that.

Q:How long takes something to be fixed?
A: Sometimes nothing, sometimes days, sometimes months or maybe years. Depends if i have time or if i want to code. But recently this project is making me sick because of the people that are using it, so maybe i stop updating it/giving support and start with something new

Regards

**Comment by bramgg** [comment]
Okay, thanks for the response. If you don't mind me asking, who are the people making you sick?

**Comment by mgp25** [comment]
Spammers
