### ISSUE TITLE
Endpoint Capture

### ISSUE THREAD

**Issue by mangledbottles** [mgp25/Instagram-API#664]
Hello mgp25,
I was looking through your wiki to learn more about this and saw you had great detail on capturing the apps key signature but could you possibly extend more on how to capture endpoints?? 
I have used google but everything I try such as Charles proxy or burp suite dont seem to work for me..
You said to use a proxy, I can use a proxy I just dont know what program to use haha
Could you maybe shed some light on this?

Anything you give will be very helpful for me learning.
Thanks :)

**Comment by mgp25** [comment]
@mangledbottles install the proxy software you want: mitmproxy, charles, ....... there are a lot of them.

Install the CA in your device, you need to do this step in order to capture SSL traffic. Then just point your device network setting to your computer ip which is running the proxy and the port.

If everything done correctly, you should start seeing all the traffic that goes through your device. But as said in the wiki, i think you can find better explanations than mine and with image captures, so you can follow step by step

Regards

**Comment by mangledbottles** [comment]
Thank you very much!! Really helpful :) 👍
