### ISSUE TITLE
fbUserSearch endpoint - how is this different than regular search?

### ISSUE THREAD

**Issue by milesrichardson** [mgp25/Instagram-API#69]
Hello,

I'm wondering what exactly the `fbUserSearch()` function does, and how it differs from `searchUsers`. How is the `fbsearch` endpoint different from the `users/search` endpoint?

Thanks

**Comment by mgp25** [comment]
@milesrichardson im not sure, the best way to check it is to run the functions and see the response in both cases. Maybe it can be that you can search by the name shown in facebook and see if the user has Instagram installed too. Im bot sure, since i didnt look at the response when i did it.

Regards
