### ISSUE TITLE
I am Trying  to understand how the new lib is working.

### ISSUE THREAD

**Issue by beshoo1** [mgp25/Instagram-API#691]
Good job with new code style , but it is not clear as old one , so i am trying to understand the way and yes i did search via github.com search function.

Now , regarding any Get function , i can not find the function in the code . eg : getNextMaxId()
it has to be hardcoded , but if you search for it , you can not find the main function!
but it is works :)
and all other Get function like getItems,getUsername ... etc 

In old version we do open the response file know the functions name , and use it.
Now we just see some vars , extended the response class.

it is new pattern for me , please advice.
is there a list of available Magic Functions :)  

Regards

**Comment by mgp25** [comment]
_Sigh..._

if you have var named `pk`, getter is `getPk()`, and so on...

`get + name_var` first letter or var uppercased..

Another example: 

```php
$media_id;
```

getter: `getMediaId()`

I think its pretty easy and intuitive

Regards

**Comment by beshoo1** [comment]
wonderful,  but where is the getter hard code function? .

eg getMediaId it is a function?  correct?

**Comment by juicytuna** [comment]
@beshoo1 Check out the AutoResponseFunctionSetter class. All Response classes extend this class and it has methods to process getters and setters for the valid properies of an object..

**Comment by jpmoney5065** [comment]
@beshoo1 you can use getFullResponse to see all possible properties.

If someone wants to take the time to go through every response and list all the possible properties and put it in the wiki, that would be nice.

**Comment by Lastwisher** [comment]
I want to clarify some points. 

When i code that responses main idea behind that was adopt changes at future, instagram api changes everyday so code should follow this changes easily, also everything sould be overwritten if needed.

There is no hardcoded getMaxId() function i mean if you expect function getMaxId() function in responses there is none hardcoded. Instead of static function i write a setter and getter to dynamic funcions as mentioned above you can see AutoResponseFunctionSetter class.

This way we are able to adopt changes and build a dynamic system. In near future ill add some genarators and unit testing for easier debug and tests for future.

also nowadays instagram api little bit messed up, like : one response returns max_id another next_max_id maybe we can do some standarts in responses, like getMaxId() for all responses or isMoreAvailable()

Btw new response system also allow you to overwrite functions eg: 
you can write your own getMaxId() function in response class or you can manupulate all responses by extending autoresponsefunctionsetter class.

This is also give us flexibility without messing source lib.

Btw @jpmoney5065 i did add all missing properties i assume when i do a unit test its will tell us did we miss anything.

Sorry about bad english, regards :)

**Comment by frrakn** [comment]
"When i code that responses main idea behind that was adopt changes at future, instagram api changes everyday so code should follow this changes easily, also everything sould be overwritten if needed."

In my opinion, the point of an API is to provide a stable abstraction over what is happening. I definitely still think this is still a very good, clean, and helpful API, but its instability is definitely a negative. Programmers that use this should not need to understand what the AutoResponseFunctionSetter class does - in fact, they really shouldn't have to look past the method signatures in `Instagram.php`. The fact that they do have to dig means the code is not clear, and when code is not clear, it is difficult to integrate. Personally up until recently, I've found this API to be really good, and had a couple systems go off of the `dev-master` release for the latest bugfixes. However, the most recent changes have completely altered the way the API is meant to be publicly used. This is okay, but if it happens really often, it works against the purpose of this API being a helpful tool.

**Comment by jpmoney5065** [comment]
I tend to agree with @frrakn 

Also when he said: 

> I don't understand the point of adding the JSONMapper. Kills code readability and introduces bugs like this.

Basically taking the raw data from instagram and doing `jsonEncode()`, `jsonDecode()`, then changing the names to camelcase.

Might as well have gone back to working with straight arrays

**Comment by Lastwisher** [comment]
Ok look like we will have deep conversation here, i have no issue with criticism i can learn alot from diffrent opinions.

Yes im totally agree with you "an API is to provide a stable abstraction over what is happening behind the scenes"

What i did on behind of scenes provide a stable understandable clear output for all of the requests.

Let me tell you how i decide to contribute to this project. Im coding a complate system for instagram and i need a strong reliable api for that. I checked all of unoffical apis for this matter infact i found some really good work on git hub, but most of them dosent update often and api versions are old. 

I check this code, @mgp25 is really done great job to replicate phone requests i check by proxy and compare results was awesome. When i started to develop by this api i see that there all lot of custom designs like getUsernameId() and at some responses we get direct json decode ( still some missing) and some of response doesn't have same pattern, one of them return getUsernameId another one getPk another one does'nt have getter function another one no setter method. So there is a great background work is just needed to shaped good.

What im trying to do create a clean easy use patterns for all of responses and background work. 

With response changes when we accomplish;
1) All properties have clean easy styled setters and getters
2) Way too much clean code  
From this : https://github.com/mgp25/Instagram-API/blob/e0ab2a3c169a6c26178361d5bedcbbeb5d2376a2/src/http/Response/Objects/Item.php 
To this : https://github.com/mgp25/Instagram-API/blob/master/src/http/Response/Objects/Item.php
3) A way that you can manupulate ALL response without messing too much of src of library 
4) Also a way that you can manupute single response without messing code
5) Clean way to request and get response back.

And this is leads us to next step, scalabilty. 
Now we are able to take care of new responses requests and others in seconds. 
Now we can create a unit tests to keep api stable and running.
Now we are able to define requests and make them classes.

About JsonMapper;
Yes as @jpmoney5065 said basicly decodes data and adds to proper places in objects, able to do them by reading phpdocs we create inside of code. As i see before objectes where populate by blood and tears as [you can see](https://github.com/mgp25/Instagram-API/blob/e0ab2a3c169a6c26178361d5bedcbbeb5d2376a2/src/http/Response/Objects/Item.php) 
If you guys want to keep develop this way you are welcome. 

But dont expect to go back and leave our awesome new futures behind. Year is 2016 we cant go anywere with putting our spagetti coding inside of classes. 

Regards.

**Comment by beshoo1** [comment]
Dear @Lastwisher, thanks for you wonderful code, it's peace of art!
But the problem that we have here is : there is a misunderstanding between us as dev as you can see here, I have a lib base on this lib, now I have a lot of things to change.

No problem, I can do that ,
I love the way you made the new lib, but the problem :
There is no changelog, we have to dig and find out what is gooing on, in terms of how to call the getters, show me a line in the Wiki talk about it?

> if you have var named pk, getter is getPk(), and so on...
> 
> get + name_var first letter of var uppercased..
> 
> Another example:
> 
> $media_id;
> getter: getMediaId()

It's easy and I love it. But mr @mgp25 always assume we are not looking, we ask directly, and maybe we are lazy ... No, we are not, but we struggle to understand and offer help if we can.

Finally, thanks for any one type a line of code, it is a great team work,

**Comment by mgp25** [comment]
I approved @Lastwisher code, its a great improvement.

I know most of you need to do changes in your code because of the changes. I know we could tell this before pushing so you have time to do the changes, but honestly, i dont have too much time to do things, so if i can make changes i will, and when its possible for me i will write documentation.

All of you need to realize that every change that is done in the API it is for its good and despite that i havent wrote any full and clear documentation yet about the changes made, you all need to be patient, im very busy with exams, and collaborators have their life too, so be patient. I do this for fun, if the fun ends i close the project as simple as that.

Regards

**Comment by beshoo1** [comment]
>  I do this for fun, if the fun ends i close the project as simple as that.

Please , don't think like that , we do love the fun in this  project , and as i told you befor we are in same side but with different glasses . now i can see by your glasses , you are right.

Thank you

**Comment by Lastwisher** [comment]
Im happy to see that we all in same page 👍
