### ISSUE TITLE
get full image likers

### ISSUE THREAD

**Issue by mahmoud0m0** [mgp25/Instagram-API#70]
hey, when i try to get likers for image with 5000 likes it only return 994 persons how do i get the full list ?
also does instagram have limits to follow people or shouild i do anything to prevent them from knowing that im following users automaticly ?

**Comment by RageBrahimi** [comment]
Question 1) Apply the same principle as [here!](https://github.com/mgp25/Instagram-API/issues/54)
Question 2) Also, with regards to your 'limit' - everything has a limit; just don't make it obvious is the only tip.

**Comment by xteraflopx** [comment]
@mgp25 putting up this repository has been the single worst decision ever. Any dedicated and intelligent reverse engineer can figure out Instagram for themselves, like I have done. Just look at all these stupid people asking stupid questions, because they can't figure out anything for themselves. You're just giving a tool to stupid people to make terrible bots.

**Comment by mgp25** [comment]
@xteraflopx the problem isnt the source i published but the people.
Is not the tool but what you do with that tool, is a moral and ethic fact.
