### ISSUE TITLE
How to avoid Login_requured

### ISSUE THREAD

**Issue by nubinter** [mgp25/Instagram-API#841]
Hello there, 
First of all I want to thank you to whoever made this API. You really do a great job. 
Maybe this is not an issue, but I don't know where to ask, so decided to post it here.

ErrorException login_required is really bugging me. Everytime I successfully login thru this API, for sometimes this error will show up, and so I have to login again. And the login process is really a pain if checkpoint required. So, is there some way to avoid an account being logged out by itself? i have tried to provide a relogin feature for my user, but It's failed because I encrypt the instagram's password in my database and so I got the wrong password error.

**Comment by mgp25** [comment]
@nubinter if you have logged in successfully you dont need to login again, you can continue with the session. In some cases, if you use a proxy and it changes the location, it will require to login again in order to verify you. And in other cases, Instagram will ask you to verify with the checkpoint.

Anyway, you can add all the logic in your script in order to catch those exception and handle them

Regards
