### ISSUE TITLE
hashtags

### ISSUE THREAD

**Issue by Triden** [mgp25/Instagram-API#874]
Hello, you do not know. For whatever reason can not work hashtags? Publications can be seen from your computer. On your phone is not visible. Search hashtags.

**Comment by mgp25** [comment]
@Triden yes, this is a knon issue. Maybe some kind of Instagram restriction since we are using an unathorized API i guess, or maybe the API is yet to be completed.

Regards

**Comment by Triden** [comment]
You are faced with this already?

**Comment by mgp25** [comment]
@Triden yes, since i started this API in late 2015, is still happening, maybe it is becuase the API has to be finished yet, to make exatly the same requests and generate the tokens the same way the Instagram app does. Or because of that, Instagram makes some stuff restrictive so API users cant abuse them

Regards

**Comment by Triden** [comment]
I think I found the reason. Perhaps you can check it. Unfortunately, my skills is not enough. There is a description of the post and comments. So, if the hashtags under the image to leave through the small amount of time as a comment, the hashtags are beginning to work in the search. Do you wonder that?
