### ISSUE TITLE
na

### ISSUE THREAD

**Issue by codeninjacode** [mgp25/Instagram-API#915]
nothing to see here.

**Comment by frrakn** [comment]
?? want to tell me what's wrong?

**Comment by frrakn** [comment]
That's fine, I reported you to GitHub. @mgp25 FYI - this left a comment calling me out saying that I should stop contributing because "my code sucked". When I asked him what was broken he withdrew everything and edited his comments.

**Comment by mgp25** [comment]
No matter what happens, we always need to be respectful with others. @codeninjacode im sorry but i have to block you. This is an open repository and here there are ideas from many many people, and thats awesome, you can discuss your ideas here, and contribute all together to build a better API. I accept Pull Requests from everyone, but there are some things that we at least me, dont tolerate and its being unrespectful with other people.

If you think this is an error, please contact me via email, and instead of arguing or making stupid things, lets talk, discuss and build this API like civilized people

It is kind of sad seeing this kind of attitude.

_sigh..._

**Comment by frrakn** [comment]
For the record if there actually IS something wrong please let me know. I also actively use this library (which should go without saying, this is the reason I contribute), but I'm not familiar with all the different ways it is being used. Happy to work with and accept all constructive comments, just please tell me what is wrong and I will fix any changes I've made.
