### ISSUE TITLE
Problem with big numbers on 32bit system

### ISSUE THREAD

**Issue by zuexo** [mgp25/Instagram-API#996]
Since recent changes to http interface (e37650b9d37c4cd31e2bfeded77768a6026743e6) big numbers like 'next_max_id' and 'pk' break on 32 bit systems.

**Comment by SteveJobzniak** [comment]
May be related to this (which was never solved in that other library):

https://github.com/liamcottle/Instagram-SDK-PHP/issues/14

Basically, Instagram "pk" values are big integers. They can possibly be stored in floats instead of int, but sometimes even a float overflows and is too small.

So we should possibly change all "pk" and "next_max_id" handling to use strings instead.

**Comment by newfolders** [comment]
And this is exactly what I'm doing in twitter api. Strings instead of BigIntegers. Sounds good.

**Comment by mgp25** [comment]
Fixed in commit https://github.com/mgp25/Instagram-API/commit/92f0da3b961f3ba8008c1faa58f9dd746bcd7bd6

**Comment by SteveJobzniak** [comment]
Further fixed in 21c48ac7. Should all be taken care of everywhere now!
